### ISSUE TITLE
Backtrack crashes my game at random times

### ISSUE THREAD

**Issue by StormiiGH** [Fedoraware/Fedoraware#1001]
Version 1.6
WIndows 11
doersnt matter which config i use it will still crash

game crashes whenever using backtrack, if i get killed if i disguise, doesnt matter what i do it will still crash

**Comment by xxmyn** [comment]
I cannot reproduce this issue at all. Ignoring the fact that we don't provide support for Windows 11, please attach your visual and normal configs, the config file produce by the game after running the host_writeconfig command in console, and a video of the issue occurring.

**Comment by lnx00** [comment]
This is probably related to #1000. Even if it isn't, the lack of a config or steps to reproduce don't help with fixing this.
