### ISSUE TITLE
Aimbot bug when shoot in sticky and teleporters

### ISSUE THREAD

**Issue by Trafic0** [Fedoraware/Fedoraware#1009]
**Fedoraware Version Date: last version**  
**Windows Version: idk how to see what version i use**  

## Steps to reproduce: 
1 activate the aimbot
2 shoot sticky and teleports

1 activate the aimbot
2 shoot sticky and teleports

**Comment by Trafic0** [comment]
> Please include the class you are using & the weapon(s) that it affects. In the case of the video, please record another one in first person.

ok i will record another one

**Comment by danfanofdead** [comment]
Not only for projectile but hitscan aswell

**Comment by Muffinmaker2** [comment]
had the same issue with melee weapon and the silent aimbot smooth when someone spectates you yesterday. it just aims to high and then it doesn't hit the teleporter

**Comment by xxmyn** [comment]
I realise I havent tested if it fixed it for stickies, but it should have.

**Comment by xxmyn** [comment]
Ok I tested it, its fixed for stickies.
