### ISSUE TITLE
Bug from my pov

### ISSUE THREAD

**Issue by danfanofdead** [Fedoraware/Fedoraware#1010]
Fware version: latest build.
Win 11
Misses teleporter with some projectile and all hitscan
config: https://dropmefiles.com/X3JaQ
Steps to reproduce:
1. load any map local or not
2. create a teleporter via "ent_create obj_teleporter" or find one
3. Press aimboat key
Video:
https://youtu.be/xt0QBWx9T4w

**Comment by danfanofdead** [comment]
I know win 11 is not supported but it shouldn't change anything.

**Comment by xxmyn** [comment]
Whoops.
