### ISSUE TITLE
Crithack

### ISSUE THREAD

**Issue by Zagibator** [Fedoraware/Fedoraware#1021]
**Fedoraware Version Date:  Aug 31 8:42Am GMT+3 
**Windows Version: 10

## Configs used:
my main config, that i used early, early crithack worked, now - not

## Description:
Crithack just doesnot work

Turn on crithack
Binded crithack to key "E"
Tryed to use it with weapons where crits aviable
Press "E"
Attack
No crits

**Comment by xxmyn** [comment]
please attach your config, nobody knows what your main config is.

**Comment by xxmyn** [comment]
YES! in the older versions you had to preheat the enemy, however with new technology the heating can be instant!

**Comment by Zagibator** [comment]
> YES! in the older versions you had to preheat the enemy, however with new technology the heating can be instant!

that is nice new feature)
