### ISSUE TITLE
Sniper sightlines stay on screen

### ISSUE THREAD

**Issue by nguyendangm844** [Fedoraware/Fedoraware#1028]
**Fedoraware Version Date:**  September 6, 2023
**Windows Version:**    windows 10 enterprise ltsc

## Configs used:
[New folder.zip](https://github.com/Fedoraware/Fedoraware/files/12504978/New.folder.zip)

## Description:
Instead of Sniper Sightlines operating on Sniper, it works for all classes

**Comment by Usernamemp44** [comment]
This is a bug I've experienced before. Basically the sniper sightlines stays on screen lol

**Comment by xxmyn** [comment]
Note:
The config provided has both `Vars::ESP::Players::SniperSightlines` and `Vars::Glow::Misc::Sightlines` set to false.

**Comment by nguyendangm844** [comment]
> Note: The config provided has both `Vars::ESP::Players::SniperSightlines` and `Vars::Glow::Misc::Sightlines` set to false.

So how do I set it back to true?
