### ISSUE TITLE
Bactrack crashed my game i re-opened the game and crashed

### ISSUE THREAD

**Issue by f2prebornz** [Fedoraware/Fedoraware#1032]
**Fedoraware Version Date:*03-SEP-2023*  
**Windows Version:*Windows 10 Home Single Language*    

## Configs used:
[Fware.zip](https://github.com/Fedoraware/Fedoraware/files/12508757/Fware.zip)

## Description:
When i activated bactrack and configured it the next match it crash i reopen the game and i joined a server crashed again

## Steps to reproduce:
Backtrack enabled
next match=crash.

joining other match

## Additional info:
I forgot to save the config

**Comment by SNIPE117** [comment]
Have you tried disabling backtrack and joining a new server or atleast rejoining the current server?

**Comment by xxmyn** [comment]
video please, just requeueing out of a match and showing the crash when u join the other one will help.

**Comment by f2prebornz** [comment]
Nevermind i fixed it
