### ISSUE TITLE
attributes changer

### ISSUE THREAD

**Issue by frickinloser** [Fedoraware/Fedoraware#1034]
can u guys add the festive option i know its in there
wtf does ancient do
can u guys use IsAustraliumItem
fix the sets of the weapon effects!!

**Comment by Muffinmaker2** [comment]
bro thats not the suggestion forum ._.

**Comment by frickinloser** [comment]
> bro thats not the suggestion forum ._.

Damn can they add festive tho

**Comment by lnx00** [comment]
This is not even worth a discussion. Please put in more effort next time.
