### ISSUE TITLE
Auto backstab doesn't stab sometimes

### ISSUE THREAD

**Issue by lnx00** [Fedoraware/Fedoraware#1038]
## Configs used:
[Example.zip](https://github.com/Fedoraware/Fedoraware/files/12538005/Example.zip)

## Description:
The autobackstab option doesn't stab sometimes, even when setting the FOV to 100%.

**Comment by GC634** [comment]
The question is did Auto backstab crash for you? Like when you try to backstab someone? Cause for me it did.

**Comment by xxmyn** [comment]
> The question is did Auto backstab crash for you? Like when you try to backstab someone? Cause for me it did.

#1000 is the issue you're talking about
