### ISSUE TITLE
splash bot with original

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#1051]
**Fedoraware Version Date:**  latest
**Windows Version:**    

## Configs used:
 https://files.catbox.moe/nq73t3.fw

## Description:
 Incorrect offset for the original

https://github.com/Fedoraware/Fedoraware/assets/81353241/fd0ba734-28d3-44ce-8c69-844b16a88fc2

## Steps to reproduce:
- [ ] With the steps below I am able to consistently reproduce this issue.

1. Equip The Original
2. Enable Splash Bot
3. Make sure the enemy is on the left
4. Make sure you're behind a wall and hold the aim key

## Additional info:
 funny cheat ngl

**Comment by xxmyn** [comment]
Error seems to be in Utils::WillProjectileHit due to originals view offset not being set.
