### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by Goennigoegoe** [Fedoraware/Fedoraware#1052]
I installed the source of the cheat and im trying to compile with mode set to x86 AVX2 and im getting these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamInternal_FindOrCreateUserInterface	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamInternal_FindOrCreateGameServerInterface	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamInternal_CreateInterface	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamInternal_ContextInit	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamGameServer_GetHSteamUser	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__SteamAPI_GetHSteamUser	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__MapViewOfFileNuma2@36	Fedoraware-TF2	D:\vs2022projects\FedorawareTF2\Fedoraware-TF2\Localize.h.obj	1

**Comment by xxmyn** [comment]
redownload the source.

**Comment by xxmyn** [comment]
i believe the issue is here 
![image](https://github.com/Fedoraware/Fedoraware/assets/70382582/f8bfeff7-45c3-4e05-a1db-2ae846f55d10)

you just don't have it set right or smthn, shouldn't really depend on you setting it so ig just redownload it :D

**Comment by Goennigoegoe** [comment]
i just cloned the latest version and built it and im getting the same error as before

**Comment by canedoly** [comment]
> i just cloned the latest version and built it and im getting the same error as before

could you try just downloading the source from github instead of cloning?

**Comment by Goennigoegoe** [comment]
> > i just cloned the latest version and built it and im getting the same error as before
> 
> could you just try downloading the source from github instead of cloning?

Cloning does the exact same as downloading from github.

**Comment by Usernamemp44** [comment]
Hm..

**Comment by canedoly** [comment]
> > > i just cloned the latest version and built it and im getting the same error as before
> > 
> > 
> > could you just try downloading the source from github instead of cloning?
> 
> Cloning does the exact same as downloading from github. Even when downloading from github i get the error.

idk, you could always try. I've always downloaded the source from github and never had that issue

**Comment by Usernamemp44** [comment]
We have a discord for this???? bruh

**Comment by xxmyn** [comment]
send your general properties dropdown for the solution as well as your expanded file directory for the repo.

(should look like this)
![image](https://github.com/Fedoraware/Fedoraware/assets/70382582/394f516a-e859-4985-b88b-e6841c62e98c)

**Comment by Goennigoegoe** [comment]
![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/6ce114dd-20b1-4830-9edb-9f3db2fb23e4)

**Comment by xxmyn** [comment]
okay and the properties tab

**Comment by Goennigoegoe** [comment]
![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/f5d667a8-4c86-41d0-b934-a4712eee5d90)


![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/1ecaf2e3-fb51-43fd-8bfc-4b6981d40c29)


![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/982b548e-4ee8-4d73-b1a2-899ae2abe608)


![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/8fb63a91-33e8-4dec-b67a-ba7749ab996f)


All the changes in linker

![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/ad115d9f-6341-4dd0-a716-d355280e2949)

![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/0406105d-83ab-4423-92ef-3e1026da483e)

![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/599255b3-bc93-413f-86c5-bdda8713f13f)

![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/cbdc0462-d650-494a-8bf6-91bd680cac20)


![image](https://github.com/Fedoraware/Fedoraware/assets/79897009/d430bfbd-dfe7-412f-8343-545cd4f66cdd)

**Comment by xxmyn** [comment]
hmm, looks fine, maybe localise.h isn't being included in compilation?

**Comment by Goennigoegoe** [comment]
It is included in compilation it seems. 
The only other time I've had an error like this was when I was trying to use a library and the fix was a library specific '#define' flag.

**Comment by lnx00** [comment]
Doesn't seem like an issue on our side
