### ISSUE TITLE
Crash in CCheaterDetection::ReportDamage()

### ISSUE THREAD

**Issue by swamptwink** [Fedoraware/Fedoraware#1055]
**Fedoraware Version Date:**  [dd38d62](https://github.com/Fedoraware/Fedoraware/commit/dd38d62712b2206cc2fc656cbfb46c9f02ec1f0a)
**Windows Version:**  W10 Pro 1909  

## Configs used:
[visuals.txt](https://github.com/Fedoraware/Fedoraware/files/12658559/visuals.txt)
[functions.txt](https://github.com/Fedoraware/Fedoraware/files/12658560/functions.txt)

## Description:

Game randomly crashed while running `CCheaterDetection::ReportDamage`, tabbed out, and while the game was still in freezecam view.

[video](https://youtu.be/R_9sVarfe1U)
![image](https://github.com/Fedoraware/Fedoraware/assets/70382582/2b4e7333-d277-4102-a5eb-76bfaa0d7f1c)

The attacker index was also unusually high at 510, maybe it's a map object?

**Comment by johnathon-walnut** [comment]
its a userid

**Comment by johnathon-walnut** [comment]
I::ClientEntityList->GetClientEntity(I::EngineClient->GetPlayerForUserID(pEvent->GetInt("attacker")))

should fix this

**Comment by johnathon-walnut** [comment]
<html><body>
<h3><span class="mw-headline" id="player_hurt">player_hurt</span></h3>
<p><code class="qmsg"><b>Note:</b> When a player is hurt</code><br>
</p>


Name: | player_hurt
-- | --
Structure: | short  userid  victim   short  health  victim health   short  attacker  attacker   short  damageamount  damage amount of victim take damage   short  custom     bool  showdisguisedcrit  if our attribute specifically crits disguised enemies we need to show it on the client   bool  crit  if has crit on fire or hurt with crit   bool  minicrit  if has minicrit on fire or hurt with minicrit   bool  allseecrit     short  weaponid  weapon id of attacker   byte  bonuseffect | short | userid | victim | short | health | victim health | short | attacker | attacker | short | damageamount | damage amount of victim take damage | short | custom |   | bool | showdisguisedcrit | if our attribute specifically crits disguised enemies we need to show it on the client | bool | crit | if has crit on fire or hurt with crit | bool | minicrit | if has minicrit on fire or hurt with minicrit | bool | allseecrit |   | short | weaponid | weapon id of attacker | byte | bonuseffect
short | userid | victim
short | health | victim health
short | attacker | attacker
short | damageamount | damage amount of victim take damage
short | custom |  
bool | showdisguisedcrit | if our attribute specifically crits disguised enemies we need to show it on the client
bool | crit | if has crit on fire or hurt with crit
bool | minicrit | if has minicrit on fire or hurt with minicrit
bool | allseecrit |  
short | weaponid | weapon id of attacker
byte | bonuseffect


</body>
</html>
