### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by segiqt** [Fedoraware/Fedoraware#1058]
Crashes on injection.

When injected with Process Hacker (what i use) it injects but then has two popups in TF2,
the first saying 
Pattern not found, module Engine.dll
![1](https://github.com/Fedoraware/Fedoraware/assets/145671723/3165cfeb-6f35-4137-942f-99e04f61c354)

Then after clicking ok, or the x button it says
![2](https://github.com/Fedoraware/Fedoraware/assets/145671723/90679d5b-508b-4fb0-8503-6de9963a641d)

Minidump created, which creates a dmp crash file of what happened. Upon opening it, its just garble code and unreadable.

This happened right after it was perfectly working fine with the Fedora Loader and now both have the same issue.

**Comment by lnx00** [comment]
Try restarting your computer
