### ISSUE TITLE
Minigun & Doubletap Issues

### ISSUE THREAD

**Issue by swamptwink** [Fedoraware/Fedoraware#1070]
**Fedoraware Version Date:**  5a31de3
**Windows Version:** W10 Pro 1909

## Configs used:

[functions.txt](https://github.com/Fedoraware/Fedoraware/files/12774467/functions.txt)
[visuals.txt](https://github.com/Fedoraware/Fedoraware/files/12774468/visuals.txt)

## Description:

When manually firing the minigun doubletaps properly and shoots 4 bullets, when using aimbot to doubletap it only fires 2 bullets.

## Steps to reproduce:

1. With the config provided, switch to heavy and attempt to aimbot a target with the minigun.
2. profit

## Additional info:
https://github.com/Fedoraware/Fedoraware/assets/70382582/8c7e33b5-45b2-4ff4-954e-fd5a32dbab5b

**Comment by PiantaMK** [comment]
solution: turn off autoshoot

**Comment by canedoly** [comment]
> solution: turn off autoshoot

DontWaitForShot* i've mentioned this in a issue like a long time ago and baan told me to just disable it to fix the issue

**Comment by PiantaMK** [comment]
> > solution: turn off autoshoot
> 
> DontWaitForShot* i've mentioned this in a issue like a long time ago and baan told me to just disable it to fix the issue

i meant autoshoot
i had the same issue and turning off autoshoot fixed it

**Comment by swamptwink** [comment]
@canedoly is right, this was over confidence in my attacking cooldown stuff, just disabling wait for shot while we are shifting should fix it. (although the comment is kind of ominous `don't run if we can't shoot (should stop unbearable dt lag)`)

**Comment by swamptwink** [comment]
i retract my previous comment

**Comment by canedoly** [comment]
> i retract my previous comment

same for me, just checked and it doesn't matter anymore it's always 2 bullets

**Comment by swamptwink** [comment]
6b1f6fd

i can finally blame lnx for something where it's actually his fault, muawhahhahhaha
