### ISSUE TITLE
Chams issue

### ISSUE THREAD

**Issue by kywowastaken** [Fedoraware/Fedoraware#1075]
No matter what chams material I use they are all just flat and a stable color. Idk if it is a config issue or what. It has always been like this I am just only now wanting to report it.
[visuals.txt](https://github.com/Fedoraware/Fedoraware/files/12791889/visuals.txt)

**Comment by canedoly** [comment]
enable mat_phong,  mat_specular, mat_bumpmap (set to 1) and optional mat_hdr_level 2

**Comment by c043** [comment]
sex machine

**Comment by Muffinmaker2** [comment]
use template to make it easier to fix

**Comment by canedoly** [comment]
> use template to make it easier to fix

i already told him how to fix it lol + this isn't an actual cheat issue

**Comment by Muffinmaker2** [comment]
> > use template to make it easier to fix
> 
> i already told him how to fix it lol + this isn't an actual cheat issue

yea ok still would made it easier and more ez to read if he goes by the template cause random pasting his visuals config in here isnt making it better

**Comment by Usernamemp44** [comment]
use mastercomfig medium preset or higher. or medium settings
