### ISSUE TITLE
Bug dispenser 

### ISSUE THREAD

**Issue by nguyendangm844** [Fedoraware/Fedoraware#1078]
**Fedoraware Version Date:**  latest version
**Windows Version:**    Win 10

## Description:
This bug only occurs when moving near the dispenser 
## Config
[New folder.zip](https://github.com/Fedoraware/Fedoraware/files/12791834/New.folder.zip)
## Additional info:
[bandicam 2023-10-03 17-50-35-665.zip](https://github.com/Fedoraware/Fedoraware/files/12791744/bandicam.2023-10-03.17-50-35-665.zip)

**Comment by johnathon-walnut** [comment]
Lol I had this issue like a year ago

https://github.com/Fedoraware/Fedoraware/assets/36936588/7bf17249-d058-4e5b-9264-bac0c15a56f8

**Comment by swamptwink** [comment]
Are you using aimbot?

**Comment by johnathon-walnut** [comment]
his aim key is on LMB i guess it can be assumed so? Might be more useful if he uploaded his config

**Comment by c043** [comment]
also had this bug where i couldnt upgrade my dispenser.

**Comment by swamptwink** [comment]
where u using aimbot to upgrade it?

**Comment by c043** [comment]
i think it was aimbot, yea. auto melee aimbot
