### ISSUE TITLE
Auto Kick From Server After Around 5 - 10 Mins of Playing with VAC Ban

### ISSUE THREAD

**Issue by zalifsif38** [Fedoraware/Fedoraware#1086]
**Fedoraware Version Date: 10/7/23**  
**Windows Version: Win 10 Pro x64 22H2**

Configs used: No custom configs, just default settings. Only setting enabled was "Auto VAC Join"

Description: After joining a server (using Auto VAC Join) while having a VAC ban, you are kicked from the server after about 5 - 10 minutes. After you get kicked you see the message that you can't join the server because the server runs VAC. While you are on the server everything works no problem.

Steps to reproduce:
1. Load into TF2 w/ FW
2. Try to join casual server while having the "Auto VAC Join" option on
3. Join the server (may or may not work, from my experience its a 50/50. I know that while using some custom huds like budhud you cannot join at all which I suppose could also be called a bug. Using the default HUD it's 50/50)
4. Play
5. Get kicked by the server (not through voting) after playing for 5 - 10 mins

**Comment by SDarkra1** [comment]
This is applicable on every other cheat, and as far as I know it can't be bypassed.

**Comment by Umbrozium** [comment]
I don't think there's much you can do about it. You are VAC banned after all. This method just runs 2 commands through console to skip a VAC check. Wonky method.

**Comment by Muffinmaker2** [comment]
fedorea be doin the wonky splonky

**Comment by PiantaMK** [comment]
iirc the server checks if the account has a vac ban every 5 mins
