### ISSUE TITLE
Party Networking feature blocks party messaging entirely.

### ISSUE THREAD

**Issue by Umbrozium** [Fedoraware/Fedoraware#109]
Not sure if this is intended, but enabling Party Networking blocks all messages, including the ones you or other party members send manually.

**Comment by johnathon-walnut** [comment]
Don't quote me on this but I think there is a rate limit on the party chat. Solution is probably to disable party networking if the chat is open, wouldn't fix it on the main menu though. (See StartMessageMode and StopMessageMode)

**Comment by johnathon-walnut** [comment]
I was wrong in the comment above, this is a different issue actually as it still works through the HUD element, just not through say_party

**Comment by johnathon-walnut** [comment]
Haven't experienced this anymore
