### ISSUE TITLE
Backtrack breaking everything

### ISSUE THREAD

**Issue by ipecarvalho** [Fedoraware/Fedoraware#1097]
Configs used:
https://pastebin.com/YTfh5wZ3

## Description:
When i put backtrack in (value) it adds that to my real ping, warp/dt is broken, auto duck sometimes duck when it shouldn't, fake ping just goes to 300 and real ping goes to (Value)

Steps to reproduce:
With the steps below I am able to consistently reproduce this issue.

1. Enable Backtrack
2. Put back track in any value
3. DT, auto duck, fake ping and real ping is fucked :)

image of the issue: 
![image](https://github.com/Fedoraware/Fedoraware/assets/91567916/c71f957f-2e40-40e1-9b5e-73157630daa0)

**Comment by swamptwink** [comment]
fake latency adds to your real ping thats how it works
