### ISSUE TITLE
Fedoraware randomly crashing my game

### ISSUE THREAD

**Issue by cerulean69696969** [Fedoraware/Fedoraware#1098]
**Fedoraware Version Date: Latest**  
**Windows Version: Windows 10**    

## Description:
Fedoraware just randomly crashes after a certain amount of time for no reason. Not even a crash dump, it just closes the game.

## Steps to reproduce:
Inject Fedoraware and play a little

**Comment by Usernamemp44** [comment]
![image_2023-10-18_162556182](https://github.com/Fedoraware/Fedoraware/assets/119122268/b07de59c-2b70-452b-98b0-a10d045049f1)
"windows version = windows"

**Comment by cerulean69696969** [comment]
i meant windows 10 💀

**Comment by swamptwink** [comment]
please provide a config and video.
