### ISSUE TITLE
Fware crashing everytime I start a new map

### ISSUE THREAD

**Issue by VallesdaPlug** [Fedoraware/Fedoraware#1103]
Title, I disabled everything in the config, and visual for the menu I modded a bit. No matter what changes I do it always crashes on startup. I do have dx_level 90, it worked fine previously, now it just breaks. 
[Crash_FW_616b.dmp](https://github.com/Fedoraware/Fedoraware/files/13057372/Crash_FW_616b.dmp)

1. I have deleted every config from FedFigs, and rolled on default, now it _works...??????!?!?!?!?!_

**Comment by lnx00** [comment]
Which injector and windows version are you using?
