### ISSUE TITLE
backtrack does not work

### ISSUE THREAD

**Issue by supastatnegr** [Fedoraware/Fedoraware#1112]
**Fedoraware Version Date:21.10**  
**Windows Version:**     Windows 10 Pro
22H2
ОС	19045.3570
Windows Feature Experience Pack 1000.19052.1000.0

## Configs used:
 just enabled backtrack and backtrack visuals

## Description:
 backtrack work strange, sometimes it works and showing backtrack visuals and sometimes does not show backtrack visuals, without backtrack visuals auto-backstab works bad (
to be more precise auto-backstab just dont work)

## Steps to reproduce:
- [ ] With the steps below I am able to consistently reproduce this issue.

1. Enable backtrack in "AimBot" and backtrack visuals also if you play spy you can enable rage autobackstab
2. Play with them on spy or something else in casual, and understand that they are working bad and sometimes backtrack visuals just disappear.

## Additional info:
 pls fix

**Comment by GC634** [comment]
Auto backstab works for me tho?

**Comment by LoranFK** [comment]
enter cl_cmdrate 66 and cl_updaterate 66 in the console

**Comment by supastatnegr** [comment]
ok ill try
