### ISSUE TITLE
vphy related sig

### ISSUE THREAD

**Issue by lbydesync** [Fedoraware/Fedoraware#1126]
55 8B EC A1 ? ? ? ? 83 EC ? 8B 40 ? 56 8B F1 39 86 (used in projectile aim..)
figure rest pasters

**Comment by Muffinmaker2** [comment]
shat ap woman ☕

**Comment by johnathon-walnut** [comment]
What exactly would be the use of this? This is just C_BaseEntity::PhysicsSimulate

**Comment by swamptwink** [comment]
no sorry
