### ISSUE TITLE
Aim-bot issue

### ISSUE THREAD

**Issue by Zagibator** [Fedoraware/Fedoraware#1128]
**Fedoraware Version Date: last
**Windows Version: 10 pro

## Configs used: 
[configs.zip](https://github.com/Fedoraware/Fedoraware/files/13257231/configs.zip)

## Description:
When i use bullet weapon, aim-bot tryes to PROJECTILE enemy? I linked video, where you can see, how aim-bot aiming like projectile aimbot. https://youtu.be/F1UIMiaXpmo

## Steps to reproduce:
Just use any sniper riffle or revolver and speactate where aim-bot aiming.
1. Go to casual/community server (NOT LOCAL, there is no such error in local server)
2. Try to kill enemy with bullet weapon

## Additional info:
I spot this issue scince october, I though it will repear itself. Sorry for my bad english.

**Comment by Zagibator** [comment]
0:17 timecode in video

**Comment by canedoly** [comment]
How is it aiming as an projectile weapon? You're probably missing because you're too far and the revolver has spread

**Comment by Zagibator** [comment]
> How is it aiming as an projectile weapon? You're probably missing because you're too far and the revolver has spread

No, no. It missing even in short range. I can make another video if you want.

**Comment by PiantaMK** [comment]
reinject and make a new aimbot cfg from scratch, maybe get one of the cfgs in the discord.

**Comment by Zagibator** [comment]
> reinject and make a new aimbot cfg from scratch, maybe get one of the cfgs in the discord. this can help sometimes.

k, thx, i will try

**Comment by FedUser23** [comment]
its just conflicting settings brother
