### ISSUE TITLE
Fedoraware Injection Error

### ISSUE THREAD

**Issue by ProjectileAimbotError404** [Fedoraware/Fedoraware#1134]
## Description:
I seem to be unable to Inject Fedoraware twice if i dont restart my PC after i injection, i get an error,as show below 
![image](https://github.com/Fedoraware/Fedoraware/assets/116775504/fd4c3369-5777-47ae-9138-47c814f5219f)

1. Inject Fedoraware
2.Play some time
3.Close TF2
4.Try to Inject Fedoraware again
5. Fail
6. Get the error

**Comment by canedoly** [comment]
that's an issue with fedoraloader, not fedoraware

**Comment by lnx00** [comment]
You are using an outdated version of the loader.
