### ISSUE TITLE
Class Icon Broken

### ISSUE THREAD

**Issue by FedUser23** [Fedoraware/Fedoraware#1136]
damn

**Comment by PiantaMK** [comment]
![hl2 2023-11-09 15-34-31-68](https://github.com/Fedoraware/Fedoraware/assets/113540867/784b020d-d167-4baf-8848-12dd9b366242)

**Comment by lnx00** [comment]
You didn't provide any information or followed the template issue in the slightest...

**Comment by PiantaMK** [comment]
> u might have..broken the class icon. Also pianta why are u polishe
![20231110144747_1](https://github.com/Fedoraware/Fedoraware/assets/113540867/978f9d8a-7bfd-4bb4-91a8-01fcade18301)
we have something in common skibitioiletfan2007...
