### ISSUE TITLE
ESP Visuals draw infront of onscreen visuals.

### ISSUE THREAD

**Issue by swamptwink** [Fedoraware/Fedoraware#1143]
**Fedoraware Version Date:**  804d4e23f62dcd7c767cb4817bdb77b05707eec2
**Windows Version:**  W10 21H2 19044.1806   

## Configs used:

Works on any config.

## Description:

ESP visuals draw over the top of the HUD visuals (not your game HUD, indicators and onscreen text). 

## Steps to reproduce:
1. Have a visual config with ESP and on screen indicators (DT Bar etc).
2. When they overlap, the ESP visuals will appear on top.

## Additional info:

N/A

**Comment by canedoly** [comment]
Are the visuals rendering after esp?
