### ISSUE TITLE
Help me, im using fedora nad my voice dont work, the commands and text chat dont work too. I literally still a f2p player

### ISSUE THREAD

**Issue by AverageFedoraUser** [Fedoraware/Fedoraware#1146]
**Fedoraware Version Date:**  idk Exloader's version that's all
**Windows Version:**  Windows 10

## Configs used:
My own config, semi-rage or legit idk

## Description:
Im using exloader version of fedoraware, idk what to say

## Additional info:
Just help me plis

**Comment by Muffinmaker2** [comment]
Fym how we supposed to help you f2p use chat??? buy some shit broke aah 💀

**Comment by AverageFedoraUser** [comment]
idk, fedora gives you a chat but it dont work

**Comment by Muffinmaker2** [comment]
when did fedoraware give you chat accsess as a f2p?

**Comment by AverageFedoraUser** [comment]
you can just look at commands and you need to be a happy of this fr

**Comment by swamptwink** [comment]
`As of [June 16, 2020 Patch](https://wiki.teamfortress.com/wiki/June_16,_2020_Patch), certain newly-created TF2 accounts have been restricted in their ability to send messages on official servers, with exception of party chat. As of [July 3, 2020 Patch](https://wiki.teamfortress.com/wiki/July_3,_2020_Patch), said accounts are now also restricted in voice chat, including sending [voice commands](https://wiki.teamfortress.com/wiki/Voice_commands). Accounts may also be restricted for being [Limited User Accounts](https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A) on Steam, which means the player has to spend at least $5.00 USD to gain access to the text and voice chats.`

[source](https://wiki.teamfortress.com/wiki/Account_types)

Fedoraware removes the chat message that appears for f2p players who are trying to chat, but it does not allow you to chat.

**Comment by AverageFedoraUser** [comment]
uurgh

**Comment by AverageFedoraUser** [comment]
ok thx

**Comment by Muffinmaker2** [comment]
> Exloader's version that's all

brooooo exloader has fedoraware in it 😭 whyyy

**Comment by N1kolasFlaV** [comment]
> idk, fedora gives you a chat but it dont work

cos it's client sided

**Comment by BindUser** [comment]
Youre retarded

**Comment by PiantaMK** [comment]
> "As of [June 16, 2020 Patch](https://wiki.teamfortress.com/wiki/June_16,_2020_Patch), certain newly-created TF2 accounts have been restricted in their ability to send messages on official servers, with exception of party chat. As of [July 3, 2020 Patch](https://wiki.teamfortress.com/wiki/July_3,_2020_Patch), said accounts are now also restricted in voice chat, including sending [voice commands](https://wiki.teamfortress.com/wiki/Voice_commands). Accounts may also be restricted for being [Limited User Accounts](https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A) on Steam, which means the player has to spend at least $5.00 USD to gain access to the text and voice chats."
> 
> [source](https://wiki.teamfortress.com/wiki/Account_types)
> 
> Fedoraware removes the chat message that appears for f2p players who are trying to chat, but it does not allow you to chat.

in some f2p accounts you can use voice chat with fed injected
