### ISSUE TITLE
all aa settings on all the time

### ISSUE THREAD

**Issue by FedUser23** [Fedoraware/Fedoraware#1148]
Jitter Legs, Hide Pitch on Shot

**Comment by swamptwink** [comment]
The only "anti aim setting" that relies on anti aim being turned on is Rehide Angles or whatever its called.

**Comment by FedUser23** [comment]
the problem is that jitter legs and hide pitch on shot are permanently on and can't be disabled

**Comment by swamptwink** [comment]
[ur retarded](https://www.youtube.com/watch?v=RfI04hWaOp4)

**Comment by Usernamemp44** [comment]
https://cdn.discordapp.com/attachments/1047772804470280242/1175314414870724608/In_The_Virtual_End_Linkin_Park_HL2_music_video_1.mp4?ex=656ac7d8&is=655852d8&hm=d6b7c92866667ac5b981f5efa0ac33c9045f0585d829d67c0d9ca74a41220727&

**Comment by Usernamemp44** [comment]
wrong paste

**Comment by FedUser23** [comment]
bro don't blame me for random code breaking then replying after its fixed

**Comment by swamptwink** [comment]
The issue I fixed was to do with leg jitter not working unless anti aim was turned on, the issue you described could not be reproduced, you replied after the issue was closed, didnt follow the template, and from what i can understand the issue you were talking about never existed.

**Comment by FedUser23** [comment]
i use the loader i can't tell what build im even using

**Comment by PiantaMK** [comment]
> i use the loader i can't tell what build im even using

![image](https://github.com/Fedoraware/Fedoraware/assets/113540867/5b0c14b1-cb4e-4cbc-9fca-d40287a4c217)
