### ISSUE TITLE
Resolver resolved everyone

### ISSUE THREAD

**Issue by HutchyBen** [Fedoraware/Fedoraware#1156]
As far as my quick glance at the resolver code looks there is no checks at all so it resolves all players when really only enemies or aim target is needed.

Will fix when I'm back home Friday if it this is an actual issue and no one else fixes.

**Comment by PiantaMK** [comment]
the bigger issue is that when the resolver is enables you have to enable resolver manually for every player because none is default and not auto

**Comment by HutchyBen** [comment]
Now this is wisdom

**Comment by swamptwink** [comment]
you can resolve players on your own team but aimbot doesn't yet target them because i hate listening to advice. It will only resolve people that it is manually activated on and the bruteforce resolver doesn't do anything unless the aimbot targets that player.

**Comment by HutchyBen** [comment]
resolver is 110% doing stuff even with nothing selected. adding a check to ignore teammates stop all jittering

**Comment by swamptwink** [comment]
> resolver is 110% doing stuff even with nothing selected. adding a check to ignore teammates stop all jittering

[FXFireBullet](https://github.com/Fedoraware/Fedoraware/blob/40940a20ef8e79eb46dee41e76bc0871345d4669/Fedoraware/Fedoraware-TF2/src/Features/Resolver/Resolver.cpp#L237) will run no matter what, but it shouldn't really make them "jittery" at all.

**Comment by HutchyBen** [comment]
I found disabling all code apart from the get eye angles and setting the angles causes jittering. Is it an issue with setting current feet yaw I don't see why it would need to be set?

**Comment by swamptwink** [comment]
I'm gonna close this, the resolver will always set a persons angles to their firing angles when they shoot.
