### ISSUE TITLE
Menu keybinds not working

### ISSUE THREAD

**Issue by titaniummachine1** [Fedoraware/Fedoraware#1157]
keybinds dont work in menu canot asing aimbot to m1 or somethign its set to always or nonr always cannot change

**Comment by HutchyBen** [comment]
Okay can you rewrite this but more understandable.
Thank you.

**Comment by HutchyBen** [comment]
Is this translation correct?

The mouse 1 does not work as a keybind.
There is no option to set aimbot to always on or always off?
Do you mean toggle?

**Comment by Gergish** [comment]
just restart your PC and it work normal again

**Comment by HutchyBen** [comment]
also just click outside the input box. i stare at code and clicking the input cancels the keybind intentionally

**Comment by swamptwink** [comment]
clicking outside of the input box will bind it to left click :trollface:
