### ISSUE TITLE
Issue with fedoraloader

### ISSUE THREAD

**Issue by ProjectileAimbotError404** [Fedoraware/Fedoraware#1158]
## Description:
Today,while trying to inject fedoraware into TF2 using Fedoraloader i ran into an issue. It would stop mid-way and would show an error. The error says:
"Failed to download the latest build
The SSL connection could not be established, see inner exception"

![image](https://github.com/Fedoraware/Fedoraware/assets/116775504/ea27952f-abaf-4e0d-aa27-4f405ea07c19)

Any way to get around this ?

## Steps to reproduce:
Run fedoraloader
Maybe run into the issue
Get frustrated 
Voila!

**Comment by HutchyBen** [comment]
Okay so it just downloads this file... do you have any issue downloading this file?
https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip

also fedoraloader has a repositorty >:( issues on there

**Comment by ProjectileAimbotError404** [comment]
i cant seem to open the link

**Comment by ProjectileAimbotError404** [comment]
and what does the file do anyway

**Comment by HutchyBen** [comment]
That has the latest build of fedoraware. Maybe you have an issue with your network blocking it or something idk

**Comment by ProjectileAimbotError404** [comment]
what do you mean?

**Comment by HutchyBen** [comment]
i have no clue! something could be causing issues on your end

**Comment by lnx00** [comment]
You are using an outdated version of Fedoraloader. You can find the latest version here:
https://github.com/Fedoraware/Fedoraloader/releases/latest
