### ISSUE TITLE
aimbot not working.

### ISSUE THREAD

**Issue by imeanimnotwrong** [Fedoraware/Fedoraware#1172]
before christmas update it was fine but after christmas update it cant even hit an heavy that is standing still. What is going on??????

**Comment by canedoly** [comment]
"after christmas update"
![image](https://github.com/Fedoraware/Fedoraware/assets/81353241/cebbc3f3-1cf7-46f0-af82-5d8331233d33) (latest)
there wasn't even an update yet??

**Comment by swamptwink** [comment]
nope
