### ISSUE TITLE
Interpolation Removal Issue

### ISSUE THREAD

**Issue by icemotione** [Fedoraware/Fedoraware#1177]
## Configs used:
https://www.mediafire.com/file/fbn4z053umr2c7r/legit.fw/file
https://www.mediafire.com/file/kab1akm8de71h64/devosal.fw/file

## Description:
Teammate animations still nolerp'd (choppy animations, caused by removed interpolation frames)

## Steps to reproduce:
- Exclude "Interpolation" from the Visual -> Removal section
- Join any server
- Teammate will still have interpolations disabled.

## Additional info:
Video of interpolation-less animations on teammates :
https://imgur.com/a/N9RLeTY
The Interpolation Removal on Visual only affects enemies.

**Comment by canedoly** [comment]
user issue ngl

**Comment by icemotione** [comment]
> user issue ngl

What do you mean? I tried going to a match without injecting fware, and the animations are normal. I went and inject fware, and the problem gets replicated, suddenly it's like the game re-renders animations of player models.
I'm not sure what causes this problem, I attempted to fix it by always returning Hook.Original<FN>() to functions that hooks interpolation, but the problem still persists..

**Comment by icemotione** [comment]
I solved this issue by removing most detour hooks, only adding the hooks related to features that I use.
