### ISSUE TITLE
game immediately freezes on unfocusing tf2 with menu open

### ISSUE THREAD

**Issue by geoduude** [Fedoraware/Fedoraware#1183]
how does something like this even happen
listen to audio

https://github.com/Fedoraware/Fedoraware/assets/70681785/ede5c73a-9b9c-4135-9fb6-ce58add4742d

**Comment by nguyendangm844** [comment]
it's not a bug, it's a feature

**Comment by geoduude** [comment]
> it's not a bug, it's a feature

makes sense

**Comment by skibiditoiletfan2007** [comment]
your pc is too good for fw go downgrade

**Comment by wrtrteyteey23ee** [comment]
seownedde is better anyway

**Comment by swamptwink** [comment]
cant recreate sorry frend
