### ISSUE TITLE
Strange sticky bug

### ISSUE THREAD

**Issue by nguyendangm844** [Fedoraware/Fedoraware#1184]
**Fedoraware Version Date:**  Latest
**Windows Version:**    win 10
## Configs used:

[New folder.zip](https://github.com/Fedoraware/Fedoraware/files/13785919/New.folder.zip)
## Description:
when i turn on aimbot my strange sticky doesn't work
[bandicam 2023-12-28 18-04-03-186.zip](https://github.com/Fedoraware/Fedoraware/files/13785930/bandicam.2023-12-28.18-04-03-186.zip)

**Comment by swamptwink** [comment]
hmm, couldnt replicate with my strange gooey so definitely just a problem with strange sticky...
