### ISSUE TITLE
fix aimbot offsets

### ISSUE THREAD

**Issue by fedorawareeenjoyer** [Fedoraware/Fedoraware#1186]
when the wall aimbot hitting wall and doing 96 dt dmg

**Comment by swamptwink** [comment]
Follow issue template.

**Comment by hhh485** [comment]
lazy ass nigga l0l

**Comment by hhh485** [comment]
i'll fix this myself

**Comment by fedorawareeenjoyer** [comment]
Okay i fixed it ez

**Comment by fedorawareeenjoyer** [comment]
hhh485 lets work on the cheat lol
