### ISSUE TITLE
Client.dll/Engine.dll Missing half the time

### ISSUE THREAD

**Issue by FedUser23** [Fedoraware/Fedoraware#1189]
engine.dll missing or client.dll missing no matter what i do.
![image](https://github.com/Fedoraware/Fedoraware/assets/145074428/ad05b7d4-4efa-426a-8989-fab72328d916)

**Comment by FedUser23** [comment]
been an issue for while and it happens on and off

**Comment by lnx00** [comment]
#1059

**Comment by FedUser23** [comment]
Didn't work still missing it
