### ISSUE TITLE
Fedora not working anymore?

### ISSUE THREAD

**Issue by pulamea12** [Fedoraware/Fedoraware#1192]
**Fedoraware Version Date: last version / 15 October or something 
**Windows Version:**    

## Configs used:
-

## Description:
I am not able to insert the cheat anymore. Everything worked fine until yesterday. Used it for a while but now I am getting an error, either by injecting with Fedoraloader directly or with another injector manually, when the TF2 is loaded, I get the error in the screenshot that I attached:
![Screenshot 2024-01-18 143104](https://github.com/Fedoraware/Fedoraware/assets/157023711/87d9fabe-9392-4e76-b8d2-298629d304f8)

Please tell me if this is a general issue or just me. Windows 11 Home, x64bit

**Comment by Fungus642** [comment]
This happens to me too on windows 10

**Comment by swamptwink** [comment]
https://github.com/Fedoraware/Fedoraware/issues/1059
