### ISSUE TITLE
Windows Defender going haywire like it's D-day

### ISSUE THREAD

**Issue by tescoradioenjoyer** [Fedoraware/Fedoraware#1204]
Build is Jan 4 2024 build
Windows version is 22H2 x64
Windows Defender went insane and kept repeating on Fedoraware being Wacapac something idk
what is causing this

**Comment by lnx00** [comment]
Exclude Fedoraware from Windows Defender.

**Comment by tescoradioenjoyer** [comment]
> Exclude Fedoraware from Windows Defender.

ok thanks
