### ISSUE TITLE
Autostab and ignore razorback is broken

### ISSUE THREAD

**Issue by ShiroSeby** [Fedoraware/Fedoraware#197]
autostab broken reproduction tutorial:
1. enable triggerbot autostab in a match
2. queue for another match then join
3. autostab will no longer work

ignore razorback doesnt work entirely (doesn't ignore razorback)

**Comment by HARrhhv1** [comment]
nigger

**Comment by LEFtt1** [comment]
Well, I'll agree with everything about that.

**Comment by sneekyspy** [comment]
fedoraware you are better trickstab react why did you do that?

**Comment by sneekyspy** [comment]
not gonna lie fedoraware best free cheat

**Comment by lnx00** [comment]
Seems to be fixed
