### ISSUE TITLE
Out of FOV arrows - change Distance From Center based on distance from enemy

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#324]
Add a little toggle to make `Distance from center` dynamically change depending on distance from enemy.

Depending on how distance from center is written, this may end up requiring a new method of distancing per-arrow..

Shitty example:
![image](https://user-images.githubusercontent.com/17802843/170772968-050a7e80-8e29-4e46-9a2b-4ec8c51a927e.png)

![image](https://user-images.githubusercontent.com/17802843/170772779-a23200d4-2342-4a68-9091-5ad1a5e5075f.png)

**Comment by femboy-boop** [comment]
There shouldn't be a reason for that unless you like play on 20 fov and closet your ass off

**Comment by SylveonBottle** [comment]
> There shouldn't be a reason for that unless you like play on 20 fov and closet your ass off

Well if anybody else likes the idea and wants to give it a shot, they're more than welcome to try adding it. 
No need to add your input if all you're going to do is tell everybody else reasons why they shouldn't waste their time on it. If someone likes the look of it, they'll work on it.
