### ISSUE TITLE
Warp autopeek

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#373]
Warp with autopeek in order to minimize possibility for enemy to bodyshot us.
\>Autopeek towards corner / enemy
\>Warp when we are `X hu` away from destination (new!!)
\>Snipe enemy
\>Run back

`X hu` can be defined as the maximum distance we can gain with a 24-tick warp. I believe this is ~28 hu when scoped as a sniper, and 130hu as a scout. 
Basically we're just warping when we're Xhu away from our autopeek destination.
This won't help against backtracking enemies if we miss, but hopefully we won't miss.

**Comment by SylveonBottle** [comment]
Warp distances in hammer unites (using `getpos` and `setpos`)
Scout: 130hu (117hu <-> 169hu with babyface blaster)
Soldier: 177hu
Pyro: 97hu (112hu with powerjack)
Demoman: 90hu
Heavy: 74hu (~43hu when revved with default minigun, 6hu with brass beast, 197hu with GORU)
Engineer: 95hu
Medic: 103hu (125hu with max overdose)
Sniper: 97hu (~24-29hu when scoped, 53 with huntsman)
Spy: 104hu

I understand some of this stuff is useless for the issue (melee, pyro, etc), but maybe it'll be useful for future references.

**Comment by tf2cheater2013** [comment]
the zoom / rev charging issue will be fixed shortly.

**Comment by johnathon-walnut** [comment]
You can already do this i think
