### ISSUE TITLE
Projectile aimbot not pre-firing?

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#390]
I'm seeing instances where projectile aimbot could've [shot at an enemy] while the enemy was behind a wall, predicting that they would come out from behind it when the rocket hit.

However, instead of doing that, the projectile aimbot doesn't work until the enemy himself is visible.

Am I an idiot and misremembering things, or did this break in a recent update?

**Comment by SylveonBottle** [comment]
Also I could've sworn demoman grenade launcher would've shot at enemys over walls. But now it's not because the enemy is "behind a wall".

**Comment by johnathon-walnut** [comment]
baans projectile aimbot is kinda gonglepoop idk how he made it so gonglepoop mine is better but because it can like scan for multiple hitboxes his is better but mine is better because its not bad unlike baans which is bad i should add mine back but i frankly can not be bothered to do anything worthwhile in this cheat

**Comment by nadiR1337** [comment]
Someone can release this feature for fedora?

**Comment by xxmyn** [comment]
I make the matrix manually so we don't have to offset everything, I don't remember getting the prefire working.

**Comment by xxmyn** [comment]
actually just testing at host_timescale 0.1 it does seem to prefire.

**Comment by SylveonBottle** [comment]
> actually just testing at host_timescale 0.1 it does seem to prefire.

Could you test this with demoman real quickly? I think that's where I was mostly seeing the issue.

**Comment by xxmyn** [comment]
Demoman had some really scuffed checks, maybe try now?

**Comment by johnathon-walnut** [comment]
Seems fine to me
