### ISSUE TITLE
Crashing with killstreak option.

### ISSUE THREAD

**Issue by xxmyn** [Fedoraware/Fedoraware#398]
On weapons that already have a killstreaker I crash, as long as the option that enables the fake weapon killstreak is active.

![image](https://user-images.githubusercontent.com/70382582/174421966-c4720591-d02d-4fe4-9ca4-85039ff2baf2.png)

**Comment by pepsimaxcherry** [comment]
ok

**Comment by relaxtakenotes** [comment]
this is funny

**Comment by johnathon-walnut** [comment]
this is NOT funny >:(

**Comment by pepsimaxcherry** [comment]
сука ублюдок

**Comment by relaxtakenotes** [comment]
hey please no swearing in russian here

**Comment by johnathon-walnut** [comment]
FIXED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xxmyn** [comment]
finally now add backtrack to the demoman pills and make them fly throug the air and water and snow to hit ther targert pkease
