### ISSUE TITLE
Strafe prediction kinda ready to add

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#402]
Simple strafe prediction from [sparkly rewrite](https://github.com/csxDevr/R8HackTF2/blob/TF2/R8/Misc.cpp#L31) 
It uses cache to average a direction, and this code should be changed, to atleast not work while the target is on ground, because if you spam a, d it will think you are going to make full 1-5 circles. It works ok mid-air but misses often because of projectile prediction itself being bad.

**Comment by relaxtakenotes** [comment]
what's the point of it if it's bad

**Comment by johnathon-walnut** [comment]
you are such a negative nancy

**Comment by canedoly** [comment]
It got added so i'm gonna close

**Comment by johnathon-walnut** [comment]
ITS BAD!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by canedoly** [comment]
idc atleast its there
