### ISSUE TITLE
Funny Noisemaker Spam Not Working

### ISSUE THREAD

**Issue by ASDFJKD** [Fedoraware/Fedoraware#42]
**Latest Version of Fedoraware:**  

## Config used:
https://anonfiles.com/13Z178K6xf/MelonHead2000_fed

## Description:  
Noisemaker Spam Not Working

## Steps to reproduce:  
Just turn on the noisemaker spam and it won't spam the noisemaker

 Misc
1. Enable Noisemaker Spam

## Additional context 
it is most likely working just not set in the button of the noisemaker spam

**Comment by johnathon-walnut** [comment]
No it just doesn't work

**Comment by johnathon-walnut** [comment]
There is something very weird about the servercmdkeyvalues thing

**Comment by ASDFJKD** [comment]
it's because before they added the new menu it was working just fine that's why i thought it was just some miss placing of something ( the noisemaker thing no being in the button to activate )
