### ISSUE TITLE
NPC and objectives

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#443]
Add NPCs (tanks, merasmus and etc) to ignore settings of aimbot.
Chams, ESP, Glow for NPCs, objectives.
Bug: Aren't drawn ESP, Chams, Glow for medieval medkits.

**Comment by xxmyn** [comment]
do you know what the model name of those medieval medkits is?

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/179488254-020db25e-2036-4182-8c6f-7d17b447c316.png)

these are all the models I could find, all of which we have hashed...

**Comment by johnathon-walnut** [comment]
Medieval meat

**Comment by johnathon-walnut** [comment]
isnt this done now?
