### ISSUE TITLE
autovac gay

### ISSUE THREAD

**Issue by MCPEnguXD** [Fedoraware/Fedoraware#444]
autovac doesnt react to demo stickies or sentry's

baan 🖕

**Comment by MCPEnguXD** [comment]
also doesnt seem to react to the loose canon

**Comment by xxmyn** [comment]
why did you mention me in this.

**Comment by hyperventilation** [comment]
mcpengu (minecraft pocket edition ngu) do you mind buying rijin sub and not appearing on issues ever again

**Comment by johnathon-walnut** [comment]
Rude

**Comment by johnathon-walnut** [comment]
die irl
