### ISSUE TITLE
DME Chams and Chams make the ragdoll effect material not work

### ISSUE THREAD

**Issue by Muffinmaker2** [Fedoraware/Fedoraware#451]
**Fedoraware Version Date:*27.6.2022*  

## Config used:
Any Config

## Description:  
When Chams and DME Chams are active at the same time the ragdoll effect material(the one with ice and gold) wont work

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable Chams
2. Enable DME Chams
3. Enable Ragdoll effects and set material to gold
4. Kill someone and yea see for your self

**Comment by johnathon-walnut** [comment]
Is this even a bug? I think it's kinda obvious that these two things wouldn't play nice together. Would you rather the ragdoll take the effect or the cham??

**Comment by Muffinmaker2** [comment]
ah nah when this was intended then nvm just thought that would be a bug in anyway

**Comment by johnathon-walnut** [comment]
I don't think it's intended but I'm confused as to what the solution to this bug would be, enforce ragdoll material and ignore the gold/ice or vice versa?

**Comment by Muffinmaker2** [comment]
my cham setts for ragdolls go like this
![image](https://user-images.githubusercontent.com/107619523/175965578-d73a00ca-1826-4e97-9e01-8d76adf6e6b5.png)
so normaly it shouldnt put a cham on the ragdoll in the first place right?

**Comment by Muffinmaker2** [comment]
what do you mean by that?

**Comment by Muffinmaker2** [comment]
in the first u can see a ragdoll with the effect gold on it and dme chams disabled and overall all settings for ragdolls disabled
![ShareX_zEoTB7CjmV](https://user-images.githubusercontent.com/107619523/175968002-9ac531f9-59d1-45a5-b62d-220583076415.png)
now in the next pic u can see how i enabled the dme chams
![hl2_lTichqpa1p](https://user-images.githubusercontent.com/107619523/175968151-34d3261d-705f-4c64-af9b-5e5ca7a6ba07.png)
so now out of my logic having nothing on in the ragdoll chams tab should apply anything to the ragdoll yea?
or am i getting something wrong

**Comment by johnathon-walnut** [comment]
Set the "options" to "active"

**Comment by Muffinmaker2** [comment]
hmm
![hl2_rkoR5fZN0d](https://user-images.githubusercontent.com/107619523/175969296-401f8c62-1a5e-4e70-be9a-e5d5e92c9780.png)
didnt rly do anything
![hl2_8pg1bbsFSF](https://user-images.githubusercontent.com/107619523/175969355-90307f36-f347-497e-a8c5-b7fa9fc2de83.png)

**Comment by xxmyn** [comment]
"later"

**Comment by johnathon-walnut** [comment]
Hehehe
