### ISSUE TITLE
Feature Targetlock

### ISSUE THREAD

**Issue by ghost** [Fedoraware/Fedoraware#463]
It happens that aimbot aims at another without completely killing the enemy.

**Comment by xxmyn** [comment]
Should the cheat decide to stop prioritizing that player once they've left our aimbot FoV, after a certain amount of time, or ONLY after the player has died?

**Comment by johnathon-walnut** [comment]
you could do all 3 options

**Comment by xxmyn** [comment]
accidentally targets someone at the other end of the map and then has to run all the way over to them just so aimbot will work again :DDD

**Comment by johnathon-walnut** [comment]
I edited your comment teehee
