### ISSUE TITLE
You can open menu while game isn't open

### ISSUE THREAD

**Issue by HutchyBean** [Fedoraware/Fedoraware#467]
If in the main menu it will just not let you tab in till you close it. while in a game it crashes with an imgui error. i am too lazy to build a debug build but is very reproduceable !!!!

**Comment by johnathon-walnut** [comment]
This happens when you minimize everything/show desktop, which causes imgui to freeze for some reason

**Comment by johnathon-walnut** [comment]
Although I'm not getting an imgui error
