### ISSUE TITLE
buildings completely ignore out "Health" glow colour

### ISSUE THREAD

**Issue by Capybaron** [Fedoraware/Fedoraware#469]
![image](https://user-images.githubusercontent.com/92531943/176765097-0f2b5986-7f2c-44fd-b9a8-a60d70c07a9e.png)

**Comment by PeterPumpkinEater69real** [comment]
the image got cropped for some reason but u can see it at the teleporter

**Comment by johnathon-walnut** [comment]
lol

**Comment by PeterPumpkinEater69real** [comment]
> lol

fix it. VERY gamebreaking

**Comment by xxmyn** [comment]
@johnathon-walnut GetHealthColor returns the wrong value it seems :D

**Comment by johnathon-walnut** [comment]
Do buildings have different heath?

**Comment by xxmyn** [comment]
Actually, it changes between when it's set and when it's pushed into m_vecGlowEntities, from {180,122,55,80} (not a proper return value for the function) to {150, 0, 0, 0}

**Comment by johnathon-walnut** [comment]
What the fuck

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/177020038-bda24fe4-5250-4495-a9ae-dbf4e45bec5d.png)
there's not even anything between them,,,,,

**Comment by johnathon-walnut** [comment]
Cursed

**Comment by johnathon-walnut** [comment]
![image](https://user-images.githubusercontent.com/36936588/179356462-13fb5ec9-9832-4c80-a87d-2213a86d2a22.png)

**Comment by johnathon-walnut** [comment]
GetHealth broken for buildings?

**Comment by xxmyn** [comment]
I don't see why it wouldn't work, they are entities after all.

**Comment by johnathon-walnut** [comment]
well changing it to use the baseobjects netvar worked lol

**Comment by xxmyn** [comment]
nvm, `DT_BaseObject, m_iHealth` &  `DT_BaseObject, m_iMaxHealth`

**Comment by johnathon-walnut** [comment]
Although, glow doesnt seem to draw on specifically teleporter entrances?

**Comment by johnathon-walnut** [comment]
Or at least, it doesn't consistently

**Comment by xxmyn** [comment]
lnx's teleporter camera broke it 100% and he is now responsible for it entirely :D

**Comment by johnathon-walnut** [comment]
really?

**Comment by xxmyn** [comment]
no but it's easier to blame him.

**Comment by johnathon-walnut** [comment]
based

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/179356786-d62d4205-0eef-4517-bbe0-97c7f479650a.png)
glow works on them normally 🤷

**Comment by johnathon-walnut** [comment]
Yeah it was just weird, it wouldn't start glowing till i placed a different building, but haven't been able to get it to happen again

**Comment by Capybaron** [comment]
cheers

**Comment by Capybaron** [comment]
cheers

**Comment by lnx00** [comment]
> lnx's teleporter camera broke it 100% and he is now responsible for it entirely :D

i hate you and i hate this cheat :D
