### ISSUE TITLE
crash problem with the follow bot

### ISSUE THREAD

**Issue by AlexFlipH1** [Fedoraware/Fedoraware#489]
tf2 crashes after enable followbot and go to near person and type record fix;stop in the console

**Comment by Capybaron** [comment]
Solution: don't type in record fix;stop

**Comment by imgladnotu** [comment]
> Solution: don't type in record fix;stop

NOTABUG WONTFIX


relevant gitlab issue: https://gitlab.gnome.org/GNOME/nautilus/-/issues/244

**Comment by johnathon-walnut** [comment]
this crashes because of pLocal->GetAbsOrigin()

**Comment by xxmyn** [comment]
im not exactly sure how you would fix this without checking that every value returns something before using it.

theres also no need to record and then stop recording when you are cheating, cl_fullupdate can be used, is faster, and idk if it will cause the same crash

**Comment by AlexFlipH1** [comment]
only im thinking is when you are on menu the white things by followbot should be gone and when exiting the menu it should be back

**Comment by AlexFlipH1** [comment]
or i dont really fucking know since i dont know coding shit

**Comment by johnathon-walnut** [comment]
Don't know how to fix this lol, solution is: you know it crashes you, don't do it anymore
