### ISSUE TITLE
DT impossible without "Wait for DT" enabled

### ISSUE THREAD

**Issue by johnathon-walnut** [Fedoraware/Fedoraware#490]
When "Wait for DT" is disabled, the indicator reports DT being impossible 
![image](https://user-images.githubusercontent.com/36936588/177631819-565b3cfc-6227-4747-ac43-6d1f200c76f8.png)

**Comment by johnathon-walnut** [comment]
(I'm scared to touch any of the DT code @xxmyn)

**Comment by xxmyn** [comment]
wait for dt waits 33 ticks after charging, dt impossible shows when you are waiting, or, when you cant attack (taunting etc) its so you dont left click while taunting or pulling out your weapon etc

**Comment by johnathon-walnut** [comment]
No I mean it happens when Wait for DT is *off*, I sat there for like 2 minutes straight and it was impossible the entire time

**Comment by xxmyn** [comment]
maybe i fucked the timer accidentally
