### ISSUE TITLE
Backtracking for trigger bot?

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#492]
I can't backstab the backtracking cham when i was on middle of the match

**Comment by xxmyn** [comment]
not implemented

**Comment by GabrielNicolas10** [comment]
s

**Comment by Capybaron** [comment]
> so far I can't understand why you guys don't do auto backstab works with backtrack and aimbot too

cuz u suck

**Comment by johnathon-walnut** [comment]
What is there to "understand"? We just haven't done that.

**Comment by GabrielNicolas10** [comment]
no need to offend me either
