### ISSUE TITLE
Doublejumping while bhopping

### ISSUE THREAD

**Issue by Gught** [Fedoraware/Fedoraware#493]
**Fedoraware Version Date:** 6.07.2022  

## Config used:

https://files.catbox.moe/t7xckc.fw

## Description:  

I've noticed that bhop can often make you doublejump as scout
and its very annoying

## Steps to reproduce:  
- [X] I am able to consistently reproduce this error

1. Enable AutoJump and directional AutoStrafe
2. Try to bhop with autostrafe
3. Notice that you cant doublejump midair sometimes because autojump makes you doublejump on the ground

## Additional context 

This happens very often while you strafe sideway
- [X] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
Well I can't say I ever experience this unless I'm lagging hard

**Comment by Gught** [comment]
it happens even if my fps is about 89

**Comment by johnathon-walnut** [comment]
And it happens "anywhere"?

**Comment by Gught** [comment]
yes

**Comment by johnathon-walnut** [comment]
Do you have any other cheats you could try

**Comment by Gught** [comment]
i haven't experienced this with other cheats even when i lagged, only with fedoraware

**Comment by johnathon-walnut** [comment]
I'm trying to rule out the possibility that your keyboard is wacky

**Comment by johnathon-walnut** [comment]
Since I genuinely haven't experienced this other than when I'm lagging really really badly

**Comment by johnathon-walnut** [comment]
Do you have a strange config/bind to jump in base tf2?

**Comment by Gught** [comment]
Hmm idk but even when i had 15 fps with cathook or lmaobox i havent seen this problem
and i dont have jump binds other than default

**Comment by Gught** [comment]
i dont have auto fan jump enabled and i cant record because ill have bad fps then

**Comment by xxmyn** [comment]
89 fps is already bad.

i cant figure out what is causing your issue, there is nothing i know about that would cause anything even close to your issue, and clearly, neither can mfed.

show the issue happening, or figure it out yourself.

**Comment by Gught** [comment]
ok ill try to find what causes it

**Comment by johnathon-walnut** [comment]
> 89 fps is already bad.
> 
> i cant figure out what is causing your issue, there is nothing i know about that would cause anything even close to your issue, and clearly, neither can mfed.
> 
> show the issue happening, or figure it out yourself.

I'm confused about this but 89 FPS is more than enough to not mess with bhop still

**Comment by johnathon-walnut** [comment]
Closing cos still havent experienced this
