### ISSUE TITLE
switch back to the old hp bar or make it 2 optimal

### ISSUE THREAD

**Issue by Podssa** [Fedoraware/Fedoraware#496]
old hp bar was better 

"srry bad english"

**Comment by xxmyn** [comment]
what was the old hp bar?

**Comment by Podssa** [comment]
it looked the same as nitro´s current hp bar

**Comment by Podssa** [comment]
or spooks cheat

**Comment by johnathon-walnut** [comment]
Do you just mean when it wasn't a gradient?

**Comment by Podssa** [comment]
yes

**Comment by johnpablo1** [comment]
just make it so the bottom gradient and top gradient just the same color

**Comment by xxmyn** [comment]
how about you use ur huge brain and set both of the gradients colours to the same colour instead of crying about it here like a bitch
