### ISSUE TITLE
Fedoraware Crashing

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#500]
when I try to inject the hack into my game it closes by itself, it started yesterday and it's still with this and I can't use the hack, I used the injector called Xenos 2.3.2

**Comment by canedoly** [comment]
the game got an update recently, that's why

**Comment by lGabryl** [comment]
> the game got an update recently, that's why

I understand man, what remains is to wait for the next update of the hack?

**Comment by canedoly** [comment]
It depends, i didn't play this game recently and idk if the recent updates made it work again, so if your not already using the latest build then you should download it

**Comment by Capybaron** [comment]
Already updated
