### ISSUE TITLE
tf2 keeps crashing after i load itemtest then enter casual

### ISSUE THREAD

**Issue by therealpanman** [Fedoraware/Fedoraware#502]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by AlexFlipH1** [comment]
fedorawave broke by a tf2 update wait for a dev to update the thing and it should be fixed

**Comment by AlexFlipH1** [comment]
thats i know
