### ISSUE TITLE
far melee range bug

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#503]
**Fedoraware Version Date:**  
latest

## Config used:
works with any config

## Description:  
so i was playing on new version on fedoraware and i went demoman to test loose cannon and i used charge to pan a npc and then suddenly the melee aimbot range went to infinite but when i restart the game it still infinite

## Additional context 
![image](https://user-images.githubusercontent.com/106420166/178109211-7738f7e7-8ebc-404f-be70-81d80527e303.png)

**Comment by johnathon-walnut** [comment]
Already known

**Comment by johnpablo1** [comment]
ah ok
