### ISSUE TITLE
 ツ  I have a problem: Fedoraware won't start when I enter .dll, game closes after update

### ISSUE THREAD

**Issue by fast-player** [Fedoraware/Fedoraware#508]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by gayblackirony** [comment]
very helpful

**Comment by johnathon-walnut** [comment]
not enough info to even begin helping you
