### ISSUE TITLE
Crashing while joining a new match or rejoining

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#509]
This is similar to another issue, Everytime i get a new match i get crashed.

**Comment by johnathon-walnut** [comment]
No config?

**Comment by FFJ11** [comment]
Any config i  have, i rejoin i crash, or in just middle of the match

**Comment by SilentBatch** [comment]
Me 2

**Comment by johnathon-walnut** [comment]
I literally play with the cheat normally and I don't get this.

**Comment by SilentBatch** [comment]
I'm crashing whenever I backstab it, it takes a while... but it happens.

**Comment by AlexFlipH1** [comment]
> I'm crashing whenever I backstab it, it takes a while... but it happens.

does it crashes when you backstab a Razorback Sniper? it does that to me as well

**Comment by SilentBatch** [comment]
Speaking of Razorback the "ignore Razorback" is not working... XD

**Comment by SilentBatch** [comment]
> > I'm crashing whenever I backstab it, it takes a while... but it happens.
> 
> does it crashes when you backstab a Razorback Sniper? it does that to me as well

It's not just Razorback, it crashes with anyone.

**Comment by AlexFlipH1** [comment]
im thinking its because of esp since it try to check what happended to the sniper and you backstabbed him and hes didnt died and esp failed and crashed your game, i dont know how to explain it

**Comment by johnathon-walnut** [comment]
https://youtu.be/nw64--u5rFI?t=23

**Comment by unoreversocard** [comment]
i get an exception in visual studio debugger the says out of range at memory or something like that idk (i likely wont reply :D)

**Comment by johnathon-walnut** [comment]
Have you considered that you might be low on RAM

> i get an exception in visual studio debugger the says out of range at memory or something like that idk (i likely wont reply :D)

**Comment by xxmyn** [comment]
debug, config, video, anything?

if it's an std::out_of_range error I assume it's from the cheat, but if nobody else is getting it consistently I'd assume it's a feature you have on, so it would be very helpful to attach a config or a video instead of just saying "cheat crash".

create a new issue post when you're willing to provide helpful information.
