### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#510]
i found crash. how to debug?

**Comment by xxmyn** [comment]
build the dll yourself in debug, attach visual studio to tf2 after injecting the debug build of the cheat, recreate the crash, and visual studio will tell you where the crash happened, and for what reason. 

If it doesn't directly tell you where it happened, it will still tell you what thread the error happened on, and you can move through the stack to find whatever line of code probably caused it.

If the game closes and visual studio stops debugging, crash didn't happen and it was probably a config issue.
