### ISSUE TITLE
The Bipolar Ambassador

### ISSUE THREAD

**Issue by SilentBatch** [Fedoraware/Fedoraware#518]
The Ambassador weapon is very strange when using the auto shoot with the smooth Aimbot, sometimes it fires and sometimes it doesn't, and the weapon starts to completely bug, from what I saw in the animation it doesn't know whether to reload or fire.

**Comment by xxmyn** [comment]
it can't catch up to the point on a moving target, so it doesn't fire.

**Comment by johnathon-walnut** [comment]
It seems fine to me, obviously it's not gonna shoot at nothing, havent experienced anything wrong the animation either
