### ISSUE TITLE
radar does not work

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#520]
**Fedoraware Version Date: Last version**

## Steps to reproduce: turn on the radar

1 - turn on the radar

**Comment by AlexFlipH1** [comment]
your dll may be broken you can detele it and reinstall the dll from the fedoraloader hold win and r and type %temp% and look for fedloader, data, and detele the dll
![image](https://user-images.githubusercontent.com/108676611/178908231-3f57344d-4d6d-4de3-b0bd-4ec6bccf6bf7.png)

**Comment by johnathon-walnut** [comment]
See, there's a minor issue with your config...

`"Vars::Radar::Players::Active": "false"`

This means that you don't have players enabled on the radar. It's not broken, you just haven't enabled it.

**Comment by xxmyn** [comment]
gabrylnicollahbruh
