### ISSUE TITLE
are there any configs

### ISSUE THREAD

**Issue by jertynr** [Fedoraware/Fedoraware#523]
I am new to the world of cheats, I do not know how to configure cheats, you can find out where to get configs, or you can throw them off

**Comment by AlexFlipH1** [comment]
https://cdn.discordapp.com/attachments/993113173517418557/997470377691324487/dumbass_save_it.fw here ya go put this in Steam\steamapps\common\Team Fortress 2\FedFigs and open fedorawave

**Comment by jertynr** [comment]
thx
