### ISSUE TITLE
fedorawave breaks so hard

### ISSUE THREAD

**Issue by AlexFlipH1** [Fedoraware/Fedoraware#524]
config i used:https://cdn.discordapp.com/attachments/993113173517418557/997470377691324487/dumbass_save_it.fw
so today i founded this bug with the thirdperson and it shows to everyone even if you are using conga it breaks so hard
![20220715144513_1](https://user-images.githubusercontent.com/108676611/179217572-e02d7cfe-c2d6-4487-a196-36baaa058b52.jpg)
![20220715001313_1](https://user-images.githubusercontent.com/108676611/179217580-d0d3f960-1359-4179-8d60-7df8de6c1928.jpg)
![20220715143957_1](https://user-images.githubusercontent.com/108676611/179217583-95cc0be2-9b2a-4b88-95b7-68d6085ecdf2.jpg)

**Comment by AlexFlipH1** [comment]
forgot to mention demoman aimbot also breaks

**Comment by xxmyn** [comment]
what is broken?

the first screenshot im not sure what im supposed to be looking at, the second one is known, mfed forgot to make the lines disappear after a while, and the third one is just the same issue.

also how can the demoman aimbot be broken if you have kills using the demoman aimbot in 2/3 attached screenshots???

**Comment by AlexFlipH1** [comment]
the third screenshot shows that if i press w or a or d the spy thought i was looking that way and it breaks with conga and the first screenshot is same with second one

**Comment by AlexFlipH1** [comment]
so yeah technically i dont know what happended

**Comment by johnathon-walnut** [comment]
I didn't forget to make the lines disappear I just didn't want them to :(

**Comment by xxmyn** [comment]
test.mensa.no and post results @AlexFlipH1

**Comment by gayblackirony** [comment]
> the third screenshot shows that if i press w or a or d the spy thought i was looking that way and it breaks with conga and the first screenshot is same with second one

probably talking about anti-backstab
