### ISSUE TITLE
Aimbot is broken 

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#526]
I was doing a setup and when I noticed the aimbot wasn't pulling to the target on every shot so the other shots going to where your aim is, I'm using the latest version of fedoraware

video below
vvvvvvvvvv
https://www.youtube.com/watch?v=Or55ufP-_7A
^^^^^^^

**Comment by xxmyn** [comment]
looks like its because of your fps.

**Comment by lGabryl** [comment]
my friend has the same problem and plays at 144 fps

**Comment by xxmyn** [comment]
i do not experience this issue even when locked at 33 fps so im unsure whats causing it for you

**Comment by lGabryl** [comment]
do you want me to send the config for you to test? I don't know if it could be the config

**Comment by xxmyn** [comment]
sure

**Comment by lGabryl** [comment]
https://www.mediafire.com/file/jecip812u021bfa/SCOUT_DT.fw/file

**Comment by xxmyn** [comment]
pro tip for next time, you can change the extension from .fw to .txt and upload it directly to this issue post.

**Comment by xxmyn** [comment]
I can't recreate this w/ fps locked to 33 as well as fps unlocked & while using your unchanged config.

**Comment by lGabryl** [comment]
so what could be the reason my aimbot is like this

**Comment by xxmyn** [comment]
No clue, I can't recreate it on my or your config, so I'm not going to put time into it.
