### ISSUE TITLE
Autobackstab Backrack

### ISSUE THREAD

**Issue by Brxho** [Fedoraware/Fedoraware#527]
i think whats missing the most is the autobackstab backtrack feature, one of the best features you could add

**Comment by Capybaron** [comment]
Shut up

**Comment by gayblackirony** [comment]
shut up

**Comment by johnathon-walnut** [comment]
Soon maybe, but again I don't wanna promise anything because I am genuinely braindead

https://user-images.githubusercontent.com/36936588/179366500-b67b4f02-c259-48de-9e70-21ea8b3653e6.mp4

**Comment by MrRealTimeTF2** [comment]
> Soon maybe, but again I don't wanna promise anything because I am genuinely braindead
> 
>  hl2_IWygVSgIab.mp4

I'm down to help work on this with you but since how bt is set up it's not as easy as people think especially that guy who keeps making alt's to say the same thing

**Comment by gayblackirony** [comment]
fuck you gabriel

**Comment by johnathon-walnut** [comment]
> > Soon maybe, but again I don't wanna promise anything because I am genuinely braindead
> > hl2_IWygVSgIab.mp4
> 
> I'm down to help work on this with you but since how bt is set up it's not as easy as people think especially that guy who keeps making alt's to say the same thing

Sure, there's still a lot of things I need to do with backtrack and honestly the auto backstab seems like the most annoying to get working, so if you wanna do that for me (I'm retarded) then that'd be nice

**Comment by whyskyboxchange** [comment]
> > > Soon maybe, but again I don't wanna promise anything because I am genuinely braindead
> > > hl2_IWygVSgIab.mp4
> > 
> > 
> > I'm down to help work on this with you but since how bt is set up it's not as easy as people think especially that guy who keeps making alt's to say the same thing
> 
> Sure, there's still a lot of things I need to do with backtrack and honestly the auto backstab seems like the most annoying to get working, so if you wanna do that for me (I'm retarded) then that'd be nice

arent you mfed youre the guy that helped me get auto backstab to work for bt in the discord

**Comment by johnathon-walnut** [comment]
Yes i'm mfed, what do you mean helped you get auto backstab to work for bt?

**Comment by whyskyboxchange** [comment]
> Yes i'm mfed, what do you mean helped you get auto backstab to work for bt?

#include "AutoStab.h"

#include "../../Vars.h"

#include "../../Backtrack/Backtrack.h"

bool CAutoStab::CanBackstab(const Vec3& vSrc, const Vec3& vDst, Vec3 vWSCDelta)
{
	vWSCDelta.z = 0;
	vWSCDelta.NormalizeInPlace();

	auto vecEyeSpy = Vec3();
	Math::AngleVectors(vSrc, &vecEyeSpy);
	vecEyeSpy.z = 0;
	vecEyeSpy.NormalizeInPlace();

	auto vecEyeVictim = Vec3();
	Math::AngleVectors(vDst, &vecEyeVictim);
	vecEyeVictim.z = 0;
	vecEyeVictim.NormalizeInPlace();

	if (vWSCDelta.Dot(vecEyeVictim) <= 0.01f)
		return false;

	if (vWSCDelta.Dot(vecEyeSpy) <= 0.5f)
		return false;

	if (vecEyeSpy.Dot(vecEyeVictim) <= -0.3f)
		return false;

	return true;
}

bool CAutoStab::TraceMelee(CBaseEntity* pLocal, CBaseCombatWeapon* pWeapon, const Vec3& vViewAngles,
                           CBaseEntity** pEntityOut)
{
	float flRange = (48.0f * Vars::Triggerbot::Stab::Range.m_Var);

	if (flRange <= 0.0f)
		return false;

	auto vForward = Vec3();
	Math::AngleVectors(vViewAngles, &vForward);
	Vec3 vTraceStart = pLocal->GetShootPos();
	Vec3 vTraceEnd = (vTraceStart + (vForward * flRange));

	CGameTrace Trace = {};
	CTraceFilterHitscan Filter = {};
	Filter.pSkip = pLocal;
	Utils::TraceHull(vTraceStart, vTraceEnd, {-18.0f, -18.0f, -18.0f}, {18.0f, 18.0f, 18.0f}, MASK_SOLID, &Filter,
	                 &Trace);

	if (IsEntityValid(pLocal, Trace.entity))
	{
		if (pEntityOut && !*pEntityOut)
			*pEntityOut = Trace.entity;

		return true;
	}

	return false;
}

bool CAutoStab::IsEntityValid(CBaseEntity* pLocal, CBaseEntity* pEntity)
{
	if (!pEntity || !pEntity->IsAlive() || pEntity->GetTeamNum() == pLocal->GetTeamNum() || !pEntity->IsPlayer())
		return false;

	if (F::AutoGlobal.ShouldIgnore(pEntity)) { return false; }

	return true;
}

void CAutoStab::RunLegit(CBaseEntity* pLocal, CBaseCombatWeapon* pWeapon, CUserCmd* pCmd)
{
	CBaseEntity* pEnemy = nullptr;

	if (!TraceMelee(pLocal, pWeapon, pCmd->viewangles, &pEnemy))
		return;

	if (Vars::Triggerbot::Stab::IgnRazor.m_Var && pEnemy->GetClassNum() == CLASS_SNIPER &&
		pEnemy->GetWeaponFromSlot(SLOT_SECONDARY)->GetItemDefIndex() == Sniper_s_TheRazorback)
		return;

	if (!CanBackstab(pCmd->viewangles, pEnemy->GetEyeAngles(),
	                 (pEnemy->GetWorldSpaceCenter() - pLocal->GetWorldSpaceCenter())))
		return;

	pCmd->buttons |= IN_ATTACK;
	m_bShouldDisguise = true;

	if (Vars::Misc::DisableInterpolation.m_Var)
	{
		pCmd->tick_count = TIME_TO_TICKS(pEnemy->GetSimulationTime()
			+ std::max(g_ConVars.cl_interp->GetFloat(), g_ConVars.cl_interp_ratio->GetFloat() / g_ConVars.cl_updaterate
				->GetFloat()));
	}
}

void CAutoStab::RunRage(CBaseEntity* pLocal, CBaseCombatWeapon* pWeapon, CUserCmd* pCmd)
{
	for (const auto& pEnemy : g_EntityCache.GetGroup(EGroupType::PLAYERS_ENEMIES))
	{
		if (Vars::Triggerbot::Stab::IgnRazor.m_Var && pEnemy->GetClassNum() == CLASS_SNIPER &&
			pEnemy->GetWeaponFromSlot(SLOT_SECONDARY)->GetItemDefIndex() == Sniper_s_TheRazorback)
			continue;

		CBaseEntity* pTraceEnemy = nullptr;

		Vec3 vAngleTo = Math::CalcAngle(pLocal->GetShootPos(), pEnemy->GetHitboxPos(HITBOX_PELVIS));

		bool bBacktrackable = (!F::Backtrack.Record[pEnemy->GetIndex()].empty());

		Vec3 vBackupPos = pEnemy->GetAbsOrigin();

		if (bBacktrackable) {
			for (size_t t = 0; t < F::Backtrack.Record[pEnemy->GetIndex()].size(); t++)
			{
				if (F::Backtrack.IsGoodTick(t)) { continue; }
				auto playerbones = reinterpret_cast<matrix3x4*>(&F::Backtrack.Record[pEnemy->GetIndex()].at(t).BoneMatrix);
				Vec3 pelvisPos = Vec3(playerbones[HITBOX_PELVIS][0][3],
					playerbones[HITBOX_PELVIS][1][3],
					playerbones[HITBOX_PELVIS][2][3]);

				vAngleTo = Math::CalcAngle(pLocal->GetShootPos(), pelvisPos);


				pEnemy->SetAbsOrigin(F::Backtrack.Record[pEnemy->GetIndex()].at(t).AbsOrigin);
			}
		}

		if (!TraceMelee(pLocal, pWeapon, vAngleTo, &pTraceEnemy) || pTraceEnemy != pEnemy)
			continue;

		if (!CanBackstab(vAngleTo, pEnemy->GetEyeAngles(),
			(pEnemy->GetWorldSpaceCenter() - pLocal->GetWorldSpaceCenter())))
			continue;

		if (bBacktrackable) {
			pEnemy->SetAbsOrigin(vBackupPos);
		}

		if (Vars::Triggerbot::Stab::Silent.m_Var)
		{
			Utils::FixMovement(pCmd, vAngleTo);
			G::SilentTime = true;
		}

		pCmd->viewangles = vAngleTo;
		pCmd->buttons |= IN_ATTACK;
		m_bShouldDisguise = true;

		if (pCmd->buttons & IN_ATTACK) {
			if (!F::Backtrack.Record[pEnemy->GetIndex()].empty()) {
				pCmd->tick_count = TIME_TO_TICKS(F::Backtrack.Record[pEnemy->GetIndex()].back().SimulationTime);
			}
			else{
				pCmd->tick_count = TIME_TO_TICKS(pEnemy->GetSimulationTime());
			}
		}

		break;
	}
}


void CAutoStab::Run(CBaseEntity* pLocal, CBaseCombatWeapon* pWeapon, CUserCmd* pCmd)
{
	if (!Vars::Triggerbot::Stab::Active.m_Var || !G::WeaponCanAttack || pWeapon->GetWeaponID() !=
		TF_WEAPON_KNIFE)
		return;

	if (Vars::Triggerbot::Stab::RageMode.m_Var)
		RunRage(pLocal, pWeapon, pCmd);

	else RunLegit(pLocal, pWeapon, pCmd);

	if (pCmd->buttons & IN_ATTACK)
		G::IsAttacking = true;

	G::AutoBackstabRunning = true;
}

**Comment by whyskyboxchange** [comment]
> Yes i'm mfed, what do you mean helped you get auto backstab to work for bt?

oops how do i attach code again

**Comment by whyskyboxchange** [comment]
> Yes i'm mfed, what do you mean helped you get auto backstab to work for bt?
[message (8).txt](https://github.com/Fedoraware/Fedoraware/files/9126687/message.8.txt)

**Comment by whyskyboxchange** [comment]
u helped me code this horrible mess which at the time worked but now doesnt work anymore since i think its because of some get simulation time junk so feel free to fix, it only works on 1 game btw, what i mean by that is, u queue into a match and then if u go to another one, when it tries to backstab an enemy in that new match whatever it does the anim and the melee sound yet no hit registered

**Comment by johnathon-walnut** [comment]
Mfw my brain has actually degraded over time

**Comment by whyskyboxchange** [comment]
> Mfw my brain has actually degraded over time

LOL

**Comment by MrRealTimeTF2** [comment]
> > > Soon maybe, but again I don't wanna promise anything because I am genuinely braindead
> > > hl2_IWygVSgIab.mp4
> > 
> > 
> > I'm down to help work on this with you but since how bt is set up it's not as easy as people think especially that guy who keeps making alt's to say the same thing
> 
> Sure, there's still a lot of things I need to do with backtrack and honestly the auto backstab seems like the most annoying to get working, so if you wanna do that for me (I'm retarded) then that'd be nice

yeah yeah msg me on telegram: MrRealTime or discord: MrRealTime#3604 with what you've got so far

**Comment by johnathon-walnut** [comment]
Well i'm still not happy with how it turned out, but it's working now.
