### ISSUE TITLE
crashes like 2s after inject 0xE06D7363

### ISSUE THREAD

**Issue by gr8m9** [Fedoraware/Fedoraware#528]
crashes like 2s after inject

**Comment by johnathon-walnut** [comment]
FAK OFF

**Comment by gr8m9** [comment]
???????

**Comment by johnathon-walnut** [comment]
sorry i'm insane

**Comment by gr8m9** [comment]
what do i do w it?

**Comment by Capybaron** [comment]
> ???????

Please join the Discord server

**Comment by johnathon-walnut** [comment]
Can you give any more details, obviously "crashes like 2s after inject" is like the least helpful shit you could possibly say

**Comment by lnx00** [comment]
Please attach your crash dump :)

**Comment by gr8m9** [comment]
https://www.dropbox.com/s/w88kfl9j3szdpaz/Fedoraware_CrashDump_d113d113d113.dmp?dl=0

**Comment by gr8m9** [comment]
> 

wheres invite?

**Comment by gr8m9** [comment]
to the discord*
