### ISSUE TITLE
[Idea for chams tab]

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#531]
Could add a setting when the enemy is visible or invisible change his chams

example: when a sniper has only his head showing and the rest of the body is hidden, his head could turn green and the rest of the body that is not visible would turn red, this can help a lot in my opinion

**Comment by NitroTF2** [comment]
Bad

**Comment by xxmyn** [comment]
to do this with our ignorez method (pasted) we would need to use stencils (that i would paste from spook) and would need to call dme twice for each stencil operation, which frankly, I don't want to do (not for performance, but because i'm lazy).
