### ISSUE TITLE
[Request]aa visual 

### ISSUE THREAD

**Issue by bestcheater123** [Fedoraware/Fedoraware#533]
![Screenshot 2022-07-17 140210](https://user-images.githubusercontent.com/103880511/179388007-8ab39b13-b805-4fdc-baa6-24c56720007d.png)
![20220717140801_1](https://user-images.githubusercontent.com/103880511/179388008-c1c5b7e9-3764-439c-804b-e45c388f7973.jpg)

**Comment by xxmyn** [comment]
i tried and failed

**Comment by bestcheater123** [comment]
why u failed dude?

**Comment by xxmyn** [comment]
if I knew I would've fixed it.

**Comment by johnathon-walnut** [comment]
I tried and failed

**Comment by Capybaron** [comment]
@everyone
