### ISSUE TITLE
Demoknight charge glitches while fast acceleration is on

### ISSUE THREAD

**Issue by Gught** [Fedoraware/Fedoraware#537]
Fast acceleration ain't needed while demo is charging so it should turn off until charge has stopped, or else it will look like demo is charging sideways but the server teleporting you back

**Comment by NitroTF2** [comment]
Maybe manually turn it off? Problemo slovef

**Comment by xxmyn** [comment]
fast accel isnt needed at all but it makes antiwarp significantly better and i want it on all the time cause im a movement player

**Comment by Gught** [comment]
> fast accel isnt needed at all but it makes antiwarp significantly better and i want it on all the time cause im a movement player

But how can it help if i use demoknight shield charge, im already moving at full speed, only thing that changed is i cant control it and just glitching around the map

**Comment by Gught** [comment]
> > fast accel isnt needed at all but it makes antiwarp significantly better and i want it on all the time cause im a movement player
> 
> But how can it help if i use demoknight shield charge, im already moving at full speed, only thing that changed is i cant control it and just glitching around the map

I think it should turn off for a moment while im using shield charge and turn on when i start moving without charge

**Comment by Gught** [comment]
Fixed (Kinda), still happens very rarely

**Comment by Gught** [comment]
> uhh no this is not fixed at all
atleast it is much better than before

**Comment by Gught** [comment]
yeah, that fixed it, but i dont know how to contribute changes im too dumb
