### ISSUE TITLE
add backtrack auto backstab pls )))))00))))))))))))))00))))0

### ISSUE THREAD

**Issue by ilya228011** [Fedoraware/Fedoraware#538]

**Comment by johnathon-walnut** [comment]
Dude wtf do you think I spent my entire afternoon doing are you fucking retarded? This is already in the cheat, fuck off.

**Comment by ilya228011** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaa okay

**Comment by lnx00** [comment]
> Dude wtf do you think I spent my entire afternoon doing are you fucking retarded? This is already in the cheat, fuck off.

rq
