### ISSUE TITLE
Glow stops working through walls after server/map change

### ISSUE THREAD

**Issue by wommzat** [Fedoraware/Fedoraware#549]
**Fedoraware Version Date: Jul 19 2022**  

## Description:  
Glow works completely fine at first launch but after a server/map change, it stops becoming visible when obscured.

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Change map/server.

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by debugac** [comment]
YES PLZ FIX THIS..

**Comment by lnx00** [comment]
Does this still happen?
