### ISSUE TITLE
erm nitro dt bar no work 😭😭😭😭😭😭😭

### ISSUE THREAD

**Issue by FvnDestruction** [Fedoraware/Fedoraware#551]
erm.... when i have hack injected i no see nitro dt bar...

**Comment by johnathon-walnut** [comment]
Why

**Comment by FvnDestruction** [comment]
it is invisible

**Comment by johnathon-walnut** [comment]
What do you expect to see

**Comment by johnathon-walnut** [comment]
Prove you have the option on

**Comment by FvnDestruction** [comment]
rijin and the regular one work, yes i have dt enabled, and no i dont have a invisible menu accent color

**Comment by johnathon-walnut** [comment]
Post config

**Comment by FvnDestruction** [comment]
ok

**Comment by yesyes786** [comment]
config issue

**Comment by johnathon-walnut** [comment]
https://github.com/Fedoraware/Fedoraware/commit/9d36f36bccc0a8575ff965cbce13f3f0bffe3bf5

Fixed in this commit probably
