### ISSUE TITLE
Fedora doesn't working in some injectors using manual-map.

### ISSUE THREAD

**Issue by SilentBatch** [Fedoraware/Fedoraware#552]
I was testing fedora in other injectors and I noticed that in most I used manual-map, in a few seconds after injection it closes the game...

I used the following projects...

https://github.com/danielkrupinski/Inflame/tree/master

https://github.com/TheCruZ/Simple-Manual-Map-Injector

https://github.com/mdilai/Shtreeba

https://github.com/danielkrupinski/MemJect

**Comment by xxmyn** [comment]
what a dumb issue

**Comment by johnathon-walnut** [comment]
The problem isn't the injector you use, it's the injection method. Use a normal injector.

**Comment by SilentBatch** [comment]
![image](https://user-images.githubusercontent.com/96029590/180001076-4cb82356-1e2a-4826-aab8-bc88c84b3594.png)

**Comment by johnathon-walnut** [comment]
Whoever wrote that is dumb tbh

**Comment by johnathon-walnut** [comment]
We haven't edited readme in forever

**Comment by johnathon-walnut** [comment]
I didn't say anything rude to you

**Comment by HutchyBean** [comment]
![image](https://user-images.githubusercontent.com/38333275/180076132-1fa15143-2346-4b9e-9817-9099a8a4595d.png)
lol
