### ISSUE TITLE
crash while joining community server

### ISSUE THREAD

**Issue by darkst0rm223** [Fedoraware/Fedoraware#553]
**Fedoraware Version Date: jul 20 2022**  

## Config used:

https://files.catbox.moe/fkrapz.fw
## Description:  
Well i tried to join a community server and i crashed when i got into the class selecting menu

## Steps to reproduce:  
1 - join community server
2 - select team
3 - crash
- [X ] I am able to consistently reproduce this error

## Additional context 

- [X ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
This sometimes happens due to the playerlist I believe

**Comment by lnx00** [comment]
Would be helpful if your could provide the server IP you wanted to join.

**Comment by lnx00** [comment]
Seems to be fixed since there was never an answer (?)
