### ISSUE TITLE
projectile dt bug

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#556]
**Fedoraware Version Date:**  
current one

## Config used:
https://files.catbox.moe/759z4y.fw

## Description:  
the projectile shoots under you when double tapping (happens with all projectile class huntsman, demo)

## Steps to reproduce the behavior: 
1. go on a projectile based class
2. press the aimbot key when the double tap key in on
3. the projectile will shoot under you when the dt is on

## Additional context 

https://user-images.githubusercontent.com/106420166/180186193-02195276-af00-4c7a-b5a1-e21f57870dd9.mp4

**Comment by johnathon-walnut** [comment]
@xxmyn

**Comment by johnathon-walnut** [comment]
This is due to the anti warp

**Comment by xxmyn** [comment]
All I can think to fix this is to stop our movement at a different spot if the weapon we are using has a delay.

I can't use the G::IsAttacking check to stop it, as it fucks up antiwarp for some reason.

**Comment by johnathon-walnut** [comment]
> All I can think to fix this is to stop our movement at a different spot if the weapon we are using has a delay.
> 
> I can't use the G::IsAttacking check to stop it, as it fucks up antiwarp for some reason.

Again, why can't we just use the old WalkTo anti warp, it has way less problems and works pretty much the same
