### ISSUE TITLE
anti aim melee bug

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#557]
**Fedoraware Version Date:**  
latsty

## Config used:
https://files.catbox.moe/0tzy33.fw

## Description:  
when anti aim is on melee aimbot cannot hit the target

## Steps to reproduce the behavior:  
1. go on any class
2. turn on the anti aim
3. try to melee a target
4. no work

## Additional context 
i manually melee'd in this video and it doesnt seem to hit at all

https://user-images.githubusercontent.com/106420166/180189370-651e5cf8-33ce-4cf7-9b27-27cc62dfba40.mp4

**Comment by NitroTF2** [comment]
I didn't get issues with melee and anti aim

**Comment by xxmyn** [comment]
add this code;
`if (!Vars::Aimbot::Global::DontWaitForShot.Value && (!G::WeaponCanAttack && !G::IsAttacking))
	{ 
		return false; 
	}	//	don't run if we can't shoot (should stop unbearable dt lag)`

and it should be fixed.

**Comment by xxmyn** [comment]
or just turn on DontWaitForShot.

**Comment by johnpablo1** [comment]
ok

**Comment by xxmyn** [comment]
THIS IS NOT FIXED!!!

**Comment by johnpablo1** [comment]
oh

**Comment by xxmyn** [comment]
should now be fixed.
