### ISSUE TITLE
Fix bug where you can't select a map at end of round

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#558]
Add buttons in the menu somewhere in the GUI for selecting a map when the map vote glitches out.

`next_map_vote 0`, 0=left 1=middle 2=right

**Comment by johnathon-walnut** [comment]
What

**Comment by johnathon-walnut** [comment]
Is this caused by the cheat or are you asking us to find out a way to fix valve's bug

**Comment by SylveonBottle** [comment]
my dumbass pressed enter on the title and accidentally posted the post without actually typing anything

**Comment by johnathon-walnut** [comment]
oh ok, didn't see the original part, i mean yeah i could do that i guess

**Comment by johnathon-walnut** [comment]
i'd rather know why you can't click on it in the first place tbh but buttons work too

**Comment by SylveonBottle** [comment]
> i'd rather know why you can't click on it in the first place tbh but buttons work too

No clue, but it's been a bug for years. https://github.com/ValveSoftware/Source-1-Games/issues/2417

**Comment by johnathon-walnut** [comment]
![image](https://user-images.githubusercontent.com/36936588/180315112-ccd2395a-8eb2-4c4d-bcdc-e55eb439736e.png)

**Comment by johnathon-walnut** [comment]
you can not undo your sins (i don't think they care)

**Comment by johnathon-walnut** [comment]
CNextMapVotingDashboardState seems to be what's in charge of this though

**Comment by SylveonBottle** [comment]
would be super cool if there was a way to patch this bug
but I'd settle for just something in the GUI

Maybe you can have a panel pop up with three buttons to pick the map, and the panel only shows during the map voting period? so like hidden panel that only shows when a map vote is in progress

**Comment by johnathon-walnut** [comment]
CNextMapVotingDashboardState::ShouldBeActve

good old valve "Actve"

**Comment by johnathon-walnut** [comment]
You wouldn't happen to know what causes this to happen in the first place right?

**Comment by SylveonBottle** [comment]
> You wouldn't happen to know what causes this to happen in the first place right?

not one clue nope
just happens randomly
Valve claimed to fix it in recent patch but it still happens

**Comment by johnathon-walnut** [comment]
Also, putting this on hold for now, i've just compared everything from CNextMapVotingDashboardState in the dylibs from like april 2021 and from latest update and don't see any difference so i might not be looking in the right place

**Comment by xxmyn** [comment]
there are keybinds for it yknow...

**Comment by lnx00** [comment]
https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/client/tf/vgui/tf_matchmaking_dashboard_next_map_voting.cpp#L150

Patching this line to `InvalidateLayout( true, true);` might fix the bug, since it'll cause a scheme reload (which does fix the issue when done manually through `hud_reloadscheme`).

**Comment by johnathon-walnut** [comment]
:true:

**Comment by lnx00** [comment]
I think we should let Valve handle this one
