### ISSUE TITLE
DT Auto-Recharge and Anti-Warp clashes in multiplayer

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#559]
(turn sound on)

https://user-images.githubusercontent.com/17802843/180336945-f3303daf-7d93-4b51-ab83-c675eb0d4940.mp4

If Auto-Recharge and Anti-Warp is both enabled, using DT while aimbot is shooting a target causes the first shot to fail for some reason.

This issue _seems_ to be caused by DT instantly trying to auto-recharge when not moving, "not moving" caused by anti-warp.
This issue doesn't seem to be affected when manually shooting DT (without aimbot). I have no clue why.
This issue doesn't seem to happen in localhost testing servers. Only multiplayer where lag is a factor.

However, even when testing in localserver, I do not like auto-recharge instantly attempting to recharge the DT bar before firing the second shot. This causes an unnecessary pause in player movement, as seen here:

https://user-images.githubusercontent.com/17802843/180337335-7292fabe-b4c6-40e2-a130-581b9eb36360.mp4

**Comment by SylveonBottle** [comment]
A potential solution to this problem could be to have auto-recharge not activate unless DT is possible (essentially, wait until full clip).
Alternatively, perhaps a form of "passive recharging" could fix the issue? Instead of recharging all ticks immediately, just recharge a single tick every X ticks. This will cause the player to be slightly slower by a small factor, however it is not as jarring as instantly stopping mid-shot against an enemy.

And, yes, of course.. an easy fix is to just not us auto-recharge and to charge manually.

**Comment by NitroTF2** [comment]
It could be stop movement recharge because auto recharge charge if you don't move, I could be wrong but manually recharge.
