### ISSUE TITLE
Lag disabled when DT shifted ticks

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#560]
Fedoraware's chams did not render any of my fake lag chams when i have my DT shifting ticks

**Comment by johnathon-walnut** [comment]
Ok?

**Comment by FFJ11** [comment]
How to fix it?

**Comment by johnathon-walnut** [comment]
What is there to fix?

**Comment by FFJ11** [comment]
I can't see my fakelag chams if i set the DT To 22

**Comment by johnathon-walnut** [comment]
I don't understand what your issue is

**Comment by xxmyn** [comment]
You can't fakelag while shifting ticks, retain fakelag ONLY works if you have space (delta between your ticks and 22) and will only allow you to fakelag until that space is filled.
