### ISSUE TITLE
What the fuck is wrong with sort by fov

### ISSUE THREAD

**Issue by Fowgzu** [Fedoraware/Fedoraware#561]
It only works 70% of the time as intended

Whenever someone gets too close it just snaps to a random guy 50 meters behind even tho your crosshair is literally on the closest person

**Comment by johnathon-walnut** [comment]
Are they visible?

**Comment by Fowgzu** [comment]
Yea they could be in front of me, fully visible and it would lock to the sniper behind

**Comment by johnathon-walnut** [comment]
Video proof

**Comment by Fowgzu** [comment]
https://outplayed.tv/media/mPneDW

**Comment by Fowgzu** [comment]
Sorry for weird res

**Comment by lnx00** [comment]
> https://outplayed.tv/media/mPneDW

The scout had a higher priority (marked as CHEATER) than the sniper.

**Comment by Fowgzu** [comment]
Is there even a way to turn that off as a whole or do i have to manually cherry pick each and every player marked and disable it

**Comment by lnx00** [comment]
You can disable the automatic cheater detection under `Visuals -> Players -> Cheater Detection`.
If you want to remove all previously marked players, then you can delete the file `Team Fortress 2/FedFigs/Core/Playerlist.json`
