### ISSUE TITLE
cant see the fedora menu

### ISSUE THREAD

**Issue by ghosterberr** [Fedoraware/Fedoraware#563]
**Fedoraware Version Date:**  

## Description:  
My pc is pretty weak and I decided to play with a resolution of 800x600, but the menu was too big and did not fit on my screen, I had to shrink it a little, but after I restarted the game when I pressed insert my menu did not open, but the cheat worked (I knew it by the date in the bottom left corner when I pressed insert it appeared) (sorry if I made a lot of mistakes, my English is not the best).

## Steps to reproduce:  
- [yes] I am able to consistently reproduce this error

1. Enable 800x600 resolution
2. Do shrink the menu
3. Notice restart the game

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by gayblackirony** [comment]
try to delete imgui.ini in the "Team Fortress 2" (installation folder basically) folder and reinject

**Comment by ghosterberr** [comment]
> try to delete imgui.ini in the "Team Fortress 2" (installation folder basically) folder and reinject

omg bro thx so much its working
