### ISSUE TITLE
Disable cheat detection completely

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#564]
Disable cheat detection completely. Sometimes the feature is enable automatically. Add it please at least in MISC.

**Comment by johnathon-walnut** [comment]
It doesn't run if you have cheater detection off in Visuals -> Players -> Player ESP -> Cheater detection
![image](https://user-images.githubusercontent.com/36936588/180643710-d212a69e-d257-4c93-8147-02b1ec296f66.png)

**Comment by johnathon-walnut** [comment]
Then it's not enabled

**Comment by johnathon-walnut** [comment]
Of course there are
