### ISSUE TITLE
Buttons for features related with help in team

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#574]
Buttons for features related with help in team: heal with Crusader's Crossbow, shoot with Rescue Ranger to friendly buildings. I mean make friendly features separate (enable/disable). Sometimes they get in the way when hitting an enemy.

**Comment by lnx00** [comment]
We should be able to add it quite easily just like we did with the auto whip Feature

**Comment by lnx00** [comment]
Apparently, this is already available in Fedoraware:
https://github.com/Fedoraware/Fedoraware/blob/b6b8891caae04c5259c4edd768a44d33478ad0b3/Fedoraware/TeamFortress2/TeamFortress2/Features/Aimbot/AimbotProjectile/AimbotProjectile.cpp#L812
https://github.com/Fedoraware/Fedoraware/blob/b6b8891caae04c5259c4edd768a44d33478ad0b3/Fedoraware/TeamFortress2/TeamFortress2/Features/Aimbot/AimbotProjectile/AimbotProjectile.cpp#L860
