### ISSUE TITLE
Shoot taking into account the distance to enemy for the Stickybomb Launcher

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#575]
For Aimbot: Shoot taking into account the distance to enemy for the Stickybomb Launcher.
This feature will also be separate.

**Comment by johnathon-walnut** [comment]
If you hold your attack key it will take the charge into account

**Comment by lnx00** [comment]
> If you hold your attack key it will take the charge into account

I think he wants the aimbot to charge until the sticky is able to hit the enemy
