### ISSUE TITLE
Issue whit The aimbot!

### ISSUE THREAD

**Issue by GC634** [Fedoraware/Fedoraware#578]
Since the last 10 days, there has been an issue Whit the aimbot. it Only misses it doesnt matter. What settings you use it still misses every single shot i Even tried to deinstall it and install it. Again But that did not help either. Please fix this Issue/Bug it is very annoying.

**Comment by xxmyn** [comment]
gabriel brain.

on a more serious note, you attached no config, no video, no demo, no info, and only you are experiencing the issue, if you seriously expect me to "fix" an issue that only you are experiencing, while you are unwilling to assist in diagnosing what's causing it, you are delusional.
