### ISSUE TITLE
[SUGGESTION} Manual Anti-Aim.

### ISSUE THREAD

**Issue by N1kolasFlaV** [Fedoraware/Fedoraware#580]
I think the title is enough but let me explain:
So Edge yaw is shit on fedoraware and you can get killed by this very easily because of this so i suggest Manual Anti-Aim ( Manual AA means to move your Real Yaw with your this keybinds: <    >) so yeah that's my shit suggestion

**Comment by FFJ11** [comment]
Bruh  just use spin on real yaw and once it matches the edge put it to 0.0

**Comment by johnathon-walnut** [comment]
Genius

**Comment by FFJ11** [comment]
You don't need to worry because the custom pitch will decrease the chance of your head being shot

**Comment by N1kolasFlaV** [comment]
> Bruh just use spin on real yaw and once it matches the edge put it to 0.0

.... Genius thank yous so  much!

**Comment by johnathon-walnut** [comment]
I added this
