### ISSUE TITLE
Fake angle ???

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#581]
![image](https://user-images.githubusercontent.com/102504389/181487103-e934aee5-b80a-420f-9d62-4898a8f857c2.png)

The fake angle is not doing it correctly why

**Comment by johnathon-walnut** [comment]
Looks like it's "doing it" to me fam

**Comment by xxmyn** [comment]
wow, posting an issue with an image, where the image shows that the cheat is doing exactly what it's meant to, that's fucking crazy.
