### ISSUE TITLE
Stickybomb aimbot

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#585]
Stickybomb aimbot doesn't take into account detonation time causing it to miss on short distance

**Comment by yujispin990** [comment]
stickybomb aimbot does not do well at predicting if the target is going too fast eg. Scout or Charging Demoknight and it also sometimes does not shoot on short distances.

**Comment by canedoly** [comment]
> Stickybomb aimbot also does not do well at predicting if the target is going too fast eg. Scout or Charging Demoknight and it also sometimes does not shoot on short distances.

I don't think that's related with detonation time

**Comment by yujispin990** [comment]
yeah just wanted to get it out there,i feel like older versions perform well when it comes to stickys.
