### ISSUE TITLE
Block sounds of Local Noisemaker

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#587]
I just noticed that the blocking of Noisemaker works on other players, not on local one (me).
An idea came up: Block sounds of Local Noisemaker

**Comment by xxmyn** [comment]
I don't see why it wouldn't work on local.

**Comment by johnathon-walnut** [comment]
what?

**Comment by Capybaron** [comment]
> > what?
> 
> like I use a silent Noisemaker, but others hear it

idiot sandwich

**Comment by johnathon-walnut** [comment]
https://youtu.be/nqY3tv-y62A
