### ISSUE TITLE
[StAC] Banned for pSilent after 10 detections

### ISSUE THREAD

**Issue by mafiotuLX** [Fedoraware/Fedoraware#592]
I've been using fedora for a while on a cummunity server uses this anti cheat system:
https://github.com/sapphonie/StAC-tf2

He was terrible and the admin decided to update the anti cheat :(
and now everytime i play there i get auto banned after killing about 10 players using the silent aimbot

And i'm wondering, is there's any way to bypass this THING? and thanks a lot!

**Comment by SylveonBottle** [comment]
stop using silent aimbot, ez bypass for psilent ban

**Comment by xxmyn** [comment]
tons of ways, iirc while saph did reduce the "dont scan this player" timer, it does still exist, not running cl_move before shooting should land ur shot in that time, you could also make aimstep, where u travel the distance u need to over multiple ticks instead of instantly, reducing your aimbot fov, using smooth aimbot, or not using aimbot at all could also help.

**Comment by SylveonBottle** [comment]
> not running cl_move before shooting should land ur shot in that time

Is that due to player rotations not being instant if you're standing still?
I know there's an anti-aim on some chairs that lets you instantly update your rotation by spamming cl_move

**Comment by Capybaron** [comment]
> > not running cl_move before shooting should land ur shot in that time
> 
> Is that due to player rotations not being instant if you're standing still?
> I know there's an anti-aim on some chairs that lets you instantly update your rotation by spamming cl_move

ah yes, chair antiaim

**Comment by SylveonBottle** [comment]
> ah yes, chair antiaim
gaming chair, training software, hacked client, cheats, whatever you wanna call it lmao

**Comment by xxmyn** [comment]
> > not running cl_move before shooting should land ur shot in that time
> 
> Is that due to player rotations not being instant if you're standing still? I know there's an anti-aim on some chairs that lets you instantly update your rotation by spamming cl_move

thats not the reason stac would ignore you, it had a timer to not scannplayers who had sent a nullcmd recently, sending a nullcmd by stopping cl_move would achieve this

**Comment by SylveonBottle** [comment]
> thats not the reason stac would ignore you, it had a timer to not scannplayers who had sent a nullcmd recently, sending a nullcmd by stopping cl_move would achieve this

Why'd they do that? if you don't mind me asking

**Comment by xxmyn** [comment]
If you fail to send a command it's likely that following it your commands will look unusual, be sent together, and while I haven't looked at the anticheat enough, it's possible that it could falsely detect that as being caused by a cheat?
