### ISSUE TITLE
Aimbot randomly shoots up when using DoubleTap

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#593]
https://user-images.githubusercontent.com/17802843/182012199-74d09c7c-d1c9-4653-9130-21dc49397301.mp4

**Comment by SylveonBottle** [comment]
This may be related to #556 as I've also had it shoot straight down randomly as well.

**Comment by xxmyn** [comment]
straight up is less likely to damage u than straight down is, its an issue with antiwarp
