### ISSUE TITLE
runescape chat

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#594]
![image](https://user-images.githubusercontent.com/17802843/182050014-74330f30-b9dd-4493-9fd8-332459ba3d5b.png)

chat messages are "corrupted" like this
voice lines are just "Voice"
text is yellow which perfectly matches the default Condition color, making it hard to see

possible improvements:
-fix glitch
-disable "Voice", unless you want to make it show subtitles (or at least generic engineer.voice.helpme w/e)
-let us change text color/font

Gotta say I actually love the idea of this feature, being able to see what people nearby are saying is great.

**Comment by johnathon-walnut** [comment]
I object to changing the colour, really I wanted to use DispatchUserMessage so I don't have to filter stuff like (Voice) and has received achievement and all that out but alas

**Comment by johnathon-walnut** [comment]
The "corrupted" text is because it's not a wide string I believe and I can probably fix it

**Comment by johnathon-walnut** [comment]
All issues fixed
![image](https://user-images.githubusercontent.com/36936588/182224207-70884261-cea1-4cee-80f9-e1485f009695.png)
