### ISSUE TITLE
ok this time autobackstab actually has problems.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#595]
ive tried every single thing i can think off to get it to work like before. Did not use backtrack because did not need to it was already too perfect,before it was snappy fast no misses at all does not matter which server or if i had high ping, now it misses alot and sometimes does not even backstab when im at the spot that it can backstab,tried with and without interpolation,tried changing network config nothing works it still misses,before it was so good that people thought i was using backtrack when i didn't even use backtrack.

**Comment by yujispin990** [comment]
i noticed i had 0.0 lerp when using netgraph on newer versions and normal 15.2 on older versions when using interpolation.

**Comment by yujispin990** [comment]
tested old backstab on older versions before the backtrack autostab was added, It works freaking amazingly.idk somewhere along the way something went wrong?

**Comment by yujispin990** [comment]
just tested the old backstab again just now and people kept calling me out for backtrack again XD.

**Comment by yujispin990** [comment]
> > i noticed i had 0.0 lerp when using netgraph on newer versions and normal 15.2 on older versions when using interpolation.
> 
> the finale.


forgive me if im wrong i dont know much about this but is this the reason why backstab is a little sluggish on the newer versions?

**Comment by xxmyn** [comment]
I don't know.

**Comment by yujispin990** [comment]
ah i understand,ill just go ahead and close this very sorry to have bothered you.

**Comment by johnathon-walnut** [comment]
The main problem I have with this issue is that, I didn't make it affect non backtrack auto backstab so I genuinely can not comprehend why it would act different if you don't have backtrack on

**Comment by xxmyn** [comment]
why do you keep closing issues that aren't fixed.

**Comment by yujispin990** [comment]
> The main problem I have with this issue is that, I didn't make it affect non backtrack auto backstab so I genuinely can not comprehend why it would act different if you don't have backtrack on

im not sure why also,i kept trying older versions and on all of them autobackstab was great,but on the latest versions its very noticeably slow and inaccurate,i dont use the backtrackbackstab because i dont wanna get called out but its missing alot with and without out backtrack on some of the newer versions.

**Comment by yujispin990** [comment]
> why do you keep closing issues that aren't fixed.

im sorry about that i thought my issue was stupid and maybe was something wrong with my pc and i didnt wanna bother you guys with this. But i play spy alot and your autobackstab is without a doubt the best i've ever used, it is really fun and you can really notice if there's suddenly something wrong with it.

**Comment by xxmyn** [comment]
if an issue is stupid we'll close it ourselves, either way it's not a big issue, it's just nice to keep issues here so that people who forked the cheat / want to work on this repo have an easy place to get ideas on what should be fixed / improved.

**Comment by yujispin990** [comment]
ok i have been switching back and forth and i found out that the newer version is a little bipolar it works ok sometimes but for some reason after a while its just bad,the old backstab was really good,i've been using for about 3 hours and even played on 140 ping server it still slaps hard!

**Comment by yujispin990** [comment]
also found that when i used the MSBuild #660 onwards where the backtrack autopeek was implemented for some reason the backstab is really bad it wont even stab when the animation played and i was literally behind the enemy while on a good ping server....its wierd idk maybe its a me problem?

**Comment by yujispin990** [comment]
also found that when i used the MSBuild #660 onwards for some reason the backstab is really bad it wont even stab when the animation played and i was literally behind the enemy while on a good ping server....its wierd idk maybe its a me problem?

**Comment by johnathon-walnut** [comment]
Fixed the main bug with this yesterday
