### ISSUE TITLE
Doubletap sometimes not working 

### ISSUE THREAD

**Issue by JDNA364PROC** [Fedoraware/Fedoraware#596]
yeah ive been using dt and noticed some issue that sometimes it doesnt work 

it usually is like that = it ,,shoots" 2 bullets (force of nature) but after a second it bring 1 bullet back 
same with heavy when i use it it shoots 5 bullets but then goes back any solution or its just my retarded brain

**Comment by canedoly** [comment]
For me recently its been the complete opposite, heavy dt works amazing and scout aswell but I had the same issue as you for a long time before. You might wanna upload your config and maybe your average fps so people can help you

**Comment by JDNA364PROC** [comment]
yeah 
average fps=150-200
config=https://www.mediafire.com/file/uaf2iv6pvtl823i/qucik.fw/file

**Comment by yesyes786** [comment]
did you forget this is fedoraware not rijin?

**Comment by NitroTF2** [comment]
updates mess with cheats... not a new thing.. wait for shift or like wait a sec and then dt...

**Comment by johnathon-walnut** [comment]
Wait to be fully reloaded if using FaN, turn off safe tick if heavy, shift 22 ticks
