### ISSUE TITLE
About projectile aimbot config

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#597]
![image](https://user-images.githubusercontent.com/105226646/182203760-532c2e11-7f29-4d49-b741-cfa77b0ec3ef.png)
Idk how to properly set up the projectile aimbot. Can you please tell me if my settings are correct for Huntsman?

**Comment by johnathon-walnut** [comment]
they are not correct

**Comment by N1kolasFlaV** [comment]
They're so bad..

**Comment by johnathon-walnut** [comment]
![image](https://user-images.githubusercontent.com/36936588/182249787-674cf961-0048-4928-8af0-9b40f21bd05c.png)
These are my settings, personally
