### ISSUE TITLE
Sniper line of sight

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#599]
Something like this
![image](https://user-images.githubusercontent.com/81353241/182220412-04297f0e-9ac3-4a62-b12a-b783080c341a.png)
It will show where the sniper is aiming and this could be useful, and also sniper bots in mvm use that so should be kinda easy to add. I'm pretty sure it just draws the wrangler laser from sniper's eyes to his dot

**Comment by johnathon-walnut** [comment]
i'd rather just use a line, thoughts?

**Comment by canedoly** [comment]
A simple line is good aswell

**Comment by johnathon-walnut** [comment]
i can make it glow 😈

**Comment by canedoly** [comment]
yeah it will be p with glow

**Comment by johnathon-walnut** [comment]
Added, please test in actual match since I am tired and want to sleep but also wanted to get this done, it will glow if glow is on and the last two commits weren't tested at all tbh
