### ISSUE TITLE
(request)Followbot-Medic Followbot - Auto change weapons?

### ISSUE THREAD

**Issue by JDNA364PROC** [Fedoraware/Fedoraware#603]
i recently started using followbot a bit more often and i think this would be good (for medic) 

totally not stolen from lbox

**Comment by JDNA364PROC** [comment]
> @JDNA364PROC does it crash on you?

actually no it just works fine never had any problems with it like crashes

**Comment by N1kolasFlaV** [comment]
> > > @JDNA364PROC does it crash on you?
> > 
> > 
> > actually no it just works fine never had any problems with it like crashes
> 
> strange. I crash on the next match

I agree here.

**Comment by lnx00** [comment]
> Noticed more. After death, the followbot isnt reset. I think that's why it crashes

I'll look into that
