### ISSUE TITLE
DRAW PROJECTILE PATH 

### ISSUE THREAD

**Issue by Podssa** [Fedoraware/Fedoraware#604]
!!!!!!!!!!!!!

**Comment by canedoly** [comment]
you can enable it in visuals -> misc and its called "movement simulation lines"

**Comment by Podssa** [comment]
No thats called prediction path, projectile path shows where the rocket or the pill from grenade launcher will go

**Comment by Podssa** [comment]
Like nitro

**Comment by johnathon-walnut** [comment]
no
