### ISSUE TITLE
a bug and a suggestion

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#606]
so if you have backtrack and aim at backtrack enabled and you don't disable interpolation, backtrack completly stops working.
Custom yaw - so you can select from 180 to -180 degrees in anti aim (i would do that myself but i don't understand how new aa works)

**Comment by johnathon-walnut** [comment]
The bug is not real

**Comment by canedoly** [comment]
> The bug is not real

Wdym by that?

**Comment by johnathon-walnut** [comment]
not reproducable

**Comment by canedoly** [comment]
oh wait i meant if you don't disable interpolation

**Comment by johnathon-walnut** [comment]
Wait for latest build, will either fuck it up more or fix it, seems like it was only setting the tick count of the backtrack if interp was disabled

**Comment by johnathon-walnut** [comment]
Should be fixed, and I added your suggestion too

**Comment by johnathon-walnut** [comment]
https://user-images.githubusercontent.com/36936588/182692098-480f921a-2e4d-47a7-9ea9-baff1897d84f.mp4

(interp on)
