### ISSUE TITLE
(REQUEST) Legit Anti-Aim

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#609]
Had fun with LAA in csgo with free cheats figured it could work here,for some reason i tried creating a LAA in casual nothing seem to work but for whatever reason worked against the bots, Normal players could hit me just fine.

**Comment by xxmyn** [comment]
Hitboxes are large in tf2, very large, your server real is also slightly offset towards your fake, so having a small angle delta between sent fake and sent real angles is useless, you can just do fake forward, real backwards, and you will have 180 delta, as well as most classes having their heads hard to hit.

**Comment by yujispin990** [comment]
oh ok ill try and experiment with this,Thank you again.
