### ISSUE TITLE
another bugs and a suggestion

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#610]
My config:
[glitch.zip](https://github.com/Fedoraware/Fedoraware/files/9261376/glitch.zip)

So whenever i hold my triggerbot key and go up to a enemy they will flicker between backtrack chams position (video)
[hl2_3bo3c6cFL2.zip](https://github.com/Fedoraware/Fedoraware/files/9261389/hl2_3bo3c6cFL2.zip)
And sometimes backtrack just becomes weird and either does 4-20 dmg up close from a shotgun or doesn't even hit (the same config)

(Suggestion) Team based chams - And a var to switch between custom colour and team based chams colours

**Comment by johnathon-walnut** [comment]
This isn't really bug, more of a side effect of the way we're making the existing auto backstab work with backtrack

**Comment by johnathon-walnut** [comment]
Your config doesn't even have backtrack on?

**Comment by canedoly** [comment]
> Your config doesn't even have backtrack on?

yeah because at the time i had the config saved it was disabled, i mostly only use aim at backtrack with backtrack enabled, same with triggerbot. I can upload the updated config if it matters that much

**Comment by johnathon-walnut** [comment]
Backtrack doesn't apply with triggerbot (yet)

**Comment by canedoly** [comment]
> Backtrack doesn't apply with triggerbot (yet)

yeah ik, its that by triggerbot i meant auto backstab

**Comment by johnathon-walnut** [comment]
Regardless, I can't get it to do the 4-20 damage in testing with your config

**Comment by johnathon-walnut** [comment]
Your config also doesn't even have any triggerbot stuff configured at all

**Comment by canedoly** [comment]
> Your config also doesn't even have any triggerbot stuff configured at all

yeah sorry about that here's the updated one with all the changes that i didn't save
[glitch.zip](https://github.com/Fedoraware/Fedoraware/files/9262201/glitch.zip)
and for that low dmg shotgun shots
so i was playing soldier on 2fort and whenever i launched someone in the air i just use shotgun on them and when i try to shoot someone who's falling i'll miss due to aimbot aiming at the backtrack ghost forcing me to disable it

**Comment by johnathon-walnut** [comment]
Yeah I can't even play on a non local server with your config, I just crash :)

**Comment by canedoly** [comment]
> Yeah I can't even play on a non local server with your config, I just crash :)

I think its caused by me having a different version of fedoraware but I was on hvh.tf with normal fedoraware and I didn't crash

**Comment by johnathon-walnut** [comment]
No it's my fault (I am retarded)

**Comment by johnathon-walnut** [comment]
Man no offense, but your config is actually awful, I'm surprised you manage to hit any shots with projectiles

**Comment by canedoly** [comment]
> Man no offense, but your config is actually awful, I'm surprised you manage to hit any shots with projectiles

For me works completly fine I hit good airshots and overall hits most of the time

**Comment by johnathon-walnut** [comment]
Well I can't use this shit, but still can't someone "up close and in the air" with a shotgun to do low damage

**Comment by xxmyn** [comment]
the backtrack is really bad.
