### ISSUE TITLE
Fedoraware party networking

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#613]
Cant invite player with **tf_party_request_join_user** if enabled fedoraware party networking. Friend not in friends steam. we are f2p
My friend got in console next:
[partyclient] sendint request to cancel outgoing invite/incoming join request
![image](https://user-images.githubusercontent.com/105226646/183240260-7232f561-c75f-452c-b126-43a85646ac4a.png)

**Comment by lnx00** [comment]
Your friend needs Lmaobox or Cathook to be able to accept your join requests.

Also if he"s using Lmaobox, then your friend needs to enable the Lobby feature so your join request won't be declined.

**Comment by lnx00** [comment]
We tried and didn't get it to work.

**Comment by FFJ11** [comment]
You can't host bots with fedoraware, possibly raiders or cat bots

**Comment by lnx00** [comment]
> > We tried and didn't get it to work.
> 
> i noticed 1 thing when invite a not friend through the tf_party_request_join_use command, an avatar of him appears. There is a small connection

Yes, there is a shirt connection. But the other client instantly declines the join request.

**Comment by lnx00** [comment]
> By the way, I noticed infZ bots spamming Fedoraware in casual. They are real? Or is it a cathook?

Hmmm haven't seen any of those yet. But no, they are not affiliated with Fedoraware and do most likely no use Fedoraware.
