### ISSUE TITLE
Movement recorder

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#615]
New idea: Movement recorder

**Comment by lnx00** [comment]
What would you need this for?

**Comment by lnx00** [comment]
Yes, i know what you mean. But i don't see how this could ever be useful

**Comment by xxmyn** [comment]
TF2 is not a movement game, and fedoraware already offers enough movement options for you to do pretty much any jump you could want to (jumping from battlements to the 2fort bridge as any class is the most I can think of) for this to be useful, and as lnx already said, it won't be added purely to allow people to automate movement for botting.

**Comment by johnathon-walnut** [comment]
(most classes, u cant as heavy unless u use GRU and get whipped)
