### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by DEVILISHTUNE** [Fedoraware/Fedoraware#620]
People say they see flicking, is that the 'flick' command? with low fps? orrrr some other setting? bug??

**Comment by iamtheskidking** [comment]
iirc its 2 features in misc under taunt control. disable those 2 and it should be fixed

**Comment by johnathon-walnut** [comment]
Fast accel

**Comment by iamtheskidking** [comment]
thank you, johnathon-walnut
