### ISSUE TITLE
(SUPER REQUEST)crazy idea:)

### ISSUE THREAD

**Issue by bestcheater123** [Fedoraware/Fedoraware#621]
Add Fedoraware chatting online(in cheat) use party networking,very cool.

**Comment by johnathon-walnut** [comment]
How would this work and what would even be the point when you can just type through the party chat?

**Comment by bestcheater123** [comment]
no,i mean the "feature" for fware,it use fware network to chat betwen fware user

**Comment by xxmyn** [comment]
fware networking uses party chat, there is no external server.
