### ISSUE TITLE
Missing some things for World Chams

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#625]
Missing some things for World Chams:
- [ ] chams for NPCs, bombs
- [x] esp, chams, glow for small birthday ammo "ammopack_small_bday.mdl"
- [x] projectile chams of enemies only
- [x] esp chams, glow for dalokohs bar, fishcake, festive sandvich "plate_sandwich_xmas.mdl", robo-sandvich "plate_robo_sandwich.mdl"
- [ ] esp, chams, glow for ghostly Gargoyle Pickup, spellbooks and [Halloween Spells](https://wiki.teamfortress.com/wiki/Halloween_Spells)
- [ ] esp, chams, glow for [crumpkin](https://wiki.teamfortress.com/wiki/Halloween_pumpkin)
![image](https://user-images.githubusercontent.com/105226646/183624794-023b5abe-cbf8-435e-8279-42e05e2b0f36.png)
![image](https://user-images.githubusercontent.com/105226646/183627594-d9d92a13-f02f-4340-87d5-9a35c76897b5.png)

If it's possible add Health Chams for Players, Buildings, NPCs

**Comment by johnathon-walnut** [comment]
You can do projectile chams for enemies only already

**Comment by johnathon-walnut** [comment]
Centered lines?

**Comment by johnathon-walnut** [comment]
????? Wtf is "centered lines" in what context???

**Comment by johnathon-walnut** [comment]
????? I literally have no idea what you mean man, what line is to be centered, centered relative to what????

**Comment by johnathon-walnut** [comment]
WHAT LINES

**Comment by NotAnUser1** [comment]
I think you mean [these](https://wiki.teamfortress.com/wiki/Magic_spells) as halloween spells you linked arent really world items, but to add on to the list, [Crumpkins](https://wiki.teamfortress.com/wiki/Halloween_pumpkin), as they give crits alongside metal and ammo

**Comment by xxmyn** [comment]
tracer lines come from the bottom of the screen because they look trash coming from anywhere else, tbh, they look trash coming from the bottom too.

**Comment by johnathon-walnut** [comment]
i dont wanna add that
