### ISSUE TITLE
pls make a config apply pross tutorial 

### ISSUE THREAD

**Issue by PROBESTPRO** [Fedoraware/Fedoraware#626]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
Is pross an English word?

**Comment by PROBESTPRO** [comment]
o think its a word

pls help me

**Comment by lnx00** [comment]
???
