### ISSUE TITLE
3 glow styles (blur, stencil, fpstencil) for buildings and world

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#633]
I noticed that 3 glow styles (blur, stencil, fpstencil) are only available for players. For buildings and the world - no

**Comment by johnathon-walnut** [comment]
Doesn't it just apply globally to everything????

**Comment by xxmyn** [comment]
it does, as of now glow code is awful, might be better to remake it kind of

**Comment by johnathon-walnut** [comment]
Your chams are worse
