### ISSUE TITLE
Request: Unlag chams

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#634]
So uh Can you guys maybe add an accurate unlag? kinda like projectile prediction with chams and for the aimbot to shoot

**Comment by johnathon-walnut** [comment]
What is accurate unlag :trollface:

**Comment by FFJ11** [comment]
rijin accurate Unlag (fake lag correction)

**Comment by johnathon-walnut** [comment]
Example?

**Comment by FFJ11** [comment]
a cham that will render an unlagged player and the aimbot will try to shoot it rather than hitting the fake

**Comment by FFJ11** [comment]
pretty much most cheats goes up to 22 ticks

**Comment by johnathon-walnut** [comment]
And how does that work, how am I meant to add that

**Comment by FFJ11** [comment]
maybe add proj prediction to the aimbot and add a cham for it

**Comment by johnathon-walnut** [comment]
Dude what

**Comment by FFJ11** [comment]
https://www.youtube.com/watch?v=_bUf_OmySqU&t=41s

0:38

**Comment by FFJ11** [comment]
still dont get it?

**Comment by johnathon-walnut** [comment]
Ok I get what it is, why does this need to be a cham, what the FUCK does it have to do with projectile aimbot and how the fuck is this implemented.

**Comment by FFJ11** [comment]
projectile aimbot has player movement prediction maybe it can be use to unlag other hackers and make something for the aimbot to shoot it, like the aimbot aims at the last tick of backtrack

**Comment by johnathon-walnut** [comment]
Are you suggesting forward tracking? That's utterly retarded

**Comment by FFJ11** [comment]
lmao the cheat is a bit bad when it comes to fake lag hvh

**Comment by xxmyn** [comment]
> projectile aimbot has player movement prediction maybe it can be use to unlag other hackers and make something for the aimbot to shoot it, like the aimbot aims at the last tick of backtrack

you can't "unlag" players that are fakelagging, tf2 does not simulate every tick like csgo, if they are not sending packets, they are not being simulated.

too stupid, didn't understand; simulating fakelagging players won't do anything because the server doesn't simulate them, you would end up shooting air.

**Comment by xxmyn** [comment]
i thought i closed this
