### ISSUE TITLE
crash upon joining new game

### ISSUE THREAD

**Issue by KaholVEVO** [Fedoraware/Fedoraware#638]
**Fedoraware Version Date:**  
current version

## Config used:
https://files.catbox.moe/3sjz0c.fw

## Description:  
Joining a new game causes a crash (only when already in a map)

## Steps to reproduce:  
Join a game, requeue for a new match and load in.

**Comment by AlexFlipH1** [comment]
if you had followbot and have a bind thats record fix;stop fixes stuff it will crash but im not sure about this one im thinking its the tf2 problem not the cheat not sure

**Comment by KaholVEVO** [comment]
> 

i have neither

**Comment by lnx00** [comment]
Try disabling the Weather effect in `Visuals -> Misc -> Precipitation (Right Side)`
