### ISSUE TITLE
Whip Not Whipping Teammates.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#644]
Whipping Teammates is not working.

**Comment by Capybaron** [comment]
> Whipping Teammates is not working.

Make sure you have melee aimbot on

**Comment by yujispin990** [comment]
it is on, I whip enemies but not my allies.

**Comment by yujispin990** [comment]
> > Whipping Teammates is not working.
> 
> Make sure you have melee aimbot on


it is on, I whip enemies but not my allies.

**Comment by PashaGames** [comment]
> > > Whipping Teammates is not working.
> > 
> > 
> > Make sure you have melee aimbot on
> 
> it is on, I whip enemies but not my allies.

![image](https://user-images.githubusercontent.com/50240958/184501623-bff0912b-4b01-497e-82fa-73b1dea690f3.png)

**Comment by yujispin990** [comment]
> > > > Whipping Teammates is not working.
> > > 
> > > 
> > > Make sure you have melee aimbot on
> > 
> > 
> > it is on, I whip enemies but not my allies.
> 
> ![image](https://user-images.githubusercontent.com/50240958/184501623-bff0912b-4b01-497e-82fa-73b1dea690f3.png)

bruh, i'm not that dumb....

**Comment by johnathon-walnut** [comment]
It is broken

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/184852879-0cb0b67a-1673-4946-926e-42a2cd21e17e.png)
this didn't fix it?

**Comment by johnathon-walnut** [comment]
I dunno haven't tested I didn't see the commit
