### ISSUE TITLE
( REQUEST ) to make enemy look like this video

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#645]
it looks like a smoothed interpolation??? looks cartoonish and i like it.

https://www.youtube.com/watch?v=ruLecem1tW4

**Comment by xxmyn** [comment]
"smoothed smoothing" is what you just said

**Comment by yujispin990** [comment]
> "smoothed smoothing" is what you just said

ah sorry about that,but i wanted to know is it hard to make?
