### ISSUE TITLE
new suggestion for aa

### ISSUE THREAD

**Issue by IMTHECHEATER** [Fedoraware/Fedoraware#646]
suggestion:u can repeatedly swap a fake and real angle with a key bind
its nice for hvh!!!!
(also can u fix fakeangle chams?,no need to use custom chams like brick or flat or bla bla,...?)

**Comment by lnx00** [comment]
You can create custom AA with Lua.

**Comment by IMTHECHEATER** [comment]
Can you give me an example?(im retard)

**Comment by PashaGames** [comment]
> You can create custom AA with Lua.

i dont think there is an ability to set sendPacket variable from lua
