### ISSUE TITLE
can't see enemies on the radar, only medkits and ammo packs and it's really hard to find enemies without chams crashing my game sometimes

### ISSUE THREAD

**Issue by Dashie17** [Fedoraware/Fedoraware#653]

**Comment by xxmyn** [comment]
if chams is crashing your game you have a much bigger issue than radar.

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/184848677-91c7acfa-13c9-40e0-8f97-ba8bb539f897.png)

**Comment by Dashie17** [comment]
> ![image](https://user-images.githubusercontent.com/70382582/184848677-91c7acfa-13c9-40e0-8f97-ba8bb539f897.png)

yeah I don't have that xd, it just shows ammo and health kits as I stated

**Comment by Dashie17** [comment]
but oh well, I'll just deal with this

**Comment by xxmyn** [comment]
upload your config.
