### ISSUE TITLE
( Request ) Hit Chance For Projectiles.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#655]
IF its possible.

**Comment by HARrhhv2** [comment]
![image](https://user-images.githubusercontent.com/105882762/185034136-f52d37dd-ecd1-4f00-9230-87699baf61f8.png)

**Comment by johnathon-walnut** [comment]
Why would you even want this

**Comment by ShotgunFlamez** [comment]
To look more legit when killing ppl

**Comment by N1kolasFlaV** [comment]
bcz fed>rijin soon..
