### ISSUE TITLE
The Crit indicator

### ISSUE THREAD

**Issue by RobertKnowsWhat** [Fedoraware/Fedoraware#657]
Fedoraware that was updated a few hours ago I think

Basically I can't see the bucket increase, and sometimes it does but it just stays in the very same number ex. before>300, after>300

I just cant see it.

**Comment by HutchyBean** [comment]
This was not known!!!

**Comment by RobertKnowsWhat** [comment]
funny sarcasm but I just want it fixed

**Comment by HutchyBean** [comment]
Developers are not smart enough !!!!!

**Comment by Cossegosse** [comment]
human issue

**Comment by xxmyn** [comment]
duplicate of #545
