### ISSUE TITLE
Question. use For Bot Mod?

### ISSUE THREAD

**Issue by DEVILISHTUNE** [Fedoraware/Fedoraware#658]
I wanna just use this with friends now adays and that means using for bot overhaul mod, But since i open it, it lauches default tf2. I was wondering if there was a way to change what it opens/ Aka the launcher for the overhaul mod.

**Comment by xxmyn** [comment]
the fedoraware dll does not open tf2, if you're using fedoraloader and dont want it to launch tf2 then why are you using fedoraloader?

**Comment by DEVILISHTUNE** [comment]
I do use it with tf2. I just wanna goof around time to time
