### ISSUE TITLE
Contracker pose remover

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#659]
Add a contracker pose remover? I hate those snipers who use it

**Comment by FFJ11** [comment]
![image](https://user-images.githubusercontent.com/102504389/185359692-7725baa5-53d4-4dc7-9c1a-1c688842d004.png)

**Comment by xxmyn** [comment]
remove taunts.

**Comment by FFJ11** [comment]
That's not even a taunt

**Comment by FFJ11** [comment]
I checked all removals, nothing removed the pose

**Comment by xxmyn** [comment]
good point, guess I've just not seen it since I started using fware, I'll add it later ig.
