### ISSUE TITLE
( Request ) Anti Backtrack.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#661]
had a chance to use a certain other tf2 software that has anti backtrack,really awesome against those BS fake latency spy abusers.Could it be implemented into fware?

**Comment by johnathon-walnut** [comment]
how do you implement it

**Comment by yujispin990** [comment]
when i used it it only seems to be activated at a certain condition,im really not sure how it works but it does work,the spy i fought tried so hard to backstab my backtrack it was so fun looking him trying so hard.

**Comment by yujispin990** [comment]
oh and i was able to backtrack him though when we spy vs spy, i am really sorry if that sounds confusing if its stupid just close it sorry for being a bother.

**Comment by canedoly** [comment]
> how do you implement it

[this](https://www.unknowncheats.me/forum/1882684-post8.html) could help, but idk how it would work in tf2

**Comment by xxmyn** [comment]
no video, no cheat name, no explanation of the feature whatsoever...

**Comment by Capybaron** [comment]
that is impossible

**Comment by yujispin990** [comment]
> no video, no cheat name, no explanation of the feature whatsoever...

ah yes,i was afraid saying the cheat name was not allowed or frowned upon.

the cheat name is : Rijin V2

feature: i cannot explain fully but everytime im fighting the spy i mentioned whenever he shows up my character will get stuck for awhile then ill move like normal again there will be an indicator saying that anti backtrack is active, and i know he is trying to backstab my backtrack because he keeps following me from a far trying to hit something.Very few times he actually backstabs my backtrack but he really needs to get close i think.

side note; i noticed the person who made rijin is named senator? and coincidentally on @canedoly post about anti backtrack on of the person who posted a reply in that forum on that topic was also named senator. Might not be related but it could be,This is just a random information.

**Comment by yujispin990** [comment]
also i could not record since i am running tf2 at around 50 to 70 fps on low settings,when ever i tried to record casual gameplay its very laggy i could only record offline maps properly,very sorry.

**Comment by lnx00** [comment]
Are you sure that you're not confusing "Anti Backtrack" with "Anti Backstab"?

**Comment by johnathon-walnut** [comment]
No he means anti backtrack, it's a thing in rijin but idk what it does nor how it works

**Comment by imgladnotu** [comment]
> No he means anti backtrack, it's a thing in rijin but idk what it does nor how it works

fakelag if spy is near && fakelag if spy is holding knife

**Comment by yujispin990** [comment]
just tested this thing to see if its actually fakelag related,dont look like it though.its so fun 2 spy cheaters cant backstab running around xd.

**Comment by lnd1g0** [comment]
Anti backtrack is just another term for fakelag. Fakelag breaks lag compensation.

**Comment by yujispin990** [comment]
> Anti backtrack is just another term for fakelag. Fakelag breaks lag compensation.

after using only the antibacktrack for awhile maybe it is related to fakelag, funny enough somehow it works well literally every latency abusing spy i've had encountered had problems trying to backtrack me and I noticed after some short intervals of lag every time i come close towards a spy or an enemy in general, I noticed it even more after rocket jumping or sticky jumping somewhere where I just get stuck in the air on my screen for a very short while.

**Comment by imgladnotu** [comment]
> > Anti backtrack is just another term for fakelag. Fakelag breaks lag compensation.
> 
> after using only the antibacktrack for awhile maybe it is related to fakelag, funny enough somehow it works well literally every latency abusing spy i've had encountered had problems trying to backtrack me and I noticed after some short intervals of lag every time i come close towards a spy or an enemy in general, I noticed it even more after rocket jumping or sticky jumping somewhere where I just get stuck in the air on my screen for a very short while.

it literally is just fakelag if a spy is holding a knife and is within backtrack range
