### ISSUE TITLE
( Request ) Seperated FoV for Hitscan,Melee and Projectile aimbot

### ISSUE THREAD

**Issue by Tygo0** [Fedoraware/Fedoraware#662]
Different FoV for each aimbot would be nice so that i dont have to edit global aimbot FoV while playing.

**Comment by johnathon-walnut** [comment]
I literally removed this feature cos I don't like it

**Comment by Tygo0** [comment]
> I literally removed this feature cos I don't like it

you cant make it so you can enable/disable between global aimbot FoV and seperated FoV's?
