### ISSUE TITLE
Decent fakelag fix

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#663]
So by using G::ChokeMap and checking if the target chokes more than we want lets say 6 ticks, we just ignore him, until he hits below 6 ticks then we shoot. Its decent but better than nothing

**Comment by NitroTF2** [comment]
no?

**Comment by xxmyn** [comment]
this is a good idea, but a bad implementation :D

**Comment by xxmyn** [comment]
Hook fl_SimTime (whatever the netvar is), and when it changes, save a record for the player it changed on with relevant data (simtime, tickcount, bones, etc) and then target the most recent record within aimbot. (genius)
