### ISSUE TITLE
FIX autobackstab

### ISSUE THREAD

**Issue by sebbe1234e** [Fedoraware/Fedoraware#664]
hi i have big problem the autobackstab never works and fake latency

**Comment by tf2cheater2013** [comment]
dnc

**Comment by lnd1g0** [comment]
Remember that 3 conditions must be met for a successful backstab.
1) The spy must be standing behind the victim.
2) The spy must be aiming no more than 60 degrees away from the victim.
3) The spy must be facing approximately the same direction as the victim is facing; you can be as much as ~107.5 degrees off, but no more.

Currently, only 1) is being automated by fedoraware. You will need to aim manually if you want to backstab.

**Comment by Cossegosse** [comment]
you all have a uid issue, brain issue and cfg issue

**Comment by johnathon-walnut** [comment]
@Cossegosse please refrain from shitting up the issues with absolute nonsense. Ty

**Comment by Cossegosse** [comment]
@johnathon-walnut please stop saying I'm a racist just because you don't like black people

**Comment by johnathon-walnut** [comment]
womp womp
