### ISSUE TITLE
( Request ) Minimal Priority type player list.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#665]
same as lbox where its easier to target one person rather than having to switch ignore to all the other enemy.

**Comment by Eniac763** [comment]
adding on to this, it should highlight the targeted enemy with a different color making the target distinct.

**Comment by Cossegosse** [comment]
I disagree with this because ur uid is too high

**Comment by johnathon-walnut** [comment]
there are priorities already and i think its fine as is - you can set them to rage if you want it to target them first
