### ISSUE TITLE
Market Garden Melee To Early or Not Trying At All.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#666]
Have not used fedware in awhile when i tested market gardener the swing is still too early, when i disabled swing prediction its kinda buggy where sometimes it will swing and sometimes it'll just stop even though im right infront an enemy...

**Comment by yujispin990** [comment]
tested all methods plain smooth and silent also tested respect fov still the same.

**Comment by xxmyn** [comment]
dont care not fixing.

**Comment by lnd1g0** [comment]
https://tenor.com/view/issue-uid-gif-25725840
