### ISSUE TITLE
( request ) team based chams and highlight target

### ISSUE THREAD

**Issue by awesomegamer23** [Fedoraware/Fedoraware#668]
Ability to change enemy/teammate chams options to team red/team blu like esp option "Relative colours"
And ability to not highlight the target depending on a var

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/187142473-d6ceb733-cffc-4e32-81ae-b72cc71dec25.png)

looks like it already does that?

**Comment by awesomegamer23** [comment]
> ![image](https://user-images.githubusercontent.com/70382582/187142473-d6ceb733-cffc-4e32-81ae-b72cc71dec25.png)
> 
> looks like it already does that?

Yeah, but only with chams

**Comment by xxmyn** [comment]
hi mfed

**Comment by Capybaron** [comment]
fuck you mfed
