### ISSUE TITLE
what do i need to do to fix this? broken animations

### ISSUE THREAD

**Issue by notsonata** [Fedoraware/Fedoraware#671]
my animations are broken. this is the default config where nothing is enabled or disabled. what do i need to tweak? i've been trying to figure it out for about an hour now and i dont have a clue what to do. it wasn't like this about a week ago.

here is an imgur link of my game
https://imgur.com/a/u3DPruT

some help would be nice

**Comment by xxmyn** [comment]
lol

**Comment by notsonata** [comment]
what?

**Comment by xxmyn** [comment]
> what?

it's fixed, I forgot to check something while hooking FrameAdvance, but I liked the visual appearance, I've now fixed it.

**Comment by notsonata** [comment]
> > what?
> 
> it's fixed, I forgot to check something while hooking FrameAdvance, but I liked the visual appearance, I've now fixed it.

thank you.
