### ISSUE TITLE
Velocity spikes when unducking

### ISSUE THREAD

**Issue by lnd1g0** [Fedoraware/Fedoraware#673]
https://www.youtube.com/watch?v=UptIH7GxdJU
https://www.unknowncheats.me/forum/team-fortress-2-a/476571-velocity-spike-ducking-air-fix.html

pls fix

**Comment by johnathon-walnut** [comment]
Pretty sure we already implemented this

**Comment by johnathon-walnut** [comment]
https://github.com/Fedoraware/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/Hooks/Detours/C_BaseEntity_SetAbsVelocity.cpp

**Comment by johnathon-walnut** [comment]
Might have been the bug where trailing ?'s causes the sig to not be found

**Comment by lnd1g0** [comment]
![untitled](https://user-images.githubusercontent.com/112320081/187252536-cb94bc19-b297-4798-a05b-c3acd82d666a.png)

**Comment by johnathon-walnut** [comment]
signature not lost, just doesnt get found, try with latest commit

**Comment by xxmyn** [comment]
closing cause it's been a week...
