### ISSUE TITLE
fedoraware best fractal predictionage

### ISSUE THREAD

**Issue by lnd1g0** [Fedoraware/Fedoraware#674]
**Fedoraware Version Date:**  Aug 30 2022

## Config used:
https://cdn.discordapp.com/attachments/893000962220896286/1014091528479715338/semirage.fw

## Description:  
![image](https://user-images.githubusercontent.com/112320081/187390097-595edd11-e640-4f4c-8176-c2e06b659f50.png)

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. use config
2. shoot player
3. notice fractal

## Additional context 

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
wontfix

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/187392132-2c393492-d4ff-453a-a752-641afee4dfb0.png)

lol

**Comment by johnathon-walnut** [comment]
:trollface:

**Comment by Cossegosse** [comment]
cfg issue

**Comment by xxmyn** [comment]
https://cdn.discordapp.com/attachments/937420218672771115/1014121713262395442/image.png

should be fixed in upcoming commit friend!

**Comment by johnathon-walnut** [comment]
Wholesome wontfix issue fix
