### ISSUE TITLE
Projectile Aimbot Issue

### ISSUE THREAD

**Issue by lnd1g0** [Fedoraware/Fedoraware#676]
**Fedoraware Version Date:**  AUG 31 2022

## Config used:
https://cdn.discordapp.com/attachments/893000962220896286/1014091528479715338/semirage.fw

## Description:  
Proj Aimbot occasionally fires at crosshair position instead of at intended target. (Only noticed with stickybomb launcher, not sure if it happens for others)

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Equip stickybomb launcher
2. Use aimbot to shoot at target
3. While aimbot is still calculating, have the target disapear
4. Cheat fires at crosshair position instead

## Additional context 

I am not sure if the steps are accurate, this is merely speculation as to what is happening
- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
>cheat predicts it can hit player
>cheat starts firing delayed fire weapon
>conditions change
>cheat predicts it cannot hit player
>cheat stops firing delayed weapon
>weapon fires anyway

not sure how you'd propose a fix.

**Comment by xxmyn** [comment]
I like the quickswitch idea but it'd have to be an option cause otherwise people are gonna lose one target and switch to like their melee weapon or smthn.

**Comment by johnathon-walnut** [comment]
neither of those ideas are pleasant to me
