### ISSUE TITLE
Avoid random crits is not working??

### ISSUE THREAD

**Issue by alakazambun** [Fedoraware/Fedoraware#679]
https://streamable.com/dau5uj

**Comment by alakazambun** [comment]
Uhm no, I've tested it again, turned on indicators, so you can see when I'm pressing my crit key and when not. https://streamable.com/zmmfdj

**Comment by johnathon-walnut** [comment]
ok

**Comment by N1kolasFlaV** [comment]
Cant wait to see the tag "wont fix" :D

**Comment by lnx00** [comment]
It should work, but you'll still see fake crits when it tries to suppress a random crit.
