### ISSUE TITLE
uhhhh

### ISSUE THREAD

**Issue by PrinceInter** [Fedoraware/Fedoraware#680]
gyus please fix projectile aimbot and crit indicator!
![554794ae2ab4a835323c6299b1d5135f](https://user-images.githubusercontent.com/111026322/187966403-e264d0a6-4395-4573-b41a-54736c8edba2.png)

**Comment by N1kolasFlaV** [comment]
@xxmyn bro omg fix proj aim and crit indecatore u bed dev pastor...

**Comment by lnd1g0** [comment]
uid issue /closed
