### ISSUE TITLE
Fedoraware Self DDOS

### ISSUE THREAD

**Issue by watcha27** [Fedoraware/Fedoraware#681]
**Sep 1 2022**  

## Config used:
Doesnt Matter it ALWAYS HAPPENS
## Description:  
Self DDOS After Picking a Class

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error
join casual pick class
join casual
pick team
pick class.

1. Enable X
2. Do Y
3. Notice Z

## Additional context 
Video:https://cdn.discordapp.com/attachments/937420218672771115/1015808364837617704/Team_Fortress_2_2022.09.04_-_11.20.27.05.mp4

**Comment by xxmyn** [comment]
can't reproduce.
