### ISSUE TITLE
24 ticks or gay

### ISSUE THREAD

**Issue by 24ticksorgay** [Fedoraware/Fedoraware#682]
24 ticks or gay

**Comment by Capybaron** [comment]
shut up

**Comment by JDNA364PROC** [comment]
or pedo

**Comment by johnpablo1** [comment]
you can already do 24 ticks lol

**Comment by johnpablo1** [comment]
https://user-images.githubusercontent.com/106420166/188311443-51992858-7466-4645-bb30-a818154c171c.mp4

**Comment by JDNA364PROC** [comment]
> Untitled.video.-.Made.with.Clipchamp.mp4

holy shit

**Comment by JDNA364PROC** [comment]
is nice

**Comment by johnpablo1** [comment]
press the tab button to edit it to higher numbers

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/188311512-704fd9d2-3206-436e-8402-d13755ac87b6.png)
take note.

![image](https://user-images.githubusercontent.com/70382582/188311558-deaf1ef9-c826-4883-8413-83ba5c36afb2.png)
take note.

![image](https://user-images.githubusercontent.com/70382582/188311652-c984129b-c337-4f0e-9a33-72201e0aa53d.png)
take note.

![image](https://user-images.githubusercontent.com/70382582/188311921-491e4e8f-7a90-4d02-ba8e-d0b8d0fe6682.png)
take note.

**Comment by JDNA364PROC** [comment]
> press the tab button to edit it to higher numbers

def gonna try it
lol
