### ISSUE TITLE
dear developers....

### ISSUE THREAD

**Issue by PrinceInter** [Fedoraware/Fedoraware#683]
dear developesr...... fix your crithack ,projectile aimbot..... add fake real (real up fake forward....)
https://user-images.githubusercontent.com/111026322/188313575-bd4f17a8-91e3-46c3-9c3f-2acd86954be8.mov

**Comment by lnd1g0** [comment]
>real up fake forward

Ok buddy, just complete this form and we will consider it!
https://www.quizexpo.com/am-i-retarded-quiz/
