### ISSUE TITLE
no recoil or gay

### ISSUE THREAD

**Issue by 24ticksorgay** [Fedoraware/Fedoraware#686]
no recoil or gay

**Comment by JDNA364PROC** [comment]
xd

**Comment by JDNA364PROC** [comment]
yes 😳

**Comment by Capybaron** [comment]
theres no recoil tho

**Comment by JDNA364PROC** [comment]
where

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/188539883-6016a5ad-aa38-4200-8cc4-ce9f3a52801a.png)
visual

![image](https://user-images.githubusercontent.com/70382582/188539926-32d7d0eb-bd6d-42cb-ab06-b898674038db.png)
complete
