### ISSUE TITLE
healthpack/ammopack timers often get displaced

### ISSUE THREAD

**Issue by Capybaron** [Fedoraware/Fedoraware#694]
![image](https://user-images.githubusercontent.com/92531943/189543882-4bb4de51-62d1-421b-abd5-c5e4e7c73598.png)
WHY!!!

**Comment by lnx00** [comment]
Because we use the position of the player that picked up the ammo/medkit. If this player isn't standing exactly on the ammo/medkit or if their position isn't accurate (dormant ESP) then the timer will be displaced.
