### ISSUE TITLE
aimbot sometimes breaking the dt

### ISSUE THREAD

**Issue by JDNA364PROC** [Fedoraware/Fedoraware#695]
while using aimbot and dt with minigun (sometimes force-a-nature) the dt breaks/doesnt shoot more than 1 bullet (once again sometimes it shoots 2) 

config-https://www.mediafire.com/file/digbpcu79pnao7i/configggggggg.fw/file

my average ping is 30-60 and fps 200 it breaks even while playing with bots

**Comment by JDNA364PROC** [comment]
and yeah it works fine with manual aim

**Comment by 24ticksorgay** [comment]
or gay

**Comment by JDNA364PROC** [comment]
> or gay

meanwhile ishowspeed on avatar

**Comment by 24ticksorgay** [comment]
i love guys (gays)

**Comment by JDNA364PROC** [comment]
> i love guys (gays)

exposed

**Comment by 24ticksorgay** [comment]
> > i love guys (gays)
> 
> exposed

sex f

**Comment by N1kolasFlaV** [comment]
sounds like an issue with your uid.. tbh...

**Comment by tf2cheater2013** [comment]
why did you upload plain text to mediafire...

**Comment by lnd1g0** [comment]
Have you tried reinstalling windows? Deleting drivers? Disassembling your keyboard and eating it key by key? Mabye shove an entire mouse up your ass?

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/189599510-63e27126-6818-4745-9d64-163496ec9924.png)

seems like this could be your issue 🙄

**Comment by carvee** [comment]
get a better hack
