### ISSUE TITLE
[Suggestion]Visual(chams):D

### ISSUE THREAD

**Issue by IMTHECHEATER** [Fedoraware/Fedoraware#696]
Add Chams Alpha And Overlay chams alpha too so fware can be rijin free version :trollface: https://youtu.be/_bUf_OmySqU?t=398

**Comment by xxmyn** [comment]
already exists.

**Comment by IMTHECHEATER** [comment]
when dude,can u explain me lol(im dumb kek)

**Comment by xxmyn** [comment]
glow modifier or whatever it is in chams, and you can change the alpha of the chams material by selecting the colour, right clicking, and clicking show alpha bar.
