### ISSUE TITLE
Aimbot is kinda broken

### ISSUE THREAD

**Issue by IMTHECHEATER** [Fedoraware/Fedoraware#697]
## Config used rn:https://files.catbox.moe/kocryj.fw

https://files.catbox.moe/kocryj.fw

## Description: Cant Using Aimbot With DoubleTap 
https://streamable.com/vgmwt1

**Comment by xxmyn** [comment]
turn off flick at enemies.

**Comment by IMTHECHEATER** [comment]
doesnt work
:sad:

**Comment by xxmyn** [comment]
I was able to recreate the issue, but turning off flick at enemies fixed it for me, can you make another clip of this issue occurring?

**Comment by IMTHECHEATER** [comment]
https://streamable.com/nntm6w

**Comment by IMTHECHEATER** [comment]
where did you go @xxmyn

**Comment by xxmyn** [comment]
yh i have no idea whats causing it

**Comment by IMTHECHEATER** [comment]
when i disable "aimbot in last tick" dt working perfect with aimbot KEK
