### ISSUE TITLE
( REQUEST ) Fake Latency Syncing.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#699]
This feature is available in Rijin V2 and i love it,it syncs our current server ping to the desired fake latency ping that we chose in the software,fake latency is also disabled on weapons that do not have any use for backtrack. There is a feature in the software that disables fake latency immediately upon death which i think is useful in some cases. Hopefully this would be easy enough to be implemented.

**Comment by xxmyn** [comment]
im confused what your question is;
1- you want the scoreboard to show your chosen fake latency
2- you want fake latency in the cheat
3- you want fake latency to rcon into the server and apply and the same latency to everyone else connected to the server

**Comment by xxmyn** [comment]
fake latency should have no effect on weapons that don't use lag compensation, it's better to keep our fake latency so we don't have to ramp it up again when we switch weapons, and making it turn off on death should be easy.

**Comment by johnathon-walnut** [comment]
🤓

**Comment by carvee** [comment]
🤓

**Comment by lnx00** [comment]
You can already set your desired fake latency ping and reduce the ping shown in the scoreboard to a custom amount using "Ping Reducer".

**Comment by yujispin990** [comment]
Oh,i am very sorry i did not explain properly.For example, if i had a ping of 40 in the server and i chose 200 as my fake latency, it'll add that 40 ping i had onto the fake latency that i chose.Please correct me if i am wrong but whenever i used the software the fake latency itself will correct it self "continuously" to match my ping and the fake latency that i chose i forgot to screenshot because my sub ran out,and it has a panel that shows that our fake latency is fluctuating probably keep an effective backtrack latency? i apologize if what i am saying does not make sense.
