### ISSUE TITLE
old issue with backtrack

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#701]
So by having fps lower than 66 (idk actually) extends the backtrack weirdly and makes that not work. I had cl_updaterate 66 and cl_cmdrate 100, the effects of this is way worse on cl_updaterate 33 and cl_cmdrate 33/100 (i don't think cmdrate makes a big difference)

https://user-images.githubusercontent.com/81353241/189971485-745f111f-929e-438a-af22-4738185f9f66.mp4

Also this isn't local server only, this is the same with the normal servers aswell

**Comment by lnd1g0** [comment]
in what circumstance would anyone use cl_updaterate lower than 66? Can you test again with fps locked below 66?

**Comment by canedoly** [comment]
In the video i've locked the fps to 25 and it got way worse, and also i was using cl_updaterate 66 and cl_cmdrate 100

**Comment by xxmyn** [comment]
this is a much larger issue with how backtrack is done right now.

**Comment by carvee** [comment]
ok and

**Comment by xxmyn** [comment]
no longer an issue since im such a good coder.
