### ISSUE TITLE
[Request] Auto JumpBug

### ISSUE THREAD

**Issue by RodolfitoHZ** [Fedoraware/Fedoraware#702]
I think it would be very useful! :D

**Comment by xxmyn** [comment]
how

**Comment by RodolfitoHZ** [comment]
> how

I HAVE NO IDEA XD

seriously, if I knew programming I would do it myself, but since I don't know, I prefer to leave the work to those who know.

**Comment by lnd1g0** [comment]
[request] Add infinit amo and god moed!!!!! pls i no programer but if i know program i wil do myeself (i practic with scratch)

**Comment by lnd1g0** [comment]
> I think it would be very useful! :D

Jumpbugs dont exist in TF2.

**Comment by RodolfitoHZ** [comment]
> > I think it would be very useful! :D
> 
> Jumpbugs dont exist in TF2.

They exist, if you want you can search on youtube, there are several clips of people using them in matches. Heck, even I managed to do that a few times. Like, It's extremely difficult, but it's possible.

**Comment by Capybaron** [comment]
> > > I think it would be very useful! :D
> > 
> > Jumpbugs dont exist in TF2.
> 
> They exist, if you want you can search on youtube, there are several clips of people using them in matches. Heck, even I managed to do that a few times. Like, It's extremely difficult, but it's possible.

you say its extremely difficult and expect anyone to make it automatic and constant? nope sorry

**Comment by RodolfitoHZ** [comment]
> > > > I think it would be very useful! :D
> > > 
> > > 
> > > Jumpbugs dont exist in TF2.
> > 
> > 
> > They exist, if you want you can search on youtube, there are several clips of people using them in matches. Heck, even I managed to do that a few times. Like, It's extremely difficult, but it's possible.
> 
> you say its extremely difficult and expect anyone to make it automatic and constant? nope sorry

well, bhop is very difficult too, and they managed to implement an auto bhop. And so in my head I was thinking that it would be possible to create an Auto Jumpbug.

anyway, no one is obligated to spend their time on this, it's just something that would be really interesting to see :P

**Comment by xxmyn** [comment]
bhop is not difficult.

i've read about unducking if the distance between your bbox and the ground is less than 6 hammer units, but i dont know if it works, frankly, i dont see a feature like this working consistently, and i dont really care about adding it anyways, if you can convince indischizo that it's worth it he might try though :D
