### ISSUE TITLE
( IDEA ) Serverside Silent Aim.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#703]
Its just a suggestion, i do not know how difficult this is to be implemented or how it even works and again i got this idea from Rijin V2, now i really dont know if i am explaining the function correctly please correct me if i am wrong, i thought it might be when someone is spectating me it wont see that my aim is flicking everywhere.

**Comment by johnathon-walnut** [comment]
Only works on projectiles, already implemented

**Comment by lnd1g0** [comment]
> Its just a suggestion, i do not know how difficult this is to be implemented or how it even works and again i got this idea from Rijin V2, now i really dont know if i am explaining the function correctly please correct me if i am wrong, i thought it might be when someone is spectating me it wont see that my aim is flicking everywhere.

Sure buddy! Just complete this form and send the results here please!
https://www.quizexpo.com/am-i-retarded-quiz/

**Comment by thegamingboyftw** [comment]
@lnd1g0 
![image](https://user-images.githubusercontent.com/75171724/190395385-af99578b-05f8-4ee7-aa9e-ff71c0faae9b.png)
HAHAHAHAHAAHAHHAHAHAHAHAJHJKHAhkhjakhj;;';'';';l;fdsa

**Comment by carvee** [comment]
hi mfeddy

**Comment by johnathon-walnut** [comment]
![Screenshot_20220915-155122_Firefox](https://user-images.githubusercontent.com/36936588/190435988-e5b4d6c4-79b4-47d9-8016-cd12fa8cc40f.jpg)

**Comment by johnathon-walnut** [comment]
Feels good

**Comment by thegamingboyftw** [comment]
good job
