### ISSUE TITLE
auto vacc issues

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#704]
So, bullet resistance for snipers is too sensitive (make it only sensitive for players marked as cheaters and for legit players only if they're aiming close, and for heavy's i'm pretty sure there is a revved cond which should work better than slowed) and overall doesn't react to most hitscan weapons/weapons impacted by bullet resistance
Fire resistance doesn't work half the time and it doesn't work for dragon fury i think and doesn't react to flares
Blast resistance doesn't work, it doesn't even want to try predict rockets/pipes
Doesn't change resistance until you have atleast 1 charge
Doesn't change resistance instantly?
And overall it barely changes to a specific resistance (this is a reason you shouldn't paste from cathook)

I've came across these issues on a casual server 
this is my auto uber config
![hl2_uD4SZVXI48](https://user-images.githubusercontent.com/81353241/190606821-10eeb445-e7ef-4de4-8eaf-2814f1bce067.png)

**Comment by debugac** [comment]
broooo it takes one line to fix the autovacc for blast....
what da lnx doin

**Comment by xxmyn** [comment]
lnx has a life

**Comment by debugac** [comment]
> lnx has a life

"broooo it takes one line to fix the autovacc for blast...."

**Comment by johnathon-walnut** [comment]
If it's one line why not submit a quick PR ;)

**Comment by debugac** [comment]
kill urself

**Comment by drack887** [comment]
the last problem of fware if it is fixed, i will only use fware instead of lbox

**Comment by debugac** [comment]
`int BlastDangerValue(CBaseEntity* pPatient)
{
    bool hasRockets = false;

    for (const auto& pProjectile : g_EntityCache.GetGroup(EGroupType::WORLD_PROJECTILES))
    {
        if (pProjectile->GetVelocity().IsZero())
            continue;

        if (pProjectile->GetTouched()) // Ignore landed Stickies
            continue;

        if (pProjectile->GetTeamNum() == pPatient->GetTeamNum())
            continue;

        if (pProjectile->GetClassID() != ETFClassID::CTFProjectile_Rocket &&
            pProjectile->GetClassID() != ETFClassID::CTFGrenadePipebombProjectile)
            continue;

        // Projectile is getting closer
        Vec3 vPredicted = (pProjectile->GetAbsOrigin() + pProjectile->GetVelocity());
        if (pPatient->GetVecOrigin().DistToSqr(pProjectile->GetVecOrigin()) > pPatient->GetVecOrigin().
            DistToSqr(vPredicted) &&
            pPatient->GetVecOrigin().DistTo(vPredicted) < 200.f)
                         hasRockets = true; //WOW THIS WAS SO HARD TO FIX NGL.... THIS DOESNT FIX THE AUTOVACC 
        {
            if (pProjectile->IsCritBoosted()) { return 2; }
            hasRockets = true;
        }
    }

    if (hasRockets)
    {
        if (pPatient->GetHealth() < 80)
        {
            return 2;
        }
        return 1;
    }

    return 0;
}`

fixed blast no way....

**Comment by xxmyn** [comment]
> `int BlastDangerValue(CBaseEntity* pPatient) { bool hasRockets = false;
> 
> ```
> for (const auto& pProjectile : g_EntityCache.GetGroup(EGroupType::WORLD_PROJECTILES))
> {
>     if (pProjectile->GetVelocity().IsZero())
>         continue;
> 
>     if (pProjectile->GetTouched()) // Ignore landed Stickies
>         continue;
> 
>     if (pProjectile->GetTeamNum() == pPatient->GetTeamNum())
>         continue;
> 
>     if (pProjectile->GetClassID() != ETFClassID::CTFProjectile_Rocket &&
>         pProjectile->GetClassID() != ETFClassID::CTFGrenadePipebombProjectile)
>         continue;
> 
>     // Projectile is getting closer
>     Vec3 vPredicted = (pProjectile->GetAbsOrigin() + pProjectile->GetVelocity());
>     if (pPatient->GetVecOrigin().DistToSqr(pProjectile->GetVecOrigin()) > pPatient->GetVecOrigin().
>         DistToSqr(vPredicted) &&
>         pPatient->GetVecOrigin().DistTo(vPredicted) < 200.f)
>                      hasRockets = true; //WOW THIS WAS SO HARD TO FIX NGL.... THIS DOESNT FIX THE AUTOVACC 
>     {
>         if (pProjectile->IsCritBoosted()) { return 2; }
>         hasRockets = true;
>     }
> }
> 
> if (hasRockets)
> {
>     if (pPatient->GetHealth() < 80)
>     {
>         return 2;
>     }
>     return 1;
> }
> 
> return 0;
> ```
> 
> }`
> 
> fixed blast no way....

make a pr and ill merge it

**Comment by xxmyn** [comment]
alright i think this is done enough.
