### ISSUE TITLE
[Suggestion] Proper strafe prediction method

### ISSUE THREAD

**Issue by lnd1g0** [Fedoraware/Fedoraware#708]
Let x, y, and z be the 3-Dimensional coordinates of the target.
Let vₓ, vᵧ and v<sub>z</sub> be the x, y, and z velocities of the target.
Let γ, ϕ<sub>a</sub>,and ϕ<sub>2</sub> be the initial roll, pitch and yaw values respectively.
Let γ˙,ϕ˙<sub>a</sub>, and ϕ˙<sub>2</sub> be the angular roll velocity, angular pitch velocity and angular yaw velocity respectively.

Assuming that roll does not have an effect on the trajectory of the target, let γ = O and γ˙ = O, where O is a zero element.

If the player data at time instant t<sub>i</sub> and t<sub>i+1</sub> are known, the positions of the target is expanded using a second⁃order Taylor series at t<sub>i</sub> as

$X_{i+1}=X_i+V_iΔt+\frac{1}{2}A_iΔt^2$

where X<sub>i</sub> and X<sub>i+1</sub> are the position coordinates of the target at t<sub>i</sub> and t<sub>i+1</sub> ， respectively; V<sub>i</sub> is the velocities of the target at t<sub>i</sub> ； $Δt=t_{i+1}−t_i$ the difference between t<sub>i</sub> and t<sub>i+1</sub> ； A<sub>i</sub> the accelerations of the target at t<sub>i</sub> .

Further, it can be deduced that $A_i=\frac{2}{(Δt^2)}(x_{i+1}, x_i, V_iΔt)$. $A_i$ can also be expressed as $(\frac{d_{v_x}}{dt},\frac{d_{v_y}}{dt},\frac{d_{v_z}}{dt})$<sub>i</sub>. $(\frac{d_{v_x}}{dt},\frac{d_{v_y}}{dt},\frac{d_{v_z}}{dt})$ can be considered as a nonlinear function with respect to $(γ˙,ϕ_a,ϕ_2)$ at $t_i$, namely, $F_i(γ˙,ϕ_a,ϕ_2)= A_i - \frac{2}{Δt^2}(X_{i+1}-X_i-V_iΔt)$.

In order to solve $(γ˙,ϕ_a,ϕ_2)_i$, the problem is transformed into solving a ternary nonlinear equations as follows:

$F_{x i}(γ˙,ϕ_a,ϕ_2) = 0$
$F_{y i}(γ˙,ϕ_a,ϕ_2) = 0$
$F_{z i}(γ˙,ϕ_a,ϕ_2) = 0$

where γ˙ is a zero element, thus:

$F_{x i}(O,ϕ_a,ϕ_2) = 0$
$F_{y i}(O,ϕ_a,ϕ_2) = 0$
$F_{z i}(O,ϕ_a,ϕ_2) = 0$

The approximation of $(ϕ˙_a,ϕ˙_2)_i$ at $t_i$ can be evaluated by:

$(ϕ˙_a,ϕ˙_2)_i≈\frac{(ϕ_a,ϕ_2) _{i+1} - (ϕ_a,ϕ_2)_i}{(t) _{i-1} - t _i}$

From $(ϕ˙_a,ϕ˙_2)_i$ and $(ϕ_a,ϕ_2)_i$, $(ϕ_a, ϕ_2) _{i+N}$ can be calculated, where $N$ is defined as the amount of time requested to predict.

**Comment by Radeon0078** [comment]
i have no idea what the fuck this means

**Comment by lnd1g0** [comment]
> i have no idea what the fuck this means

step 1: put value in equation
step 2: get predicted pos
step 3: shoot at predicted pos

**Comment by imgladnotu** [comment]
this is why i shouldnt have slept through math class.

**Comment by xxmyn** [comment]
why?

**Comment by lnd1g0** [comment]
> why?

current strafe pred is shit

**Comment by xxmyn** [comment]
yes but this is useless.

**Comment by carvee** [comment]
indigo kill yourself 💯

**Comment by IMTHECHEATER** [comment]
my brain AGHHHH

**Comment by xxmyn** [comment]
this is retarded.
