### ISSUE TITLE
Rename cheat menu and chat prefix

### ISSUE THREAD

**Issue by kyrahm** [Fedoraware/Fedoraware#709]
What is the command to rename cheat menu and chat prefix?

**Comment by lnd1g0** [comment]
Hello I am 23 year man in bangladesh . I am coding an “counter strike global offensive “ cheat and need some help .

I already are using Osiris as a base but i wondering what crypto currencies mine most stealthy and most profit (unrelated)

I am saving the project as “cheat.Dll” as release x64 but how I put cheat in game? I drag cheat file onto desktop but it falls in recycle bin. how do run cheat menu in game?

Some other human said i need a “loader” but i already have windows 10.

Thanks 😊

**Comment by N1kolasFlaV** [comment]
Do you have Mental Retardation?

**Comment by johnathon-walnut** [comment]
Do you have Mental Retardation?

**Comment by xxmyn** [comment]
There is no command to change the prefix & it has to be changed by editing your config file.
![image](https://user-images.githubusercontent.com/70382582/191620493-c1b974e1-888e-4cee-905e-bedc5e8e2689.png)
