### ISSUE TITLE
dont wait for shoot and dt on heavy issue

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#710]
So by having dont wait for shoot **disabled** and dt'ing with heavy, makes you shoot only 2 bullets instead of 3-4 and maybe disable safe tick if plocal class is heavy

**Comment by xxmyn** [comment]
turn it on then

**Comment by Capybaron** [comment]
i nearly got hit by a car today

**Comment by canedoly** [comment]
> turn it on then

thank you
