### ISSUE TITLE
problems with bunnyhop as a scout

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#712]
## Description:  
when I try to do the bunnyhop with the scout it releases two jumps at once, making that when I try to jump again the jump doesn't come out, because with this bug it kind of deletes the second jump (I'm having this bug all the time)

## Steps to reproduce:  
turn on the bhop and jump constantly with the scout class 

## Additional context 
it gets in the way a bit in bho and when i try to do some jumps as a scout

**Comment by xxmyn** [comment]
fps issue

**Comment by Gught** [comment]
if you're experiencing fps problems, i would recommend you to use Vusaline as it helped me a lot so now i can run tf2 on almost ultra settings with fps around 100-400 (even tho i dont have GPU l0l)

**Comment by lnd1g0** [comment]
Vusaline breaks other cheats such as LMAOBOX.

**Comment by Gught** [comment]
> Vusaline breaks other cheats such as LMAOBOX.

Lbox works fine for me, idk how should it break Lmaobox, only problem I've noticed is if you run file_operations.bat game will crash as soon as you connect to any server
(Fixed by running revert_file_operations.bat)

**Comment by lGabryl** [comment]
> if you're experiencing fps problems, i would recommend you to use Vusaline as it helped me a lot so now i can run tf2 on almost ultra settings with fps around 100-400 (even tho i dont have GPU l0l)

how do i do it

**Comment by xxmyn** [comment]
this issue is solved and is entirely on your end, as other commenters said you can try to install a graphics config to increase your fps which may fix the issue.

if you are unsure how to install vusaline, just google it and the github rep will show up for it, it has an installer that walks you through setting it up.

**Comment by lnd1g0** [comment]
> ## Config used: https://files.catbox.moe/blug57.fw
> ## Description:
> when I try to do the bunnyhop with the scout it releases two jumps at once, making that when I try to jump again the jump doesn't come out, because with this bug it kind of deletes the second jump (I'm having this bug all the time)
> 
> ## Steps to reproduce:
> turn on the bhop and jump constantly with the scout class
> 
> ## Additional context
> it gets in the way a bit in bho and when i try to do some jumps as a scout

are you using default TF2 network settings?
