### ISSUE TITLE
Crit cheat does not work properly 

### ISSUE THREAD

**Issue by Wetchokomilklol** [Fedoraware/Fedoraware#715]
The crit hack is in beta yeah but for me it does not work for guns, only melee and sometimes the melee does not even work.
This bug is really dumb

**Comment by Wetchokomilklol** [comment]
If you could give an reasoning to this that would be great.

**Comment by carvee** [comment]
BRAIN ISSUE

**Comment by Wetchokomilklol** [comment]
Thanks that helped alot.
:D

**Comment by debugac** [comment]
carve ur a meanie

**Comment by Wetchokomilklol** [comment]
no but fr I need this

**Comment by lnx00** [comment]
it works

**Comment by xxmyn** [comment]
badass

**Comment by lnd1g0** [comment]
Sure buddy! We will fix this! Just complete this quiz and send us the results!
https://www.quizexpo.com/am-i-retarded-quiz/
