### ISSUE TITLE
[Suggestion] Anti OBS/Screenshot

### ISSUE THREAD

**Issue by shojimoji** [Fedoraware/Fedoraware#725]
I've been finding that fedoraware is better than any of the clients i have, its just that any i come across dont have anti OBS/Screenshot. Implementing this would be cool. Thanks!

**Comment by lnd1g0** [comment]
Why would a **free** cheat have a function intended for closet cheaters? No one in their right mind would use fedoraware as a closet cheat.

**Comment by xxmyn** [comment]
its not hard to add tbh might do it

**Comment by xxmyn** [comment]
![20220926102859_1](https://user-images.githubusercontent.com/70382582/192172977-05e71142-2694-410c-8a0d-740b7aded7da.jpg)
![hl2_XrC3r0LScc](https://user-images.githubusercontent.com/70382582/192173005-292c7d24-5af2-4a76-ad9c-12bdfbe1674f.jpg)

will push shortly.

**Comment by xxmyn** [comment]
ohh not adding anti-obs btw for the same reason indigo said
