### ISSUE TITLE
Doubletap problem [BUG]

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#734]
## Config used:
https://www.mediafire.com/file/yvln55q1uzxpz8h/scout_hvh.fw/file

## Description:  
My doubletap forces it to load all the time, so when I shoot or click the dash key it just doesn't work as it was supposed to, this makes it impossible for me to use doubletap

## Steps to reproduce:  
try using doubletap

**Comment by Gught** [comment]
I've noticed that this bug only happens when i die, and the only way to fix it is reinjecting the cheat. Sadly, i couldn't find what causes it, but its definitely some peace of code just constantly running the recharge function

**Comment by xxmyn** [comment]
I've no idea what this issue post is about, please record a video of the issue you're trying to describe.

**Comment by Gught** [comment]
> I've no idea what this issue post is about, please record a video of the issue you're trying to describe.

Whenever I respawn the recharge breaks

**https://imgur.com/a/L4dkQdd**

**Comment by Huj12345** [comment]
same problem.
