### ISSUE TITLE
Halloween suggestions

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#737]
Spell book world esp

Shoot pumpkin bomb if lethal, it works by checking enemy distance to the bomb, and if he's close & it does enough damage, shoot the pumpkin

**Comment by imgladnotu** [comment]
spell forcer

**Comment by canedoly** [comment]
> spell forcer

wasn't that patched?

**Comment by imgladnotu** [comment]
> > spell forcer
> 
> wasn't that patched?
> EDIT: It seems like it wasn't
> https://github.com/V alveSoftware/Source-1-Games/issues/3682

oh bollocks it already has a issue on the source1 bugtracker?

**Comment by xxmyn** [comment]
it's had an issue page since cathook added the feature.

**Comment by lnx00** [comment]
> Shoot pumpkin bomb if lethal, it works by checking enemy distance to the bomb, and if he's close & it does enough damage, shoot the pumpkin

I'm pretty sure someone added that a while ago

**Comment by canedoly** [comment]
> > Shoot pumpkin bomb if lethal, it works by checking enemy distance to the bomb, and if he's close & it does enough damage, shoot the pumpkin
> 
> I'm pretty sure someone added that a while ago

Yeah but I don't think it checks if its lethal, only if its close enough to do damage
