### ISSUE TITLE
cheat crashing on casual when ur joining from localserver

### ISSUE THREAD

**Issue by Huj12345** [Fedoraware/Fedoraware#741]
1. inject fedora into tf2
2. go on localsv (itemtest) 
3. find casual from localsv
4. crash

**Comment by canedoly** [comment]
I've joined my local item test server many times and found a casual game while in that same server and never crashed. You might wanna send your fedoraware config and maybe your dxlevel

**Comment by Huj12345** [comment]
https://anonfiles.com/K3c1mdBby3/se_fw

**Comment by lnx00** [comment]
I can confirm this issue with the given config.

The exception happens in datacache.dll (Access violation). The callstack entry related to fedoraware is:
https://github.com/Fedoraware/Fedoraware/blob/2b508fb529a09184a9050f2b24e8d5bea80be6e5/Fedoraware/TeamFortress2/TeamFortress2/Hooks/Detours/C_BaseAnimating_FrameAdvance.cpp#L18

**Comment by xxmyn** [comment]
how unusual, i'll do some ghetto thing to see if i can fix it...

**Comment by johnathon-walnut** [comment]
doesnt happen for me with that config

**Comment by Bathrobeuser** [comment]
sv_pure bypass?

**Comment by xxmyn** [comment]
Can't reproduce at all, even making sure that the code linked by lnx will run, closing bc stale, please open a new issue and follow the template if similar issue occurs.
