### ISSUE TITLE
Cheat crashing when making 2 Halloween contracts

### ISSUE THREAD

**Issue by Yumbos** [Fedoraware/Fedoraware#742]
**Fedoraware Version Date: Oct 4 2022**  

## Config used:
https://files.catbox.moe/01vjt7.fw 

## Description:  
Basically, when i complete a single contract, nothing happens, but the thing occurs when i finish a second contract, then when i complete that contract my entire contract hud gets bugged and if i claim the Halloween Package my game crashes. 

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error
I get this error whenever i follow the steps above.

**Comment by JDNA364PROC** [comment]
i keep crashing when i kill headless horseman so yeah

**Comment by rikagq** [comment]
Yeah i have the same problem, and it is annoying.
