### ISSUE TITLE
Cheat Projectile Aimbot

### ISSUE THREAD

**Issue by BoyBabaji** [Fedoraware/Fedoraware#743]
How do i fix projectile aimbot on fedoraware it wont aim to players but normal aimbot works

**Comment by frel0** [comment]
> h

he has no hitboxes for projectile aimbot selected

**Comment by Yumbos** [comment]
> To fix, just fill in this form: https://www.quizexpo.com/am-i-retarded-quiz/

bro i did that test and it's garbage man

**Comment by imgladnotu** [comment]
> > To fix, just fill in this form: https://www.quizexpo.com/am-i-retarded-quiz/
> 
> bro i did that test and it's garbage man

you actually fell for the bait.
l0l

**Comment by Yumbos** [comment]
> > > To fix, just fill in this form: https://www.quizexpo.com/am-i-retarded-quiz/
> > 
> > 
> > bro i did that test and it's garbage man
> 
> you actually fell for the bait. l0l

not really, i was just bored and did it

**Comment by xxmyn** [comment]
can't repro
