### ISSUE TITLE
[Solved] 

### ISSUE THREAD

**Issue by watcha27** [Fedoraware/Fedoraware#744]
**Fedoraware Version Date:**  
The Latest

## Config used:
None

## Description:  
i loaded up vac bypass and launched the game and i injected it (Ignore TLS Erase PE Headers)
cheat worked yesterday

## Steps to reproduce:  
Inject Fedoraware
Inject Fedoraware

## Additional context 
None

- [yes] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
if its solved you can close the issue.
