### ISSUE TITLE
aimbot broken if backtrack is off

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#745]
**Fedoraware Version Date:**  
latest

## Config used:
https://files.catbox.moe/ssd349.fw

## Description:  
aimbot broken if backtrack off

## Additional context 
https://youtu.be/EUOZUOIRh5w

**Comment by johnpablo1** [comment]
shit i forgot to write anything

**Comment by xxmyn** [comment]
is this with the main branch?

**Comment by johnpablo1** [comment]
nah just this one
