### ISSUE TITLE
bugs in staging backtrack branch

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#746]
In hitscan aimbot, disable every hitbox other than "head",
Use sniper rifle or ambassador, hold aimkey and it won't shoot.
Now when you add "body" to "Scan Hitboxes" it will shoot.
So weapons that can headshot will refuse to shoot at the head hitbox, for example unscoped sniper rifle shoots at the head but while scoped it doesn't
EDIT: It also happens with hunstman I have head hitbox on priority and it doesn't work

EDIT2: Smooth warp option works weirdly, it should work only when holding the key, and when you have like 5-8 ticks left you warp instantly the rest/rubberband

**Comment by xxmyn** [comment]
fixed the main issue of this so i will be closing it.

smooth warp rubberbanding at the end is smthn that I have no idea how to fix, I was thinking of streaming warp but I don't like it, might add it later though 🤷
