### ISSUE TITLE
EngineVGui Error

### ISSUE THREAD

**Issue by shojimoji** [Fedoraware/Fedoraware#755]
**Unknown, Cant get it from not showing up.**  

## Config used:
(https://files.catbox.moe/u39op9.fw)

## Description:  
Fedoraware won't open in tf2, and injecting fedoraware gives a error : EngineVGui.

## Steps to reproduce:  
- [ Use TFGhost V2, Launch tfghost, Inject fedoraware. TF2 Will open a new small window saying EngineVGui, With the top name saying Clinterfaces::Init() -> nullptr. Opening the actual tf2 window and press insert wont open the GUI.] I AM able to consistently reproduce this error

1. Launch TFGhost
2. Inject Fedoraware
3. Look at the second TF2 Window

## Additional context 

TFGhost ia an anti VAC ban launcher, dont know if that helps.
- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by cletusdavid** [comment]
Have you downloaded the latest build?

**Comment by shojimoji** [comment]
Thanks, didn't realize it updated.
