### ISSUE TITLE
Fedoraware Not Loading When Pressing INSERT

### ISSUE THREAD

**Issue by zipzoop24** [Fedoraware/Fedoraware#758]
Fedoraware Version Date: Latest as of 12:09 PM EST 15/10/22

##Config used:
No Config Used/Default(?)

##Description:
I downloaded Fedoraloader and tried to inject. It loaded Steam and TF2 just fine, and I saw the injection successful dialogue box, but when I press insert in-game nothing happens.

##Steps to reproduce:
    Download Fedoraloader
    Open and load Fedoraware
    Open TF2
    Press insert
    Nothing happens

##Steps to reproduce the behavior:
Same as steps to reproduce

##Additional context
No

**Comment by iloev** [comment]
did you install the "c++ runtimes" ?

**Comment by iloev** [comment]
if not, then i will give a link to a "all in one" version. https://github.com/abbodi1406/vcredist

**Comment by iloev** [comment]
also https://fedoraware.github.io/Docs/faq/

**Comment by zipzoop24** [comment]
Have all the requirements downloaded

**Comment by zipzoop24** [comment]
So after a couple more retries (as in, trying to load like 3 times) it finally loaded. This issue can be closed, but I did not find the cause. It worked again after the first time I managed to load it.

**Comment by xxmyn** [comment]
dont disable sound.
