### ISSUE TITLE
DLL Not working with new update. I have attempted to inject with my injector, nothing. Help?

### ISSUE THREAD

**Issue by r34325432543543543** [Fedoraware/Fedoraware#759]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
there's no info so how are we meant to help?
