### ISSUE TITLE
EXTREME Lagging When Viewing Enemies From a Distance/Higher Altitude(?), Auto Detonate Stickies and Auto Backstab Not Working

### ISSUE THREAD

**Issue by zipzoop24** [Fedoraware/Fedoraware#760]
**Fedoraware Version Date: Latest as of 14:11 EST 15/10/22, Fedoraloader**  

## Config used:
https://files.catbox.moe/5zs9tg.fw

## Description:  
Title, demos included. The moments when I stop is to configure some settings (such as turning rage on or off, increasing/decreasing range, etc) but it is not seen in the demos.

https://files.catbox.moe/d5a3bf.dem
https://files.catbox.moe/89i2lu.dem
https://files.catbox.moe/gougg3.dem

The lag seen in the demo is much worse in game. Game completely stutters and is unplayable until I look away.

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

Enable ESP (any type, any options, can't isolate what causes the lag)
Look at someone from a distance
LAG INTO THE SINGLE DIGITS

Enable Auto Detonate Stickies
Put Some Stickies Near an Enemy
Stickies Don't Explode

Enable Auto Backstab
Go to an Enemy's Back
Enemy Not Backstabbed

## Additional context 
- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
im not loading ur demos, can u record it with obs instead.

**Comment by zipzoop24** [comment]
> im not loading ur demos, can u record it with obs instead.

Unfortunate. It's too late for me at this moment to record new demos, so I will just do it tomorrow as soon as I can. I promise that these (especially the FPS/lag one) aren't miniscule problems.

**Comment by zipzoop24** [comment]
> im not loading ur demos, can u record it with obs instead.

I recorded new demos 
[demos.zip](https://github.com/Fedoraware/Fedoraware/files/9794727/demos.zip)

After testing, I finally understand what the problem is regarding the FPS bug. So as ANY PROJECTILE CLASS if you kill an enemy with YOUR PRIMARY and look at other enemies that are far away from you, you will lag. As stated before, it is much worse in-game and the demo can't record it. I won't lag when looking at enemies that are close to me, yet as soon as I look at enemies that are far away from me, the game lags more and more the farther away they are. I can "fix" this by switching weapons. However, as soon as I kill another enemy with my primary, the bug returns. The game ran perfectly fine until I killed someone. Hitscan classes do not seem to have this issue, as I kill people with my primary as Scout and Heavy and do not lag.

As seen in the other 2 demos, auto detonate and auto backstab don't seem to be working at all, no matter what settings I try to change.

**Comment by jailbaiting** [comment]
you fail to understand basic english, record videos, upload to youtube, streamable or another upload site and then you will probably have your issue solved.

**Comment by xxmyn** [comment]
im closing this issue as you attached more demos instead of recording an actual video.

**Comment by zipzoop24** [comment]
> im closing this issue as you attached more demos instead of recording an actual video.

Why record a video instead of a demo? So you can better understand what the lag looks like?
