### ISSUE TITLE
a simple question

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#762]
why when i try to use fedoraware with dxlevel 81 it gives me a warning that i have to increase to dxlevel 90 ?

(my computer is a complete garbage and i can only play with a nice fps in dxlevel 81, or i use dxlevel 90 in 144p)

**Comment by xxmyn** [comment]
fedoraware doesnt provide support for dxlevels below 90, that warning is just to stop people from posting about graphical issues that only occur because they are on a lower dxlevel.

**Comment by lGabryl** [comment]
> fedoraware doesnt provide support for dxlevels below 90, that warning is just to stop people from posting about graphical issues that only occur because they are on a lower dxlevel.

but does this affect some function of the hack making it unusable?

**Comment by xxmyn** [comment]
we dont know as we dont provide support for it, as well as other things like non windows 10 operating systems and duel injection.
