### ISSUE TITLE
Backtrack /w fakelatency misses

### ISSUE THREAD

**Issue by xxmyn** [Fedoraware/Fedoraware#768]
Fakelatency values > 200 miss consistently while backtrack mode is set to all (turning on tracers shows that it is actually firing at bt ticks).

video : go f_ck yourself
config : go f_ck yourself

who i want to fix this : anyone but me.

**Comment by johnathon-walnut** [comment]
wah

**Comment by hyperventilation** [comment]
suggestion: remove all

**Comment by lnx00** [comment]
i hope this isn't my fault

**Comment by xxmyn** [comment]
> i hope this isn't my fault

it's not i just never fixed it when i made new backtrack
