### ISSUE TITLE
Fedoraware disabling interpolation on injection even when i do not disable it (very scary, im also mercenary-teleportation-phobic)

### ISSUE THREAD

**Issue by iloev** [Fedoraware/Fedoraware#769]
**Fedoraware Version Date:** 
Newest one

## Description:  
i have merc-teleportation-phobia pls fix

## Steps to reproduce:  
Inject the cheat and join a casual server, you will notice how the models are moving

Just inject it lol, it will disable interp by default (idk why)

**Comment by xxmyn** [comment]
the cheat doesn't mess with interp at all if you have the option off, it's probably frame advance hook, i might disable it for players with the interp option off.
