### ISSUE TITLE
random crash occurring??

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#771]
Randomly crashes mid match

**Comment by xxmyn** [comment]
thanks for the info??

**Comment by johnathon-walnut** [comment]
It's cos of cheater detection

**Comment by FFJ11** [comment]
i turned it off but still crashing. Do i turn it off on the visuals and hvh? or both?

**Comment by xxmyn** [comment]
i cant recreate this at all, im not even sure if cheater detection is whats consistently causing it as it seems to be working fine for me all the time.

please upload your config @FFJ11 and I will try and debug it shortly.

**Comment by FFJ11** [comment]
I got it fixed i think i can close this issue now

**Comment by xxmyn** [comment]
i cant pinpoint what causes this at all so im gonna reopen it

**Comment by SylveonBottle** [comment]
been crashing a LOT lately.
Gonna be honest, I think it has something to do with a player. Either a cosmetic item or some kind of character in a player's name.

Was crashing restart after restart, but after the game went to map selection, I could join just fine. Almost as if said player left the game

**Comment by johnathon-walnut** [comment]
I got a consistent crash in one server with getweapontype in cheater detection, not sure if related. By the time I realised to check what weapon he was using I had already rejoined too many times lol

**Comment by johnathon-walnut** [comment]
when

**Comment by xxmyn** [comment]
So incredibly stale.
