### ISSUE TITLE
AimMethod = AimPosition?

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#777]
In Vars.h under `namespace Projectile`:

https://github.com/Fedoraware/Fedoraware/blob/ad725ec8baa98cd627abd72106c90e7fd3f3a0d8/Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h#L115-L116

However, in AimBotProjectile:

https://github.com/Fedoraware/Fedoraware/blob/ad725ec8baa98cd627abd72106c90e7fd3f3a0d8/Fedoraware/TeamFortress2/TeamFortress2/Features/Aimbot/AimbotProjectile/AimbotProjectile.cpp#L549

Sorry but like, am I just super high right now or could this cause any issues with aimMethod/aimPosition?

**Comment by xxmyn** [comment]
no, the naming of the local var is unusual but it wouldn't cause any issues with the algorithm.
