### ISSUE TITLE
Im new to projectile aimbot and i need help

### ISSUE THREAD

**Issue by ProjectileAimbotError404** [Fedoraware/Fedoraware#782]
**Fedoraware Version Date:27 OCT 2022**  

## Config used:
(https://cdn.discordapp.com/attachments/781968749099089960/1035010584070066196/unknown.png)

## Description:  
Whenever I use the projectile aimbot it only hits the target when im basically touching it,meaning i have to be very close,is there any settings i could use to make it work ?Also,this is my first time doing an issue and i hope i wrote everything correct

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error
I've had it happen multiple times

1.Put the same setting as in the config
2.go on tr_walkway_r2c
3.spawn bots
4.go soldier(direct hit)
5.Fire from far(not working)
6.Fire from up close(working)
7.Question reality
## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.
- [ ] I think i did everything correct

**Comment by drack887** [comment]
prediction time 0.1!!!!!!! WHY YOU USING THIS VALUE EZ

**Comment by hyperventilation** [comment]
that splash prediction op 🔥

**Comment by ProjectileAimbotError404** [comment]
> prediction time 0.1!!!!!!! WHY YOU USING THIS VALUE EZ

whay should i use instead ?

**Comment by johnathon-walnut** [comment]
higher it is, the further you can shoot from
