### ISSUE TITLE
improvement to swing prediction

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#784]
Idk how swing prediction currently works since I didn't look at it, but ik that it doesn't take into account enemy velocity
Would it be decent to atleast use simple linear extrapolation for the enemy player? Move sim would be an overkill imo

**Comment by xxmyn** [comment]
movesim for local player and for enemy seems like a great idea wdym

**Comment by canedoly** [comment]
> movesim for local player and for enemy seems like a great idea wdym

yeah it is, but wouldn't it be heavy on perfomance?

**Comment by xxmyn** [comment]
movesim runs every tick on every player already.

**Comment by canedoly** [comment]
> movesim runs every tick on every player already.

never knew, so ig move sim on enemy & local for swing pred could be added

**Comment by xxmyn** [comment]
> > movesim runs every tick on every player already.
> 
> never knew, so ig move sim on enemy & local for swing pred could be added

i will add it eventually.

**Comment by xxmyn** [comment]
will be committed shortly.
