### ISSUE TITLE
fake on shot pitch bug

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#785]
So when completly random legit players (most noticeable on heavy) shoot, they will flick to the sky.

**Comment by xxmyn** [comment]
can u upload a video

**Comment by cletusdavid** [comment]
Can confirm this happens too, they will snap while holding shoot button

**Comment by cletusdavid** [comment]
https://youtu.be/liXs2MHc68I

**Comment by xxmyn** [comment]
alright i think i might know what causes it, can you make them fire at a low angle and then a high angle and see if one of them causes it
