### ISSUE TITLE
Small bug with the flamethrower

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#792]
When I shoot with the flamethrower it flicks a lot in the enemy's view (my friend told me this was happening because I wasn't even noticing)

Config: https://www.mediafire.com/file/0oxqtqj7w9cgsxb/N.fw/file

**Comment by Podssa** [comment]
ok

**Comment by cletusdavid** [comment]
ok

**Comment by xxmyn** [comment]
are u aimbotting with the flame thrower or are you manually shooting with the flamethrower.

**Comment by lGabryl** [comment]
> are u aimbotting with the flame thrower or are you manually shooting with the flamethrower.

i was using aimbot

**Comment by xxmyn** [comment]
yeah the flamethrower doesn't have pSilent so ofc u flick.
