### ISSUE TITLE
VM Weapon gone

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#795]
![image](https://user-images.githubusercontent.com/102504389/198972463-84552bec-532d-45d9-b949-28f02edcf637.png)

Where is the Weapon why is it gone

**Comment by xxmyn** [comment]
ruh roh raggy, is vm chams on?

**Comment by FFJ11** [comment]
yep

**Comment by FFJ11** [comment]
i tried re-arranging the vm weapon to it's original for, still not there

**Comment by xxmyn** [comment]
whoopsie ill fix it eventually
