### ISSUE TITLE
Auto-Airblast too late to reflect Fast projectiles

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#799]
The auto airblast barely airblasts a direct hit or a flare

**Comment by johnathon-walnut** [comment]
What's your ping

**Comment by FFJ11** [comment]
Real ping goes up to 100-200

**Comment by FFJ11** [comment]
It didn't work, my real ping was 23-30+

**Comment by FFJ11** [comment]
my fps ranges to 30-90

**Comment by FFJ11** [comment]
fps is the problem?

**Comment by FFJ11** [comment]
![image](https://user-images.githubusercontent.com/102504389/199407481-3dff63f6-2abf-40e0-917d-f91772942504.png)

**Comment by johnathon-walnut** [comment]
hayai
