### ISSUE TITLE
AntiAim buggin my movement!

### ISSUE THREAD

**Issue by N1kolasFlaV** [Fedoraware/Fedoraware#800]
https://user-images.githubusercontent.com/106869594/199362009-70a826c0-9e6d-4110-9373-dd180dbfa71a.mp4

argh fix cant play medic

**Comment by cletusdavid** [comment]
just like, dont use anti aim?

**Comment by N1kolasFlaV** [comment]
ye and the snipers hs me 😠  nice iq..

**Comment by xxmyn** [comment]
follow the template next time.
