### ISSUE TITLE
Bug when I try to dash and shoot with the DT

### ISSUE THREAD

**Issue by Trafic0** [Fedoraware/Fedoraware#802]
sometimes when i shoot with the dt it just locks me where i am and just hits one shot, and with dash the same thing happens, and when I reload the dt it looks up real quick and comes back,

**Comment by JDNA364PROC** [comment]
22 ticks moment

**Comment by cletusdavid** [comment]
It's a known issue, happens with all cheats.

**Comment by Eniac763** [comment]
its because you have all dt conditions enabled, user issue.

**Comment by xxmyn** [comment]
Stale & No longer an issue in fedoraware.
