### ISSUE TITLE
fware is shit!!! menu not displaying on my phone

### ISSUE THREAD

**Issue by frel0** [Fedoraware/Fedoraware#803]
can you plsease stop using imgui im trying to play tf2 on my phone

@xxmyn @lnx00 @johnathon-walnut @tf2cheater2013

**Comment by imgladnotu** [comment]
> 
> can you plsease stop using imgui im trying to play tf2 on my phone
> 
> @xxmyn @lnx00 @johnathon-walnut @tf2cheater2013 

funnily enough, its probably possible if you backport fed to 2013 tf2 linux minus the windows-only libs
