### ISSUE TITLE
fix flamethrower 

### ISSUE THREAD

**Issue by vaitomanocucpp** [Fedoraware/Fedoraware#810]
my pyro cant the flickering anymore

**Comment by xxmyn** [comment]
are you using aimbot?

**Comment by cletusdavid** [comment]
"cant the flickering anymore"

**Comment by vaitomanocucpp** [comment]
> 

yes.

**Comment by xxmyn** [comment]
closing cause ur unhelpful and this is probably due to you using aimbot
