### ISSUE TITLE
Crithack Indicator based on Lmaobox's (Suggestion)

### ISSUE THREAD

**Issue by razerbignamer** [Fedoraware/Fedoraware#812]
## Suggestion:
Make a new crithack-indicator based on lmaobox ones, the current it's cool but it's visually sucks

**Demonstration**:
![indicatior](https://user-images.githubusercontent.com/66913721/201402957-b4495d25-eb1b-41f9-8f82-d9a5637568c6.png)
**Fully charged:**

![fully charge](https://user-images.githubusercontent.com/66913721/201403287-2b881e61-7102-41ab-90d7-9dd9db1bdacf.png)

**Comment by johnathon-walnut** [comment]
this crit hack indicator is based af

**Comment by Eniac763** [comment]
why not add da one from 2017 nullcore

**Comment by razerbignamer** [comment]
> this crit hack indicator is based af

agreed, is very neat

**Comment by vaitomanocucpp** [comment]
keep dreaming about that

**Comment by razerbignamer** [comment]
> keep dreaming about that

fodase preto

**Comment by vaitomanocucpp** [comment]
> > keep dreaming about that
> 
> fodase preto

ok free user

**Comment by vaitomanocucpp** [comment]
> > keep dreaming about that
> 
> fodase preto

beggar [pls-donate-scripts](https://github.com/razerbignamer/pls-donate-scripts)

**Comment by razerbignamer** [comment]
> > > keep dreaming about that
> > 
> > 
> > fodase preto
> 
> beggar [pls-donate-scripts](https://github.com/razerbignamer/pls-donate-scripts)

'beggar' é só um script pobre, alias acho que tu ta projetando free user 😂

**Comment by johnathon-walnut** [comment]
english on this repo only pls
