### ISSUE TITLE
weird issues

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#815]
By setting the fakelag to on key, and setting it to like 16 ticks
when you're not holding the key it will still choke 1 tick causing your aa to jitter and somehow this, fixes the rubberbanding on the smooth warp option.
This is the same when setting fakelag ticks to 1

**Comment by N1kolasFlaV** [comment]
me agree with da fl makes your AA jitterin, ples fix dis baanos.

**Comment by xxmyn** [comment]
Can't recreate the 1 tick choke or the aa jitter, or the rubberbanding.
