### ISSUE TITLE
the discord invite link is invalid

### ISSUE THREAD

**Issue by Capybaron** [Fedoraware/Fedoraware#817]
fix immediately

**Comment by Eniac763** [comment]
no

**Comment by johnathon-walnut** [comment]
You're probably just banned

**Comment by Capybaron** [comment]
> You're probably just banned

![image](https://user-images.githubusercontent.com/92531943/202211265-44531892-c286-4bfe-bc21-5f5b12a34ef8.png)

**Comment by lnx00** [comment]
It's valid

**Comment by xxmyn** [comment]
try again
