### ISSUE TITLE
(suggestion) aimbot shoot delay

### ISSUE THREAD

**Issue by drack887** [Fedoraware/Fedoraware#819]
why we need this?
when use DT with peaking, sometimes shoot too fastly (you will understand if you used lmaobox DT)

**Comment by xxmyn** [comment]
we need this feature because of an issue with lmaobox?

**Comment by drack887** [comment]
fware dt sometimes do same thing as lbox (sometimes pwing wall with peaking)

**Comment by N1kolasFlaV** [comment]
or when using auto peek.
