### ISSUE TITLE
nightly.link the fedora's hoster down

### ISSUE THREAD

**Issue by venasyon** [Fedoraware/Fedoraware#820]
**Fedoraware Version Date: [v1.6.2](https://github.com/lnx00/Fedoraloader/releases/tag/v1.6.2)**  
 ## Issue 
the link https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip cannot reachable.
Fedoraware users cannot download FW via FedoraLoader.

## Description:  
nightly.link, the host is probably down or cannot reachable locally.
45.32.185.199, the IP adress of nightly.link cannot reachable.

### Steps to reproduce the behavior:  

think about renew the link.

**Comment by venasyon** [comment]
## Update about Issue

The https://nightly.link/
cannot reachable via **Cloudflare Warp, Avira Phantom VPN, NordVPN or another Proxy- Virtual network bypass provider.**

https://nightly.link/ isnt respondin' to ping commands. 

FedoraLoader still having connection issues.

**Comment by venasyon** [comment]
## This is might be an solution.

the string, MainWindow.cs:14  
 public const string ACTION_URL = "https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip";

the link must be chanced to another alternatives like github's original hosting provider.

**Comment by johnathon-walnut** [comment]
If the website is down I don't think there's much you can do about it and there's no point changing the URL just because it's temporarily offline...

Is it a permanent shutdown?

**Comment by venasyon** [comment]
its probably not. but this isn't the first and won't be the last. think about change the provider

**Comment by johnathon-walnut** [comment]
To what lol?

**Comment by venasyon** [comment]
like github permanent links. 

https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files

**Comment by lnx00** [comment]
This is something completely different

**Comment by johnathon-walnut** [comment]
This doesn't give you the option to download the latest build artifact - you could use git cli but you still need to know the run ID for that

**Comment by lnx00** [comment]
Also you can't download artifacts without being logged in. That was the main reason to use nightly.link

**Comment by venasyon** [comment]
i used this link for my university project, i thought it would work but it isnt.

I'm sorry, I'm not as good a developer as you guys. sorry for time of waste

**Comment by johnathon-walnut** [comment]
??? If you know any alternatives to nightly that's good but otherwise this seems like an unnecessary issue that will probably be fixed in a few hours when it's back up

**Comment by johnathon-walnut** [comment]
@lnx00 I doubt you care for fw/loader any more but it might be worth re-using the locally downloaded DLL if it fails to get to nightly

**Comment by imgladnotu** [comment]
@johnathon-walnut @lnx00 i think its better for you guys to setup auto-releases per new successful compile job in github actions rather than relying on manual GH login -> actions tab/nightly.link doing it in behalf of the repository visitor

**Comment by lnx00** [comment]
nightly.link is up again
