### ISSUE TITLE
Choppy animations?

### ISSUE THREAD

**Issue by Robertnight** [Fedoraware/Fedoraware#829]
Fedoraware Version Date:
Latest

## Config used:
none/default

## Description:  
Player walk animations are choppy, as if they were played at 30 fps.

## Steps to reproduce:  
just inject the cheat

**Comment by stax132349** [comment]
disable interpolation in removals
![image](https://user-images.githubusercontent.com/90155114/203871989-c2bc4b71-332e-494d-8d14-21bbed32c678.png)

**Comment by Robertnight** [comment]
It's not added there by default.
Video (watch the red soldier): https://streamable.com/hs2jzj

**Comment by stax132349** [comment]
looks normal to me in that vid

**Comment by johnathon-walnut** [comment]
It's how they're supposed to be................... TF2 has been lying to you...........................................................

**Comment by Robertnight** [comment]
That's 100% not how it's supposed to be. Without the cheat, models update faster. With the cheat it looks like as if my game was running at 33 ticks.

**Comment by johnathon-walnut** [comment]
🤓

**Comment by Robertnight** [comment]
You can say, you can't fix it. Guess bad paste truly checks out?

**Comment by johnathon-walnut** [comment]
It's not a bug

**Comment by Robertnight** [comment]
so, the cheat literally makes animations bugged? cool lol

**Comment by HutchyBean** [comment]
You are a MORON!

**Comment by xxmyn** [comment]
> so, the cheat literally makes animations bugged? cool lol

those animations are more accurate to what the server sees, there is not currently a way to disable it but you dont have to anyway, it doesnt effect accuracy or anything.

**Comment by xxmyn** [comment]
https://github.com/Fedoraware/Fedoraware/tree/nonchoppy

there u go @Robertnight

**Comment by xxmyn** [comment]
> You can say, you can't fix it. Guess bad paste truly checks out?

i hope getting this non-issue changed for ur aesthetic pleasure is worth getting banned from the repo btw 😈
