### ISSUE TITLE
Fadeout Own Team Within FOV

### ISSUE THREAD

**Issue by SylveonBottle** [Fedoraware/Fedoraware#833]
Getting really fucking tired of trying to scope in on a tunnel/corner and my team starts blocking my field of view.
Fade own team is super OP, loving it, I just wish it would also fade teammates that are generally being really annoying and getting in the way as well even from a distance.

**Comment by xxmyn** [comment]
since you cant shoot through teammates, would it be better if they were only faded to like 25% opacity (or some amount near that) instead of becoming completely invisible?

**Comment by johnathon-walnut** [comment]
Sniper can shoot through teammates

**Comment by xxmyn** [comment]
oh well
