### ISSUE TITLE
Non-Relative Chams Colors (Team based chams)

### ISSUE THREAD

**Issue by Eniac763** [Fedoraware/Fedoraware#838]
Please add Non-Relative chams, I want chams to change colors based on team (RED and BLU) and not "teammate" and "enemies".

![20221129195333_1](https://user-images.githubusercontent.com/95100740/204681428-7dd6429d-cc2e-44ef-8d90-1d958acfc13b.jpg)

Here I am on RED team and the Enemy is BLU team, however there are only Enemies chams and Teammate chams, there aren't options for team based chams such as RED Team chams or BLU Team chams.

**Comment by johnathon-walnut** [comment]
Untick relative colours then

**Comment by xxmyn** [comment]
that's not what he was asking for, and to answer your question @Eniac763 no.

**Comment by johnathon-walnut** [comment]
> that's not what he was asking for, and to answer your question @Eniac763 no.

What

**Comment by johnathon-walnut** [comment]
> I want chams to change colours based on team

**Comment by xxmyn** [comment]
the chams dont use the relative team colours option iirc, they are just based on whether a player is on the enemy team or not

**Comment by Eniac763** [comment]
> the chams dont use the relative team colours option iirc, they are just based on whether a player is on the enemy team or not

yeap
