### ISSUE TITLE
[not a problem] Someone help me

### ISSUE THREAD

**Issue by lGabryl** [Fedoraware/Fedoraware#839]
Does anyone know any tips on how to start coding in c++ for beginners who don't know anything?

**Comment by Eniac763** [comment]
start with python then java then any other language. ¯\_(ツ)_/¯

**Comment by HutchyBean** [comment]
> Does anyone know any tips on how to start coding in c++ for beginners who don't know anything?

DO NOT START WITH PROJECT LIKE TF2 CHEAT !!!

**Comment by HutchyBean** [comment]
read a book or something
