### ISSUE TITLE
fedoraware crashing with new update

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#841]
**Fedoraware Version Date:**  
latest

## Description:  
i inject and it just crash!!

## Steps to reproduce the behavior:  
1. inject fedoraware
2. wait for a sec
3. cheat no load
4. crash game

**Comment by AXDWT** [comment]
missing out to kill people with cheats

**Comment by My-BallsItch** [comment]
I blame merasmus

**Comment by xxmyn** [comment]
i'll fix this with help from my best friend Cui Zongying

**Comment by N1kolasFlaV** [comment]
god bless baan :pray:

**Comment by jokiri** [comment]
**true**

**Comment by razerbignamer** [comment]
fed moment

**Comment by nullptrmachine** [comment]
esp, aimbot doesnt work what the fuck

**Comment by lnx00** [comment]
It should no longer be crashing now, but there are still bugs.

**Comment by vaitomanocucpp** [comment]
o k thank you Inx00 😄

**Comment by xxmyn** [comment]
Cui Zongying hacked lnx's computer and did all these crash fixed :D
