### ISSUE TITLE
uff ya p100 crash fix

### ISSUE THREAD

**Issue by IamIndeedGamingAsHardAsICan03489** [Fedoraware/Fedoraware#843]
new CreateTFRagdoll siggy
E8 ? ? ? ? 8B CB E8 ? ? ? ? 84 C0 74 66

**Comment by wolfsnipezz** [comment]
what?

**Comment by vaitomanocucpp** [comment]
impressive but if u pick a class u crash! :trollface:

**Comment by Dashiieee** [comment]
where do i put this lmao

**Comment by jailbaiting** [comment]
you put it in the DLL

**Comment by CardinalAquella** [comment]
E8 🤮

**Comment by vaitomanocucpp** [comment]
> where do i put this lmao

bro if u dont know a simple thing like where you should put that line
when he literally said where, please consider uninstaling life.
