### ISSUE TITLE
fix the crashing

### ISSUE THREAD

**Issue by Capybaron** [Fedoraware/Fedoraware#844]
baan do ya thang >:((( evil

**Comment by razerbignamer** [comment]
the download button dll is outdated tho

**Comment by nullptrmachine** [comment]
update C_BaseEntity_BaseInterpolatePart1

**Comment by johnathon-walnut** [comment]
it's not included in compilation not an issue

**Comment by Dashiieee** [comment]
it crashes when i shoot lmao

**Comment by johnathon-walnut** [comment]
> it crashes when i shoot lmao

u deserve it u nonce

**Comment by Dashiieee** [comment]
> > it crashes when i shoot lmao
> 
> u deserve it u nonce

bro has spongebob pfp and thinks he cold lmao so edgy

**Comment by jailbaiting** [comment]
> > > it crashes when i shoot lmao
> > 
> > 
> > u deserve it u nonce
> 
> bro has spongebob pfp and thinks he cold lmao so edgy

pony lover talking lawl get a grip with reality and realise u cant have sex with ponies in your mid 20s looza

**Comment by lnx00** [comment]
#841
