### ISSUE TITLE
config problem

### ISSUE THREAD

**Issue by YALLO99** [Fedoraware/Fedoraware#849]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by YALLO99** [comment]
hi config dosent work and not save after changes (happened after #909)

**Comment by AXDWT** [comment]
youre so stupid bruv
you just need to type a name for a config in the textbox press enter and it saves
same as visuals config
