### ISSUE TITLE
Cfg issue with anti aim

### ISSUE THREAD

**Issue by Bathrobeuser** [Fedoraware/Fedoraware#850]
**Fedoraware Version Date:**  

## Config used:

https://files.catbox.moe/3tdp01.fw <-- general , https://files.catbox.moe/6gh75x.fw <-- visuals

## Description:  

after using the config with anti aim the anti will start bugging : i cant jump , i can move but a litle while scoping i cant move and im getting stuck in place , resolver is fucked somehow , my visuals arent showing fake angles too 

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

move with the config for a while like max 10mins in anti aim 

## Additional context 

fake yaw: spin

**Comment by xxmyn** [comment]
took me 18 minutes to repro, is an issue with spin anti aim, the inability to jump is bhop.
