### ISSUE TITLE
Auto detonate is not working + a missing demoman sticky launcher

### ISSUE THREAD

**Issue by vaitomanocucpp** [Fedoraware/Fedoraware#851]
https://streamable.com/7aizat

**Comment by Eniac763** [comment]
plus glow esp for stickies not working, meaning u cant see where stickies are.

**Comment by vaitomanocucpp** [comment]
aim at stickes is also not workin :DD

**Comment by xxmyn** [comment]
whoops, this has also been fixed but i did not mean to mention it.
