### ISSUE TITLE
demoman primary weapon glow 

### ISSUE THREAD

**Issue by johnpablo1** [Fedoraware/Fedoraware#852]
## Config used:
https://files.catbox.moe/r19cw0.fw

## Description:  
it only works on demoman and his weapon (dont know if it is intentional or not)

## Additional context 
![image](https://user-images.githubusercontent.com/106420166/205474133-abcc4287-f275-417e-ba80-a146397a6f61.png)

**Comment by lnx00** [comment]
Should be fixed in a6a9c856d57fcb220bfe37dc54e8344f523c0849
