### ISSUE TITLE
auto backstab problem

### ISSUE THREAD

**Issue by Dashiieee** [Fedoraware/Fedoraware#853]
auto backstab doesnt work smh

**Comment by N1kolasFlaV** [comment]
fuck you, iq issue

**Comment by Capybaron** [comment]
> fuck you, iq issue

**Comment by Dashiieee** [comment]
> fuck you, iq issue

aww the little russian kid wants attention <3 hope your dad gets killed in ukraine

**Comment by Dashiieee** [comment]
> > fuck you, iq issue

bro has capybara pfp 💀

**Comment by johnathon-walnut** [comment]
> > fuck you, iq issue
> 
> aww the little russian kid wants attention <3 hope your dad gets killed in ukraine

I'm banning you from this repo
