### ISSUE TITLE
ban bypass

### ISSUE THREAD

**Issue by Mag0000004** [Fedoraware/Fedoraware#860]
is there any way i can bypass a ban on tf2? how can i join the community server again?

**Comment by lnx00** [comment]
no

**Comment by pay2lose** [comment]
alt

**Comment by Mag0000004** [comment]
> alt

my ip is banned, alts wont work. would appriciate help so i can hack on skial again

**Comment by Mag0000004** [comment]
> no

thanks for a very helpful answer

**Comment by pay2lose** [comment]
> > alt
> 
> my ip is banned, alts wont work. would appriciate help so i can hack on skial again

vpn

**Comment by johnathon-walnut** [comment]
You can't

**Comment by xxmyn** [comment]
ik this is locked but protip for everyone, dont cheat on tf2 community servers.
