### ISSUE TITLE
the seperated configs suck & dont work half the time

### ISSUE THREAD

**Issue by xxmyn** [Fedoraware/Fedoraware#861]
features r not grouped together properly (binds are saved outside of the visuals, if a feature has a bind it probably shouldn't be saved as visual at all).

some features are not saved or take multiple saves to save properly (idfk why).

**Comment by johnathon-walnut** [comment]
U r wrong

**Comment by hyperventilation** [comment]
anyway why wasnt the cheat renamed to walnutware

**Comment by SylveonBottle** [comment]
Kinda annoying now when I save my config I have to press like 3 more buttons just to switch to visual and save that too since I can't bother to know what gets saved to which

**Comment by xxmyn** [comment]
seems like non saving issues are mostly fixed, please update 2 month old pr's before merging them next time @johnathon-walnut  :DDDDDD
