### ISSUE TITLE
full AA on works on fakelag when low-end pc and high-end

### ISSUE THREAD

**Issue by jaaajjjjjjjjjjjjjjjjjjjj** [Fedoraware/Fedoraware#863]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
Nonsense issue, remake it properly
