### ISSUE TITLE
Loading a my regular config(not visuals) causes engis buildings to be placed behind my model

### ISSUE THREAD

**Issue by lemonHeart45** [Fedoraware/Fedoraware#864]
**Fedoraware Version Date:**  

## Config used:
https://files.catbox.moe/tj4wog.fw

## Description:  
whenever i load my regular config it causes the buildings i place to be placed behind myself. ive tried turning off all things that were turned on for the config and it still did not fix the issue

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable Hacks config
2. Play engineer and place a building
3. Notice it is placed behind yourself

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by lemonHeart45** [comment]
Not my biggest issue just annoying af

**Comment by lemonHeart45** [comment]
Sorry, i forgot to give it the bug tab (i am very new to github :(.    )

**Comment by lemonHeart45** [comment]
nevermind i fixed it (idk how i just turned on everything manually and it fixed it)

**Comment by xxmyn** [comment]
what a WACKY bug!
