### ISSUE TITLE
Backtrack sometimes doesn't backstab in the back and can you add the 1000 Backtrack back + Crit hack damage?

### ISSUE THREAD

**Issue by jaaajjjjjjjjjjjjjjjjjjjj** [Fedoraware/Fedoraware#866]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
no
