### ISSUE TITLE
Game keeps crashing when you join a new session with fedoraware

### ISSUE THREAD

**Issue by relixes** [Fedoraware/Fedoraware#868]
**Fedoraware Version Date:**  Fedoraloader 1.6.2

## Config used:
>
 https://files.catbox.moe/xshmyd.fw
Visual preset: https://files.catbox.moe/1hdlm4.fw

## Description:  
 Whenever I join another session with Fedoraware, my game keeps crashing for no reason and I have to restart.

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error
Yes

1. Launch tf2 and inject fedoraware
2. Load config and join session
3. When joining session, game becomes really laggy and crashes

## Additional context 

It works when you join a session with no config, but it also crashes when trying to join another session
[ ] I have included the steps to reproduce to the best I am able to share.

**Comment by Eniac763** [comment]
if you listen to weezer, you need to set your ingame res to1024x768 all settings low idiotican style!

**Comment by lnx00** [comment]
The config isn't crashing for me after joining a new game multiple times. Please attach your visual config too, since it is probably the cause.

**Comment by relixes** [comment]
@lnx00 Added.

**Comment by xxmyn** [comment]
Can't repro with visual & cheat config.
