### ISSUE TITLE
[Visuals] World modulation settings does not override properly 

### ISSUE THREAD

**Issue by harmonyzt** [Fedoraware/Fedoraware#869]
**Fedoraware Version Date: Latest Build (Tested at 23.12.2022)**  

## Description:  
A very uncostistent bug which can happen when you load a visual config when you already have loaded another one or you load an imported visual config with the game open which makes the world modulation settings not change either forever until you restart the game or change by loading a specific visual config.

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Load any visual config which does have custom world modulation settings 
2. Grab another visual config with different world modulation settings 
3. (Optional) Import one or a couple of new visual configs while the game is open (not sure if the game open has any impact)
4. Switch to one of the visual configs you have imported and notice world modulation settings stay the same as the previous one which was loaded.

## Additional context 
Live example can be seen at the last couple of visual configs made by MCPengu and ascendeds1on at [FVV](https://fedoraware.ncvisualsvault.cc/). Since these configs were loaded one by one, the world modulation settings remained on the visual config made by ascendeds1on from the previous one although having a complete set of its own world modulation settings. Including screenshots for the reference -
First (and probably the one which creates the issue) - [Image](https://fedoraware.ncvisualsvault.cc/media/showcase/gfbrokeup.png)
And the second one which "stole" the settings and did not override them by their own - [Image](https://fedoraware.ncvisualsvault.cc/media/showcase/ascended.png)

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
adding onto this that for me it sometimes breaks halfway through games, and wont work again until i change the colour.

**Comment by johnathon-walnut** [comment]
It's all my fault I'm sorry

**Comment by harmonyzt** [comment]
I guess it requires some kind of investigation to find out the exact problem
