### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by NaleC3D** [Fedoraware/Fedoraware#871]
**Fedoraware Version Date:*Last *  

## Description:  
<Always i inject the cheat in tf2 he crash, with no motive>

## Additional context 
One day i inject the cheat with Xenon and he crash tf2, i reset my pc, recompile, re dowload, every and he continue crash

**Comment by xxmyn** [comment]
stop using google translate to make github issues.

**Comment by lnx00** [comment]
Can't reproduce without config.

**Comment by NaleC3D** [comment]
Config Default

**Comment by xxmyn** [comment]
my game does not crash when i inject, closing (yes my game is a he)
