### ISSUE TITLE
duck jump

### ISSUE THREAD

**Issue by canedoly** [Fedoraware/Fedoraware#872]
Using duck jump doesn't gain you 6 additional velocity, because it crouches after jumping not before. Its explained [here](https://www.youtube.com/watch?v=7z_p_RqLhkA&ab_channel=shounic)

**Comment by xxmyn** [comment]
duck jump is designed to duck while you are in the air, not before, we could do this but it would add a delay to jumps, would be a seperate feature, and would have to be made to not work with bunnyhop

**Comment by canedoly** [comment]
Yeah, but can't you make it so that it crouches at the same tick when jumping or 1 tick before?

**Comment by xxmyn** [comment]
dont think so

**Comment by lnx00** [comment]
> dont think so

Lmaobox does it

**Comment by SylveonBottle** [comment]
```
alias +rj "spec_mode;-duck;+cr;alias checkrj +cr"
alias -rj "-cr;checkduck;alias checkrj none"
alias +crouch "-cr;+duck;alias checkduck +duck"
alias -crouch "-duck;checkrj;alias checkduck none"
alias checkduck none
alias checkrj none
alias +cr "+jump; wait 8 ; +duck"
alias -cr "-duck ; -jump"
alias none ""
bind space +rj
bind ctrl +crouch
```

Use with `sv_allow_wait 1`

**Comment by jailbaiting** [comment]
holy dude u are really needing that 6 extra velo, from the max 400 that the scout can do?

**Comment by xxmyn** [comment]
after testing this once for 1 second with cl_showpos, having duckjump on already gives you the 6 velocity boost, so im closing this as done :D
