### ISSUE TITLE
Fix backtrack

### ISSUE THREAD

**Issue by Trafic0** [Fedoraware/Fedoraware#874]
Fix backtrack for super funny spy gameplays 

### **PLEASE**

**Comment by danfanofdead** [comment]
spy backtrack +auto backstab = nothing.

**Comment by razerbignamer** [comment]
the backtrack has been broken for like fucking months

**Comment by Eniac763** [comment]
mfed is currently pregnant and sadly cannot do anything at this time, please wait.

**Comment by lnx00** [comment]
#768
