### ISSUE TITLE
Auto-Retain recharges while using smooth teleport.

### ISSUE THREAD

**Issue by danfanofdead** [Fedoraware/Fedoraware#875]
tickbase makes you press the teleport button twice before you fully teleported
Dm me on discord ig I can't paste my cfg here LolTrolledlmao#3217

**Comment by danfanofdead** [comment]
This only happens when you disable DT

**Comment by yesyes786** [comment]
buy rijin easy fix

**Comment by xxmyn** [comment]
turn off smooth teleport or auto-retain (not sure why you have it on considering you aren't using doubletap)
