### ISSUE TITLE
Edge Jump Always On Eats Scouts Double Jump

### ISSUE THREAD

**Issue by xxmyn** [Fedoraware/Fedoraware#878]
By setting edge jump to always on, scout will no longer be able to double jump.

**Comment by N1kolasFlaV** [comment]
now you know wtf..

**Comment by lnx00** [comment]
lmao i hate this cheat

**Comment by johnathon-walnut** [comment]
> By setting edge jump to always on, scout will no longer be able to double jump.

why

**Comment by xxmyn** [comment]
> > By setting edge jump to always on, scout will no longer be able to double jump.
> 
> why

because old ground flag was > 0, and current ground flag is not, so it jumps twice.
