### ISSUE TITLE
Visual Settings from One Config Editing Visual Settings for Another Config

### ISSUE THREAD

**Issue by 91jtezckYoKAoR8GTp6O** [Fedoraware/Fedoraware#884]
**Fedoraware Version Date:** 01.01.2023 

## Config used:

 https://files.catbox.moe/9wm32m.fw
			  https://files.catbox.moe/32oiom.fw
			  https://files.catbox.moe/o2brqp.fw
			  https://files.catbox.moe/owczmj.fw
			  https://files.catbox.moe/q488tn.fw

## Description:  

Whenever I change visual settings in one config, they automatically reproduce themselves onto other configs.

Ex: Enable World ESP in Config 1, go to Config 2 (which does not have World ESP enabled) and see that Config 2 now also has World ESP enabled.

## Steps to reproduce:  
- I am able to consistently reproduce this error

1. Load any config
2. Make sure that configs have different visual settings enabled
3. Change any option in the visual tab in one config
4. Go to a different config
5. See those changes applied in the different config too

## Additional context 

Video: https://www.vidlii.com/watch?v=TwimABcbftR
(Yes I know the quality sucks but you can still see the checkmarks)

- I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
either config 2 doesnt have that in the actual config or it's not loading world esp stuff properly

**Comment by 91jtezckYoKAoR8GTp6O** [comment]
> either config 2 doesnt have that in the actual config or it's not loading world esp stuff properly

Me mentioning World ESP was just as an example. Any option under the visual section can be used. In the video I used various ESP options for demonstration. The point is that a hypothetical Config 1 should have visual configuration XYZ and a hypothetical Config 2 should have visual configuration ABC. However, in practice, what ends up happening is that Config 2 adopts whatever options are chosen for Config 1 (in this case XYZ.) In the video the "no cheat" config doesn't have any ESP options enabled whilst the "scout" config also doesn't. When I enable any ESP options for "no cheat" those same options replicate themselves for the "scout" config (where previously it was shown that no options were enabled.)

**Comment by xxmyn** [comment]
Can't reproduce.
