### ISSUE TITLE
Inject error

### ISSUE THREAD

**Issue by winzys1** [Fedoraware/Fedoraware#885]
How to fix it?
![image](https://user-images.githubusercontent.com/121810977/210245156-82ad88f7-dd5b-47d0-b8a3-fa3fce1353e6.png)

**Comment by HutchyBean** [comment]
Are you using latest commit?

**Comment by winzys1** [comment]
Never mind i fixed this. I just dowload up to date version

**Comment by HutchyBean** [comment]
🤌🤌🤌🤌
