### ISSUE TITLE
(suggestion) add more things like 

### ISSUE THREAD

**Issue by zlobens** [Fedoraware/Fedoraware#895]
setcvar command to allow you to force any variables
like Lithium sticky launcher spam
..................
happy new year

**Comment by johnathon-walnut** [comment]
We already have that lol

**Comment by zlobens** [comment]
for real?
teach me master
I couldn't find anything about it in the fedora docs

**Comment by johnathon-walnut** [comment]
U can do setcvar <cvar name> <value> in console
And baan added sticky launcher spam to Misc I believe

**Comment by BLS01** [comment]
Sticky Spam its located at Misc.
