### ISSUE TITLE
Heya, when I queue on casual I crash and Competitive

### ISSUE THREAD

**Issue by jaaajjjjjjjjjjjjjjjjjjjj** [Fedoraware/Fedoraware#899]
**Fedoraware Version Date:**  

## Config used: sniper.fw

 https://files.catbox.moe/knycr1.fw

## Description:  

I crash on casual on load + It wont let me party
## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by jaaajjjjjjjjjjjjjjjjjjjj** [comment]
rarely competitive

**Comment by xxmyn** [comment]
Closing due to age and the fact that I queue perfectly fine. Instead of commenting here please open a new issue and follow the template correctly.
