### ISSUE TITLE
old proj aim

### ISSUE THREAD

**Issue by cheeseliker42** [Fedoraware/Fedoraware#900]
new one is  shit old one was better

**Comment by ieatshitforfun** [comment]
fr

**Comment by frel0** [comment]
they wont do shit about it soo... it takes like 30 seconds but idk why wont they do it

**Comment by N1kolasFlaV** [comment]
that is a very true and i

**Comment by xxmyn** [comment]
mfed pushed the fix for it against my wishes (so sad)
