### ISSUE TITLE
Projectile aimbot timing issues

### ISSUE THREAD

**Issue by titaniummachine1** [Fedoraware/Fedoraware#901]
[[

**Fedoraware Version Date:**  

## Description:  

projectile aimbot is shooting slightly further into futhere then enemy sis going so it shoots slightly further then he would go.
## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

use projectiles

enable projectile aimbot and use it.

## Additional context 

how to fix 
bugged: https://imgur.com/gallery/bv5jK6b
fixed: https://imgur.com/gallery/ZddIa7U
- [x] I have included the steps to reproduce to the best I am able to share.
https://www.youtube.com/watch?v=n4F5t8cxrdE

**Comment by vactrain** [comment]
![изображение](https://user-images.githubusercontent.com/122169199/211185287-f7e522f9-7fc4-40f4-8f70-d7ce3bbd954b.png)

are you fucking stupid, right?
disable your fakelag, thats all.

**Comment by danfanofdead** [comment]
> 

still sucks tho

**Comment by xxmyn** [comment]
its an issue with fakelag on walkway and doesn't occur outside of the map / without the feature.
