### ISSUE TITLE
Failed to download latest build because something machine refused connection nightly link blah blah

### ISSUE THREAD

**Issue by RobertoManiac** [Fedoraware/Fedoraware#902]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by stax132349** [comment]
1. This should go on the FedoraLoader github
2. This is literally because nightly.link is down
3. Wait

**Comment by RobertoManiac** [comment]
cool

**Comment by vactrain** [comment]
just compile it by yourself

**Comment by xxmyn** [comment]
you can download the artifact manually if required.

**Comment by creepergoku** [comment]
how to download artifact manually
