### ISSUE TITLE
Anti-aim reveals real yaw

### ISSUE THREAD

**Issue by TheGameEnhancer2004** [Fedoraware/Fedoraware#910]
Whenever i shoot with fakelag and anti aim enabled, fake yaw aa stops working. 
I will appreciate it, if someone fix this bug. I got tired of getting killed by bots

**Video [example](https://imgur.com/a/lSEz6Wf)** (**Fakelag value set to 1**)

**Video [example](https://imgur.com/a/tjhVsOJ)** (**Fakelag adaptive mode**)

[**Config**](https://files.catbox.moe/tcarsi.fw)

**Pitch:** fake down
**Real yaw:** spin (Speed: 8.2)
**Fake yaw:** forward

**Comment by canedoly** [comment]
Can you try without fakelag?

**Comment by Gught** [comment]
It works fine without fakelag, but smooth teleport jitters a lot without fakelag value set to 1

**Comment by xxmyn** [comment]
I'm not sure what I'm supposed to see in those videos, after you shoot with fakelag enabled it should keep showing your shooting angles until you leave your choke cycle though, it's not your "real" angle, just the angle that you shot at, I could set it to end your choke cycle once you are able send angles again which is 15ms after you fired, but I feel that would make you more likely to be shot.
