### ISSUE TITLE
(Suggestion) Bring back old smooth teleport 

### ISSUE THREAD

**Issue by Derpfaceking** [Fedoraware/Fedoraware#912]
holding down teleport key would teleport while key is being held and would allow you to use as much of your shifted ticks as you wanted and was very very useful for legit (not really legit) spy configs

**Comment by cheeseliker42** [comment]
shut the fuck up

**Comment by cheeseliker42** [comment]
close this fucking suggestion

**Comment by cheeseliker42** [comment]
lnx stop editing my massages ty
