### ISSUE TITLE
Backtrack + autobackstab issue

### ISSUE THREAD

**Issue by Spunky4552** [Fedoraware/Fedoraware#920]
Auto Backstab doesnt work when i enable backtrack on.

**Comment by cheeseliker42** [comment]
Nigga thats never gonna get added/fixed so stop arguing about it dumbass.

**Comment by Gught** [comment]
> Nigga thats never gonna get added/fixed so stop arguing about it dumbass.

Please, good sir, you are making me upset with your choice of words!
 I kindly ask you to stop swearing on these github users, since it is against [**GitHub Community Guidelines**](https://docs.github.com/articles/github-community-guidelines) .

**Comment by cheeseliker42** [comment]
SHUT THE FUCK UP DUMBASS

**Comment by lnx00** [comment]
#768
