### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by lordraiden23** [Fedoraware/Fedoraware#927]
You must work on cs go fedorware version :D
Would definitely buy or donate hehe

**Comment by cheeseliker42** [comment]
shit well never happen

**Comment by cheeseliker42** [comment]
make it yourself

**Comment by cheeseliker42** [comment]
f4g

**Comment by lordraiden23** [comment]
dafuq why so rude? 
Ok np.
 Z operation will take ya'll down ;)

**Comment by johnathon-walnut** [comment]
Fedoraware for CS:GO is not planned

**Comment by cheeseliker42** [comment]
never has been

**Comment by lordraiden23** [comment]
oh okay, didnt know. then I am sorry for disturbing, 
bombs are canceled. 
good luck in tf2, cool game tho :D

**Comment by lnx00** [comment]
Isn't Osiris basically Fedoraware for CSGO?
