### ISSUE TITLE
incorrect demoman info

### ISSUE THREAD

**Issue by faoktjba42laf** [Fedoraware/Fedoraware#930]
float CTFPipebombLauncher::GetProjectileSpeed( void )
{
	float flForwardSpeed = RemapValClamped( ( gpGlobals->curtime - m_flChargeBeginTime ),
		0.0f,
		GetChargeMaxTime(),
		TF_PIPEBOMB_MIN_CHARGE_VEL,
		TF_PIPEBOMB_MAX_CHARGE_VEL );

	return flForwardSpeed;
}

https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_pipebomblauncher.cpp // the function above me

#define TF_PIPEBOMB_MAX_CHARGE_TIME	 4.0f  // (his is for normal stickies obv, otherwise it's 1.2 for quickie
// hard code these eventually
#define TF_PIPEBOMB_MIN_CHARGE_VEL 900 // wiki lies?
#define TF_PIPEBOMB_MAX_CHARGE_VEL 2400 // wiki lies?

https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_grenade_pipebomb.cpp // this also could be used for sticky trajectory 

https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_pipebomblauncher.h // speed and max charge. 

#define TF_WEAPON_PIPEBOMB_GRAVITY		0.5f //unsure if it effects charge.

https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_grenadelauncher.cpp // this has also interesting information on The Loose Cannon

https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_grenadelauncher.h 

#define TF_ARROW_MAX_CHARGE_TIME 5.0f //this is weird 
https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_compound_bow.cpp

float CTFCompoundBow::GetProjectileSpeed( void )
{
	return RemapValClamped( GetCurrentCharge(), 0.0f, 1.f, 1800, 2600 ); // wiki lied here aswell
}

//-----------------------------------------------------------------------------
// Purpose: 
//-----------------------------------------------------------------------------
float CTFCompoundBow::GetProjectileGravity( void )
{
	return RemapValClamped( GetCurrentCharge(), 0.0f, 1.f, 0.5, 0.1 );
}
// also very weird

str8 from sdk and tf2 leak 

enjoy this public information, should correct some stuff on demoman  -fourteen

**Comment by xxmyn** [comment]
I hate this post.
The compound bow info is done correctly, TF_ARROW_MAX_CHARGE_TIME is in reference to the point when ["extreme" spread is added to the arrow](https://github.com/OthmanAba/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/game/shared/tf/tf_weapon_compound_bow.cpp#L542C16-L542C16). The wiki also doesn't lie about the compound bow, you can't fire the weapon with 0 charge time.

The gravity for fully charged stickies is almost definitely wrong, but that's not something you properly talk about here.

also you can send link to lines, you don't need to send the entire page for each source, and please learn markdown.
