### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ilya228011** [Fedoraware/Fedoraware#931]
![image](https://user-images.githubusercontent.com/95689124/213896164-5912aa29-0d56-49bc-9b61-e70a65329cc4.png)

**Comment by stax132349** [comment]
![image](https://user-images.githubusercontent.com/90155114/213896365-d0191bb7-d76b-4161-baea-d8d9dcff4dbc.png)
hmm i wonder what the issue is

**Comment by stax132349** [comment]
clearly something on your end by the way

**Comment by ilya228011** [comment]
i dont know

**Comment by ilya228011** [comment]
what could I have done wrong

**Comment by N1kolasFlaV** [comment]
give him the font bro! stop being so rude stax!
