### ISSUE TITLE
(REQUEST) "auto peek on backtrack only" does not work anymore.

### ISSUE THREAD

**Issue by yujispin990** [Fedoraware/Fedoraware#935]
After the addition of new backtrack methods auto peek will always peek even though backtrack is enabled. I requested this feature before and it was implemented amazingly! hopefully it can be implemented again, Thank you.

**Comment by JDNA364PROC** [comment]
proj aimbot is now shooting at backtrack.
so when proj aimbot backtrack?

**Comment by cheeseliker42** [comment]
never you dumbass

**Comment by JDNA364PROC** [comment]
> never you dumbass

mean

**Comment by johnathon-walnut** [comment]
Be nice

**Comment by cheeseliker42** [comment]
ok mfed

**Comment by xxmyn** [comment]
Please try the changes made in [this](https://github.com/Fedoraware/Fedoraware/tree/BacktrackAutopeek) branch & tell me if they work.

**Comment by johnathon-walnut** [comment]
@xxmyn how do I stop getting notifications related to this in my email thanks
