### ISSUE TITLE
delete this cheat please it ruined my life.

### ISSUE THREAD

**Issue by xxmyn** [Fedoraware/Fedoraware#945]
so today i went to get a job right just a simple job right where id do tech support for customers of this random product, any way pretty simple i thought, probably wont need any code BUT i will tell em about my github when i apply for this job right and they will probably just ignore it but whatever, so i apply for this job right and then they send me an email pretty stock standard saying they want an interview at some point and if 12:00 on a saturday would be alright and if id be okay travelling or would have to do it remotely blah blah allat, anyway, i go down to sydney, i take a 2 hour train down to sydney, i get into the room and the interviewer is there, with all my commit history printed out right, like he looks me directly in the eyes and i just glance down and see "buttplug went thwoomp" and immediately i know what he is holding, so like i sit down all awkward, and he looks @ me and says "this isn't acceptable" right and im like "yeah ik but i was dumb when i wrote that aye" and he just looks so dissapointed its not even funny and like after like 3 minutes of him sitting there staring at me this dude walks in and says "wow ur that retarded paster with the buttplug thing aren't you, ur a personal hero can you please sign this" and i reach out to sign the side of his shirt cause thats what he was holding out and he pulls back and just starts laughing and screaming like "r u retarded, did you genuinely think i would want the signature of the worst paster in the world" and then he just kept laughing and i started crying and now im on the train home and im in tears so please delete fedoraware thank you.

**Comment by HutchyBean** [comment]
+rep delete fedoraware

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/215232485-77a5d880-18f1-4e06-a661-f05b9255d125.png)

**Comment by imgladnotu** [comment]
you can delete the repository, but not the degeneracies of people, and the numerous forks and copies of the cheat's source )))))))))))))

**Comment by xDroflLOL** [comment]
> you can delete the repository, but not the degeneracies of people, and the numerous forks and copies of the cheat's source )))))))))))))

yeah...

**Comment by MCPEnguXD** [comment]
no balls

**Comment by cheeseliker42** [comment]
shut up baan u fuckin bitch

**Comment by xxmyn** [comment]
please delete repo itS SO BAD

**Comment by MCPEnguXD** [comment]
ask mfed to do it nerd

**Comment by cheeseliker42** [comment]
why you so mad dude

**Comment by cheeseliker42** [comment]
did u get banned

**Comment by Capybaron** [comment]
dew it.

**Comment by xxmyn** [comment]
> did u get banned

omg i was banned after I left those f*cking nazis dont want me telling them to delete the cheat!!!

**Comment by cheeseliker42** [comment]
you're a tranny

**Comment by cheeseliker42** [comment]
shutup

**Comment by cheeseliker42** [comment]
L+ratio + enjoy your new life

**Comment by hyperventilation** [comment]
helo based derpamernment?
