### ISSUE TITLE
Folllowbot crashing 

### ISSUE THREAD

**Issue by tf2embl** [Fedoraware/Fedoraware#946]
**Fedoraware Version Date: Latest**  

## Config used:
https://anonfiles.com/817e41U5y5/vegas_fw
https://anonfiles.com/N57444Uey6/vegass_fw <-- visuals

## Description:  
if the player that the followbot is following leaves the game in anyway it crashes the game

## Steps to reproduce:  
1. Enable follow bot on a player
2. The player that the bot is following leaves
3. Crash

**Comment by xxmyn** [comment]
Can be recreated with bots, error occurs [here](https://github.com/Fedoraware/Fedoraware/blob/14fdf68946a717b67b193af6f948a8acb37f7e1c/Fedoraware/TeamFortress2/TeamFortress2/Features/Followbot/Followbot.cpp#L71)
