### ISSUE TITLE
Crashes a lot

### ISSUE THREAD

**Issue by FishyFish21** [Fedoraware/Fedoraware#949]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by cheeseliker42** [comment]
looks like skill issue ngl

**Comment by cheeseliker42** [comment]
what class do you usually crash on?
