### ISSUE TITLE
While using smooth aimbot, would randomly look down

### ISSUE THREAD

**Issue by someid1ot** [Fedoraware/Fedoraware#963]
2023-08-03
## Description:  

On a tf2 casual match I pressed my smooth aimbot key (Shift) and immediately looked down.
Tried with a few more configs and I have had the same problem.
I also tried on singleplayer but the issue remained. This only started today.

## Steps to reproduce:  
I am unable to reproduce it at will.
It is random, sometimes I wont look down but other times I will.
I do know that it only looks down when the aimbot has a target, if the aimbot has no target and you spam the aimbot key nothing happens.

Whenever you have a target just spam shift a bunch of times.
If you dont get it please let me know.

**Comment by xxmyn** [comment]
Weird, I seem to get this without aimbot on some projectiles, I'll look into it soon, not sure what would cause it.
