### ISSUE TITLE
Followbot not working

### ISSUE THREAD

**Issue by SuperVitu64** [Fedoraware/Fedoraware#995]
**Fedoraware Version Date: Latest**  
**Windows Version: Windows 10 Pro (The bot i'm trying to make it follow me also runs 10 Pro)**    

## Description:
I have a VM that i set up as the bot that should follow me. No matter what i configure from the followbot tab, the bot doesn't do anyting and stays there

## Steps to reproduce:
Make a VM with W10 and install TF2 on it
Be on a casual match with both accs and enable followbot on guest
Start to wonder why the hell does it not work
- [x] With the steps below I am able to consistently reproduce this issue.

## Additional info:

this issue looks really bad written im so sorry

**Comment by xxmyn** [comment]
We try not to support botting activities in general, if you could create a video of the issue occurring from the bots PoV, that would be great.

**Comment by SuperVitu64** [comment]
Frick- sorry, didnt know that one

Atm im not at my computer to send a video (will do it as soon as i reach my pc) but the thing is the followbot computer does absolutely nothing even if followbot is activated.
